"""
Tier 2 State-Owned Enterprise Board Members.
Monopoly Commercial Leaders.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional

@dataclass
class PEPProfile:
    pep_id: str
    full_name: str
    country_code: str
    country_name: str
    tier: int
    role_title: str
    department_or_agency: str
    is_active: bool = True
    risk_score: float = 8.5
    source_of_wealth: Optional[str] = None
    aliases: List[str] = field(default_factory=list)

PEP_RECORDS_TIER2_SOE_EXECUTIVES: Dict[str, PEPProfile] = {
    "PEP-07-0001": PEPProfile(
        pep_id="PEP-07-0001",
        full_name="Arthur Silva",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #1",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Arthur", "Hon. Arthur Silva"]
    ),
    "PEP-07-0002": PEPProfile(
        pep_id="PEP-07-0002",
        full_name="Beatrice Chen",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #2",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Beatrice", "Hon. Beatrice Chen"]
    ),
    "PEP-07-0003": PEPProfile(
        pep_id="PEP-07-0003",
        full_name="Carlos Fernandez",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #3",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Carlos", "Hon. Carlos Fernandez"]
    ),
    "PEP-07-0004": PEPProfile(
        pep_id="PEP-07-0004",
        full_name="Dmitri Patel",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #4",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Dmitri", "Hon. Dmitri Patel"]
    ),
    "PEP-07-0005": PEPProfile(
        pep_id="PEP-07-0005",
        full_name="Elena Reddy",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #5",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Elena", "Hon. Elena Reddy"]
    ),
    "PEP-07-0006": PEPProfile(
        pep_id="PEP-07-0006",
        full_name="Fatima Mercer",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #6",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Fatima", "Hon. Fatima Mercer"]
    ),
    "PEP-07-0007": PEPProfile(
        pep_id="PEP-07-0007",
        full_name="Gabriel Schneider",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #7",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Gabriel", "Hon. Gabriel Schneider"]
    ),
    "PEP-07-0008": PEPProfile(
        pep_id="PEP-07-0008",
        full_name="Helena Lombardi",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #8",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Helena", "Hon. Helena Lombardi"]
    ),
    "PEP-07-0009": PEPProfile(
        pep_id="PEP-07-0009",
        full_name="Ibrahim Weber",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #9",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Ibrahim", "Hon. Ibrahim Weber"]
    ),
    "PEP-07-0010": PEPProfile(
        pep_id="PEP-07-0010",
        full_name="Julia Kovacs",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #10",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Julia", "Hon. Julia Kovacs"]
    ),
    "PEP-07-0011": PEPProfile(
        pep_id="PEP-07-0011",
        full_name="Klaus Khan",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #11",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Klaus", "Hon. Klaus Khan"]
    ),
    "PEP-07-0012": PEPProfile(
        pep_id="PEP-07-0012",
        full_name="Lucia Rahman",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #12",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Lucia", "Hon. Lucia Rahman"]
    ),
    "PEP-07-0013": PEPProfile(
        pep_id="PEP-07-0013",
        full_name="Mateo Vargas",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #13",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Mateo", "Hon. Mateo Vargas"]
    ),
    "PEP-07-0014": PEPProfile(
        pep_id="PEP-07-0014",
        full_name="Nadia Al-Sayed",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #14",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Nadia", "Hon. Nadia Al-Sayed"]
    ),
    "PEP-07-0015": PEPProfile(
        pep_id="PEP-07-0015",
        full_name="Omar Mansour",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #15",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Omar", "Hon. Omar Mansour"]
    ),
    "PEP-07-0016": PEPProfile(
        pep_id="PEP-07-0016",
        full_name="Pradeep Santos",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #16",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Pradeep", "Hon. Pradeep Santos"]
    ),
    "PEP-07-0017": PEPProfile(
        pep_id="PEP-07-0017",
        full_name="Qasim Haddad",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #17",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Qasim", "Hon. Qasim Haddad"]
    ),
    "PEP-07-0018": PEPProfile(
        pep_id="PEP-07-0018",
        full_name="Rosa Morales",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #18",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Rosa", "Hon. Rosa Morales"]
    ),
    "PEP-07-0019": PEPProfile(
        pep_id="PEP-07-0019",
        full_name="Siddharth Sterling",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #19",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Siddharth", "Hon. Siddharth Sterling"]
    ),
    "PEP-07-0020": PEPProfile(
        pep_id="PEP-07-0020",
        full_name="Tariq Volkov",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #20",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Tariq", "Hon. Tariq Volkov"]
    ),
    "PEP-07-0021": PEPProfile(
        pep_id="PEP-07-0021",
        full_name="Arthur Silva",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #21",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Arthur", "Hon. Arthur Silva"]
    ),
    "PEP-07-0022": PEPProfile(
        pep_id="PEP-07-0022",
        full_name="Beatrice Chen",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #22",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Beatrice", "Hon. Beatrice Chen"]
    ),
    "PEP-07-0023": PEPProfile(
        pep_id="PEP-07-0023",
        full_name="Carlos Fernandez",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #23",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Carlos", "Hon. Carlos Fernandez"]
    ),
    "PEP-07-0024": PEPProfile(
        pep_id="PEP-07-0024",
        full_name="Dmitri Patel",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #24",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Dmitri", "Hon. Dmitri Patel"]
    ),
    "PEP-07-0025": PEPProfile(
        pep_id="PEP-07-0025",
        full_name="Elena Reddy",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #25",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Elena", "Hon. Elena Reddy"]
    ),
    "PEP-07-0026": PEPProfile(
        pep_id="PEP-07-0026",
        full_name="Fatima Mercer",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #26",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Fatima", "Hon. Fatima Mercer"]
    ),
    "PEP-07-0027": PEPProfile(
        pep_id="PEP-07-0027",
        full_name="Gabriel Schneider",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #27",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Gabriel", "Hon. Gabriel Schneider"]
    ),
    "PEP-07-0028": PEPProfile(
        pep_id="PEP-07-0028",
        full_name="Helena Lombardi",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #28",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Helena", "Hon. Helena Lombardi"]
    ),
    "PEP-07-0029": PEPProfile(
        pep_id="PEP-07-0029",
        full_name="Ibrahim Weber",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #29",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Ibrahim", "Hon. Ibrahim Weber"]
    ),
    "PEP-07-0030": PEPProfile(
        pep_id="PEP-07-0030",
        full_name="Julia Kovacs",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #30",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Julia", "Hon. Julia Kovacs"]
    ),
    "PEP-07-0031": PEPProfile(
        pep_id="PEP-07-0031",
        full_name="Klaus Khan",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #31",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Klaus", "Hon. Klaus Khan"]
    ),
    "PEP-07-0032": PEPProfile(
        pep_id="PEP-07-0032",
        full_name="Lucia Rahman",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #32",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Lucia", "Hon. Lucia Rahman"]
    ),
    "PEP-07-0033": PEPProfile(
        pep_id="PEP-07-0033",
        full_name="Mateo Vargas",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #33",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Mateo", "Hon. Mateo Vargas"]
    ),
    "PEP-07-0034": PEPProfile(
        pep_id="PEP-07-0034",
        full_name="Nadia Al-Sayed",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #34",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Nadia", "Hon. Nadia Al-Sayed"]
    ),
    "PEP-07-0035": PEPProfile(
        pep_id="PEP-07-0035",
        full_name="Omar Mansour",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #35",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Omar", "Hon. Omar Mansour"]
    ),
    "PEP-07-0036": PEPProfile(
        pep_id="PEP-07-0036",
        full_name="Pradeep Santos",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #36",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Pradeep", "Hon. Pradeep Santos"]
    ),
    "PEP-07-0037": PEPProfile(
        pep_id="PEP-07-0037",
        full_name="Qasim Haddad",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #37",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Qasim", "Hon. Qasim Haddad"]
    ),
    "PEP-07-0038": PEPProfile(
        pep_id="PEP-07-0038",
        full_name="Rosa Morales",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #38",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Rosa", "Hon. Rosa Morales"]
    ),
    "PEP-07-0039": PEPProfile(
        pep_id="PEP-07-0039",
        full_name="Siddharth Sterling",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #39",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Siddharth", "Hon. Siddharth Sterling"]
    ),
    "PEP-07-0040": PEPProfile(
        pep_id="PEP-07-0040",
        full_name="Tariq Volkov",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #40",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Tariq", "Hon. Tariq Volkov"]
    ),
    "PEP-07-0041": PEPProfile(
        pep_id="PEP-07-0041",
        full_name="Arthur Silva",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #41",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Arthur", "Hon. Arthur Silva"]
    ),
    "PEP-07-0042": PEPProfile(
        pep_id="PEP-07-0042",
        full_name="Beatrice Chen",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #42",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Beatrice", "Hon. Beatrice Chen"]
    ),
    "PEP-07-0043": PEPProfile(
        pep_id="PEP-07-0043",
        full_name="Carlos Fernandez",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #43",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Carlos", "Hon. Carlos Fernandez"]
    ),
    "PEP-07-0044": PEPProfile(
        pep_id="PEP-07-0044",
        full_name="Dmitri Patel",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #44",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Dmitri", "Hon. Dmitri Patel"]
    ),
    "PEP-07-0045": PEPProfile(
        pep_id="PEP-07-0045",
        full_name="Elena Reddy",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #45",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Elena", "Hon. Elena Reddy"]
    ),
    "PEP-07-0046": PEPProfile(
        pep_id="PEP-07-0046",
        full_name="Fatima Mercer",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #46",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Fatima", "Hon. Fatima Mercer"]
    ),
    "PEP-07-0047": PEPProfile(
        pep_id="PEP-07-0047",
        full_name="Gabriel Schneider",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #47",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Gabriel", "Hon. Gabriel Schneider"]
    ),
    "PEP-07-0048": PEPProfile(
        pep_id="PEP-07-0048",
        full_name="Helena Lombardi",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #48",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Helena", "Hon. Helena Lombardi"]
    ),
    "PEP-07-0049": PEPProfile(
        pep_id="PEP-07-0049",
        full_name="Ibrahim Weber",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #49",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Ibrahim", "Hon. Ibrahim Weber"]
    ),
    "PEP-07-0050": PEPProfile(
        pep_id="PEP-07-0050",
        full_name="Julia Kovacs",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #50",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Julia", "Hon. Julia Kovacs"]
    ),
    "PEP-07-0051": PEPProfile(
        pep_id="PEP-07-0051",
        full_name="Klaus Khan",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #51",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Klaus", "Hon. Klaus Khan"]
    ),
    "PEP-07-0052": PEPProfile(
        pep_id="PEP-07-0052",
        full_name="Lucia Rahman",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #52",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Lucia", "Hon. Lucia Rahman"]
    ),
    "PEP-07-0053": PEPProfile(
        pep_id="PEP-07-0053",
        full_name="Mateo Vargas",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #53",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Mateo", "Hon. Mateo Vargas"]
    ),
    "PEP-07-0054": PEPProfile(
        pep_id="PEP-07-0054",
        full_name="Nadia Al-Sayed",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #54",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Nadia", "Hon. Nadia Al-Sayed"]
    ),
    "PEP-07-0055": PEPProfile(
        pep_id="PEP-07-0055",
        full_name="Omar Mansour",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #55",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Omar", "Hon. Omar Mansour"]
    ),
    "PEP-07-0056": PEPProfile(
        pep_id="PEP-07-0056",
        full_name="Pradeep Santos",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #56",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Pradeep", "Hon. Pradeep Santos"]
    ),
    "PEP-07-0057": PEPProfile(
        pep_id="PEP-07-0057",
        full_name="Qasim Haddad",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #57",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Qasim", "Hon. Qasim Haddad"]
    ),
    "PEP-07-0058": PEPProfile(
        pep_id="PEP-07-0058",
        full_name="Rosa Morales",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #58",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Rosa", "Hon. Rosa Morales"]
    ),
    "PEP-07-0059": PEPProfile(
        pep_id="PEP-07-0059",
        full_name="Siddharth Sterling",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #59",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Siddharth", "Hon. Siddharth Sterling"]
    ),
    "PEP-07-0060": PEPProfile(
        pep_id="PEP-07-0060",
        full_name="Tariq Volkov",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #60",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Tariq", "Hon. Tariq Volkov"]
    ),
    "PEP-07-0061": PEPProfile(
        pep_id="PEP-07-0061",
        full_name="Arthur Silva",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #61",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Arthur", "Hon. Arthur Silva"]
    ),
    "PEP-07-0062": PEPProfile(
        pep_id="PEP-07-0062",
        full_name="Beatrice Chen",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #62",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Beatrice", "Hon. Beatrice Chen"]
    ),
    "PEP-07-0063": PEPProfile(
        pep_id="PEP-07-0063",
        full_name="Carlos Fernandez",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #63",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Carlos", "Hon. Carlos Fernandez"]
    ),
    "PEP-07-0064": PEPProfile(
        pep_id="PEP-07-0064",
        full_name="Dmitri Patel",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #64",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Dmitri", "Hon. Dmitri Patel"]
    ),
    "PEP-07-0065": PEPProfile(
        pep_id="PEP-07-0065",
        full_name="Elena Reddy",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #65",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Elena", "Hon. Elena Reddy"]
    ),
    "PEP-07-0066": PEPProfile(
        pep_id="PEP-07-0066",
        full_name="Fatima Mercer",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #66",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Fatima", "Hon. Fatima Mercer"]
    ),
    "PEP-07-0067": PEPProfile(
        pep_id="PEP-07-0067",
        full_name="Gabriel Schneider",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #67",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Gabriel", "Hon. Gabriel Schneider"]
    ),
    "PEP-07-0068": PEPProfile(
        pep_id="PEP-07-0068",
        full_name="Helena Lombardi",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #68",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Helena", "Hon. Helena Lombardi"]
    ),
    "PEP-07-0069": PEPProfile(
        pep_id="PEP-07-0069",
        full_name="Ibrahim Weber",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #69",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Ibrahim", "Hon. Ibrahim Weber"]
    ),
    "PEP-07-0070": PEPProfile(
        pep_id="PEP-07-0070",
        full_name="Julia Kovacs",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #70",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Julia", "Hon. Julia Kovacs"]
    ),
    "PEP-07-0071": PEPProfile(
        pep_id="PEP-07-0071",
        full_name="Klaus Khan",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #71",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Klaus", "Hon. Klaus Khan"]
    ),
    "PEP-07-0072": PEPProfile(
        pep_id="PEP-07-0072",
        full_name="Lucia Rahman",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #72",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Lucia", "Hon. Lucia Rahman"]
    ),
    "PEP-07-0073": PEPProfile(
        pep_id="PEP-07-0073",
        full_name="Mateo Vargas",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #73",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Mateo", "Hon. Mateo Vargas"]
    ),
    "PEP-07-0074": PEPProfile(
        pep_id="PEP-07-0074",
        full_name="Nadia Al-Sayed",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #74",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Nadia", "Hon. Nadia Al-Sayed"]
    ),
    "PEP-07-0075": PEPProfile(
        pep_id="PEP-07-0075",
        full_name="Omar Mansour",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #75",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Omar", "Hon. Omar Mansour"]
    ),
    "PEP-07-0076": PEPProfile(
        pep_id="PEP-07-0076",
        full_name="Pradeep Santos",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #76",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Pradeep", "Hon. Pradeep Santos"]
    ),
    "PEP-07-0077": PEPProfile(
        pep_id="PEP-07-0077",
        full_name="Qasim Haddad",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #77",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Qasim", "Hon. Qasim Haddad"]
    ),
    "PEP-07-0078": PEPProfile(
        pep_id="PEP-07-0078",
        full_name="Rosa Morales",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #78",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Rosa", "Hon. Rosa Morales"]
    ),
    "PEP-07-0079": PEPProfile(
        pep_id="PEP-07-0079",
        full_name="Siddharth Sterling",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #79",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Siddharth", "Hon. Siddharth Sterling"]
    ),
    "PEP-07-0080": PEPProfile(
        pep_id="PEP-07-0080",
        full_name="Tariq Volkov",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #80",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Tariq", "Hon. Tariq Volkov"]
    ),
    "PEP-07-0081": PEPProfile(
        pep_id="PEP-07-0081",
        full_name="Arthur Silva",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #81",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Arthur", "Hon. Arthur Silva"]
    ),
    "PEP-07-0082": PEPProfile(
        pep_id="PEP-07-0082",
        full_name="Beatrice Chen",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #82",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Beatrice", "Hon. Beatrice Chen"]
    ),
    "PEP-07-0083": PEPProfile(
        pep_id="PEP-07-0083",
        full_name="Carlos Fernandez",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #83",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Carlos", "Hon. Carlos Fernandez"]
    ),
    "PEP-07-0084": PEPProfile(
        pep_id="PEP-07-0084",
        full_name="Dmitri Patel",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #84",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Dmitri", "Hon. Dmitri Patel"]
    ),
    "PEP-07-0085": PEPProfile(
        pep_id="PEP-07-0085",
        full_name="Elena Reddy",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #85",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Elena", "Hon. Elena Reddy"]
    ),
    "PEP-07-0086": PEPProfile(
        pep_id="PEP-07-0086",
        full_name="Fatima Mercer",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #86",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Fatima", "Hon. Fatima Mercer"]
    ),
    "PEP-07-0087": PEPProfile(
        pep_id="PEP-07-0087",
        full_name="Gabriel Schneider",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #87",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Gabriel", "Hon. Gabriel Schneider"]
    ),
    "PEP-07-0088": PEPProfile(
        pep_id="PEP-07-0088",
        full_name="Helena Lombardi",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #88",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Helena", "Hon. Helena Lombardi"]
    ),
    "PEP-07-0089": PEPProfile(
        pep_id="PEP-07-0089",
        full_name="Ibrahim Weber",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #89",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Ibrahim", "Hon. Ibrahim Weber"]
    ),
    "PEP-07-0090": PEPProfile(
        pep_id="PEP-07-0090",
        full_name="Julia Kovacs",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #90",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Julia", "Hon. Julia Kovacs"]
    ),
    "PEP-07-0091": PEPProfile(
        pep_id="PEP-07-0091",
        full_name="Klaus Khan",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #91",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Klaus", "Hon. Klaus Khan"]
    ),
    "PEP-07-0092": PEPProfile(
        pep_id="PEP-07-0092",
        full_name="Lucia Rahman",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #92",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Lucia", "Hon. Lucia Rahman"]
    ),
    "PEP-07-0093": PEPProfile(
        pep_id="PEP-07-0093",
        full_name="Mateo Vargas",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #93",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Mateo", "Hon. Mateo Vargas"]
    ),
    "PEP-07-0094": PEPProfile(
        pep_id="PEP-07-0094",
        full_name="Nadia Al-Sayed",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #94",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Nadia", "Hon. Nadia Al-Sayed"]
    ),
    "PEP-07-0095": PEPProfile(
        pep_id="PEP-07-0095",
        full_name="Omar Mansour",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #95",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Omar", "Hon. Omar Mansour"]
    ),
    "PEP-07-0096": PEPProfile(
        pep_id="PEP-07-0096",
        full_name="Pradeep Santos",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #96",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Pradeep", "Hon. Pradeep Santos"]
    ),
    "PEP-07-0097": PEPProfile(
        pep_id="PEP-07-0097",
        full_name="Qasim Haddad",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #97",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Qasim", "Hon. Qasim Haddad"]
    ),
    "PEP-07-0098": PEPProfile(
        pep_id="PEP-07-0098",
        full_name="Rosa Morales",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #98",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Rosa", "Hon. Rosa Morales"]
    ),
    "PEP-07-0099": PEPProfile(
        pep_id="PEP-07-0099",
        full_name="Siddharth Sterling",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #99",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Siddharth", "Hon. Siddharth Sterling"]
    ),
    "PEP-07-0100": PEPProfile(
        pep_id="PEP-07-0100",
        full_name="Tariq Volkov",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #100",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Tariq", "Hon. Tariq Volkov"]
    ),
    "PEP-07-0101": PEPProfile(
        pep_id="PEP-07-0101",
        full_name="Arthur Silva",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #101",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Arthur", "Hon. Arthur Silva"]
    ),
    "PEP-07-0102": PEPProfile(
        pep_id="PEP-07-0102",
        full_name="Beatrice Chen",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #102",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Beatrice", "Hon. Beatrice Chen"]
    ),
    "PEP-07-0103": PEPProfile(
        pep_id="PEP-07-0103",
        full_name="Carlos Fernandez",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #103",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Carlos", "Hon. Carlos Fernandez"]
    ),
    "PEP-07-0104": PEPProfile(
        pep_id="PEP-07-0104",
        full_name="Dmitri Patel",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #104",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Dmitri", "Hon. Dmitri Patel"]
    ),
    "PEP-07-0105": PEPProfile(
        pep_id="PEP-07-0105",
        full_name="Elena Reddy",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #105",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Elena", "Hon. Elena Reddy"]
    ),
    "PEP-07-0106": PEPProfile(
        pep_id="PEP-07-0106",
        full_name="Fatima Mercer",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #106",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Fatima", "Hon. Fatima Mercer"]
    ),
    "PEP-07-0107": PEPProfile(
        pep_id="PEP-07-0107",
        full_name="Gabriel Schneider",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #107",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Gabriel", "Hon. Gabriel Schneider"]
    ),
    "PEP-07-0108": PEPProfile(
        pep_id="PEP-07-0108",
        full_name="Helena Lombardi",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #108",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Helena", "Hon. Helena Lombardi"]
    ),
    "PEP-07-0109": PEPProfile(
        pep_id="PEP-07-0109",
        full_name="Ibrahim Weber",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #109",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Ibrahim", "Hon. Ibrahim Weber"]
    ),
    "PEP-07-0110": PEPProfile(
        pep_id="PEP-07-0110",
        full_name="Julia Kovacs",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #110",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Julia", "Hon. Julia Kovacs"]
    ),
    "PEP-07-0111": PEPProfile(
        pep_id="PEP-07-0111",
        full_name="Klaus Khan",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #111",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Klaus", "Hon. Klaus Khan"]
    ),
    "PEP-07-0112": PEPProfile(
        pep_id="PEP-07-0112",
        full_name="Lucia Rahman",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #112",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Lucia", "Hon. Lucia Rahman"]
    ),
    "PEP-07-0113": PEPProfile(
        pep_id="PEP-07-0113",
        full_name="Mateo Vargas",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #113",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Mateo", "Hon. Mateo Vargas"]
    ),
    "PEP-07-0114": PEPProfile(
        pep_id="PEP-07-0114",
        full_name="Nadia Al-Sayed",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #114",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Nadia", "Hon. Nadia Al-Sayed"]
    ),
    "PEP-07-0115": PEPProfile(
        pep_id="PEP-07-0115",
        full_name="Omar Mansour",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #115",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Omar", "Hon. Omar Mansour"]
    ),
    "PEP-07-0116": PEPProfile(
        pep_id="PEP-07-0116",
        full_name="Pradeep Santos",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #116",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Pradeep", "Hon. Pradeep Santos"]
    ),
    "PEP-07-0117": PEPProfile(
        pep_id="PEP-07-0117",
        full_name="Qasim Haddad",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #117",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Qasim", "Hon. Qasim Haddad"]
    ),
    "PEP-07-0118": PEPProfile(
        pep_id="PEP-07-0118",
        full_name="Rosa Morales",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #118",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Rosa", "Hon. Rosa Morales"]
    ),
    "PEP-07-0119": PEPProfile(
        pep_id="PEP-07-0119",
        full_name="Siddharth Sterling",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #119",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Siddharth", "Hon. Siddharth Sterling"]
    ),
    "PEP-07-0120": PEPProfile(
        pep_id="PEP-07-0120",
        full_name="Tariq Volkov",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #120",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Tariq", "Hon. Tariq Volkov"]
    ),
    "PEP-07-0121": PEPProfile(
        pep_id="PEP-07-0121",
        full_name="Arthur Silva",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #121",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Arthur", "Hon. Arthur Silva"]
    ),
    "PEP-07-0122": PEPProfile(
        pep_id="PEP-07-0122",
        full_name="Beatrice Chen",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #122",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Beatrice", "Hon. Beatrice Chen"]
    ),
    "PEP-07-0123": PEPProfile(
        pep_id="PEP-07-0123",
        full_name="Carlos Fernandez",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #123",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Carlos", "Hon. Carlos Fernandez"]
    ),
    "PEP-07-0124": PEPProfile(
        pep_id="PEP-07-0124",
        full_name="Dmitri Patel",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #124",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Dmitri", "Hon. Dmitri Patel"]
    ),
    "PEP-07-0125": PEPProfile(
        pep_id="PEP-07-0125",
        full_name="Elena Reddy",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #125",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Elena", "Hon. Elena Reddy"]
    ),
    "PEP-07-0126": PEPProfile(
        pep_id="PEP-07-0126",
        full_name="Fatima Mercer",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #126",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Fatima", "Hon. Fatima Mercer"]
    ),
    "PEP-07-0127": PEPProfile(
        pep_id="PEP-07-0127",
        full_name="Gabriel Schneider",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #127",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Gabriel", "Hon. Gabriel Schneider"]
    ),
    "PEP-07-0128": PEPProfile(
        pep_id="PEP-07-0128",
        full_name="Helena Lombardi",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #128",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Helena", "Hon. Helena Lombardi"]
    ),
    "PEP-07-0129": PEPProfile(
        pep_id="PEP-07-0129",
        full_name="Ibrahim Weber",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #129",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Ibrahim", "Hon. Ibrahim Weber"]
    ),
    "PEP-07-0130": PEPProfile(
        pep_id="PEP-07-0130",
        full_name="Julia Kovacs",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #130",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Julia", "Hon. Julia Kovacs"]
    ),
    "PEP-07-0131": PEPProfile(
        pep_id="PEP-07-0131",
        full_name="Klaus Khan",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #131",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Klaus", "Hon. Klaus Khan"]
    ),
    "PEP-07-0132": PEPProfile(
        pep_id="PEP-07-0132",
        full_name="Lucia Rahman",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #132",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Lucia", "Hon. Lucia Rahman"]
    ),
    "PEP-07-0133": PEPProfile(
        pep_id="PEP-07-0133",
        full_name="Mateo Vargas",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #133",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Mateo", "Hon. Mateo Vargas"]
    ),
    "PEP-07-0134": PEPProfile(
        pep_id="PEP-07-0134",
        full_name="Nadia Al-Sayed",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #134",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Nadia", "Hon. Nadia Al-Sayed"]
    ),
    "PEP-07-0135": PEPProfile(
        pep_id="PEP-07-0135",
        full_name="Omar Mansour",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #135",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Omar", "Hon. Omar Mansour"]
    ),
    "PEP-07-0136": PEPProfile(
        pep_id="PEP-07-0136",
        full_name="Pradeep Santos",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #136",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Pradeep", "Hon. Pradeep Santos"]
    ),
    "PEP-07-0137": PEPProfile(
        pep_id="PEP-07-0137",
        full_name="Qasim Haddad",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #137",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Qasim", "Hon. Qasim Haddad"]
    ),
    "PEP-07-0138": PEPProfile(
        pep_id="PEP-07-0138",
        full_name="Rosa Morales",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #138",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Rosa", "Hon. Rosa Morales"]
    ),
    "PEP-07-0139": PEPProfile(
        pep_id="PEP-07-0139",
        full_name="Siddharth Sterling",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #139",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Siddharth", "Hon. Siddharth Sterling"]
    ),
    "PEP-07-0140": PEPProfile(
        pep_id="PEP-07-0140",
        full_name="Tariq Volkov",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #140",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Tariq", "Hon. Tariq Volkov"]
    ),
    "PEP-07-0141": PEPProfile(
        pep_id="PEP-07-0141",
        full_name="Arthur Silva",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #141",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Arthur", "Hon. Arthur Silva"]
    ),
    "PEP-07-0142": PEPProfile(
        pep_id="PEP-07-0142",
        full_name="Beatrice Chen",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #142",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Beatrice", "Hon. Beatrice Chen"]
    ),
    "PEP-07-0143": PEPProfile(
        pep_id="PEP-07-0143",
        full_name="Carlos Fernandez",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #143",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Carlos", "Hon. Carlos Fernandez"]
    ),
    "PEP-07-0144": PEPProfile(
        pep_id="PEP-07-0144",
        full_name="Dmitri Patel",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #144",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Dmitri", "Hon. Dmitri Patel"]
    ),
    "PEP-07-0145": PEPProfile(
        pep_id="PEP-07-0145",
        full_name="Elena Reddy",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #145",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Elena", "Hon. Elena Reddy"]
    ),
    "PEP-07-0146": PEPProfile(
        pep_id="PEP-07-0146",
        full_name="Fatima Mercer",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #146",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Fatima", "Hon. Fatima Mercer"]
    ),
    "PEP-07-0147": PEPProfile(
        pep_id="PEP-07-0147",
        full_name="Gabriel Schneider",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #147",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Gabriel", "Hon. Gabriel Schneider"]
    ),
    "PEP-07-0148": PEPProfile(
        pep_id="PEP-07-0148",
        full_name="Helena Lombardi",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #148",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Helena", "Hon. Helena Lombardi"]
    ),
    "PEP-07-0149": PEPProfile(
        pep_id="PEP-07-0149",
        full_name="Ibrahim Weber",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #149",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Ibrahim", "Hon. Ibrahim Weber"]
    ),
    "PEP-07-0150": PEPProfile(
        pep_id="PEP-07-0150",
        full_name="Julia Kovacs",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #150",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Julia", "Hon. Julia Kovacs"]
    ),
    "PEP-07-0151": PEPProfile(
        pep_id="PEP-07-0151",
        full_name="Klaus Khan",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #151",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Klaus", "Hon. Klaus Khan"]
    ),
    "PEP-07-0152": PEPProfile(
        pep_id="PEP-07-0152",
        full_name="Lucia Rahman",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #152",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Lucia", "Hon. Lucia Rahman"]
    ),
    "PEP-07-0153": PEPProfile(
        pep_id="PEP-07-0153",
        full_name="Mateo Vargas",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #153",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Mateo", "Hon. Mateo Vargas"]
    ),
    "PEP-07-0154": PEPProfile(
        pep_id="PEP-07-0154",
        full_name="Nadia Al-Sayed",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #154",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Nadia", "Hon. Nadia Al-Sayed"]
    ),
    "PEP-07-0155": PEPProfile(
        pep_id="PEP-07-0155",
        full_name="Omar Mansour",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #155",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Omar", "Hon. Omar Mansour"]
    ),
    "PEP-07-0156": PEPProfile(
        pep_id="PEP-07-0156",
        full_name="Pradeep Santos",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #156",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Pradeep", "Hon. Pradeep Santos"]
    ),
    "PEP-07-0157": PEPProfile(
        pep_id="PEP-07-0157",
        full_name="Qasim Haddad",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #157",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Qasim", "Hon. Qasim Haddad"]
    ),
    "PEP-07-0158": PEPProfile(
        pep_id="PEP-07-0158",
        full_name="Rosa Morales",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #158",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Rosa", "Hon. Rosa Morales"]
    ),
    "PEP-07-0159": PEPProfile(
        pep_id="PEP-07-0159",
        full_name="Siddharth Sterling",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #159",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Siddharth", "Hon. Siddharth Sterling"]
    ),
    "PEP-07-0160": PEPProfile(
        pep_id="PEP-07-0160",
        full_name="Tariq Volkov",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #160",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Tariq", "Hon. Tariq Volkov"]
    ),
    "PEP-07-0161": PEPProfile(
        pep_id="PEP-07-0161",
        full_name="Arthur Silva",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #161",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Arthur", "Hon. Arthur Silva"]
    ),
    "PEP-07-0162": PEPProfile(
        pep_id="PEP-07-0162",
        full_name="Beatrice Chen",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #162",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Beatrice", "Hon. Beatrice Chen"]
    ),
    "PEP-07-0163": PEPProfile(
        pep_id="PEP-07-0163",
        full_name="Carlos Fernandez",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #163",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Carlos", "Hon. Carlos Fernandez"]
    ),
    "PEP-07-0164": PEPProfile(
        pep_id="PEP-07-0164",
        full_name="Dmitri Patel",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #164",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Dmitri", "Hon. Dmitri Patel"]
    ),
    "PEP-07-0165": PEPProfile(
        pep_id="PEP-07-0165",
        full_name="Elena Reddy",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #165",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Elena", "Hon. Elena Reddy"]
    ),
    "PEP-07-0166": PEPProfile(
        pep_id="PEP-07-0166",
        full_name="Fatima Mercer",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #166",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Fatima", "Hon. Fatima Mercer"]
    ),
    "PEP-07-0167": PEPProfile(
        pep_id="PEP-07-0167",
        full_name="Gabriel Schneider",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #167",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Gabriel", "Hon. Gabriel Schneider"]
    ),
    "PEP-07-0168": PEPProfile(
        pep_id="PEP-07-0168",
        full_name="Helena Lombardi",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #168",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Helena", "Hon. Helena Lombardi"]
    ),
    "PEP-07-0169": PEPProfile(
        pep_id="PEP-07-0169",
        full_name="Ibrahim Weber",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #169",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Ibrahim", "Hon. Ibrahim Weber"]
    ),
    "PEP-07-0170": PEPProfile(
        pep_id="PEP-07-0170",
        full_name="Julia Kovacs",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #170",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Julia", "Hon. Julia Kovacs"]
    ),
    "PEP-07-0171": PEPProfile(
        pep_id="PEP-07-0171",
        full_name="Klaus Khan",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #171",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Klaus", "Hon. Klaus Khan"]
    ),
    "PEP-07-0172": PEPProfile(
        pep_id="PEP-07-0172",
        full_name="Lucia Rahman",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #172",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Lucia", "Hon. Lucia Rahman"]
    ),
    "PEP-07-0173": PEPProfile(
        pep_id="PEP-07-0173",
        full_name="Mateo Vargas",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #173",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Mateo", "Hon. Mateo Vargas"]
    ),
    "PEP-07-0174": PEPProfile(
        pep_id="PEP-07-0174",
        full_name="Nadia Al-Sayed",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #174",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Nadia", "Hon. Nadia Al-Sayed"]
    ),
    "PEP-07-0175": PEPProfile(
        pep_id="PEP-07-0175",
        full_name="Omar Mansour",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #175",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Omar", "Hon. Omar Mansour"]
    ),
    "PEP-07-0176": PEPProfile(
        pep_id="PEP-07-0176",
        full_name="Pradeep Santos",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #176",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Pradeep", "Hon. Pradeep Santos"]
    ),
    "PEP-07-0177": PEPProfile(
        pep_id="PEP-07-0177",
        full_name="Qasim Haddad",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #177",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Qasim", "Hon. Qasim Haddad"]
    ),
    "PEP-07-0178": PEPProfile(
        pep_id="PEP-07-0178",
        full_name="Rosa Morales",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #178",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Rosa", "Hon. Rosa Morales"]
    ),
    "PEP-07-0179": PEPProfile(
        pep_id="PEP-07-0179",
        full_name="Siddharth Sterling",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #179",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Siddharth", "Hon. Siddharth Sterling"]
    ),
    "PEP-07-0180": PEPProfile(
        pep_id="PEP-07-0180",
        full_name="Tariq Volkov",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 State-Owned Enterprise Board Members Official #180",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Tariq", "Hon. Tariq Volkov"]
    ),
}
