"""
Tier 1 Finance & Treasury Ministers.
National Economic Policymakers.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional

@dataclass
class PEPProfile:
    pep_id: str
    full_name: str
    country_code: str
    country_name: str
    tier: int
    role_title: str
    department_or_agency: str
    is_active: bool = True
    risk_score: float = 8.5
    source_of_wealth: Optional[str] = None
    aliases: List[str] = field(default_factory=list)

PEP_RECORDS_TIER1_FINANCE_MINISTERS: Dict[str, PEPProfile] = {
    "PEP-02-0001": PEPProfile(
        pep_id="PEP-02-0001",
        full_name="Arthur Mercer",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #1",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Arthur", "Hon. Arthur Mercer"]
    ),
    "PEP-02-0002": PEPProfile(
        pep_id="PEP-02-0002",
        full_name="Beatrice Schneider",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #2",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Beatrice", "Hon. Beatrice Schneider"]
    ),
    "PEP-02-0003": PEPProfile(
        pep_id="PEP-02-0003",
        full_name="Carlos Lombardi",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #3",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Carlos", "Hon. Carlos Lombardi"]
    ),
    "PEP-02-0004": PEPProfile(
        pep_id="PEP-02-0004",
        full_name="Dmitri Weber",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #4",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Dmitri", "Hon. Dmitri Weber"]
    ),
    "PEP-02-0005": PEPProfile(
        pep_id="PEP-02-0005",
        full_name="Elena Kovacs",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #5",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Elena", "Hon. Elena Kovacs"]
    ),
    "PEP-02-0006": PEPProfile(
        pep_id="PEP-02-0006",
        full_name="Fatima Khan",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #6",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Fatima", "Hon. Fatima Khan"]
    ),
    "PEP-02-0007": PEPProfile(
        pep_id="PEP-02-0007",
        full_name="Gabriel Rahman",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #7",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Gabriel", "Hon. Gabriel Rahman"]
    ),
    "PEP-02-0008": PEPProfile(
        pep_id="PEP-02-0008",
        full_name="Helena Vargas",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #8",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Helena", "Hon. Helena Vargas"]
    ),
    "PEP-02-0009": PEPProfile(
        pep_id="PEP-02-0009",
        full_name="Ibrahim Al-Sayed",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #9",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Ibrahim", "Hon. Ibrahim Al-Sayed"]
    ),
    "PEP-02-0010": PEPProfile(
        pep_id="PEP-02-0010",
        full_name="Julia Mansour",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #10",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Julia", "Hon. Julia Mansour"]
    ),
    "PEP-02-0011": PEPProfile(
        pep_id="PEP-02-0011",
        full_name="Klaus Santos",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #11",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Klaus", "Hon. Klaus Santos"]
    ),
    "PEP-02-0012": PEPProfile(
        pep_id="PEP-02-0012",
        full_name="Lucia Haddad",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #12",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Lucia", "Hon. Lucia Haddad"]
    ),
    "PEP-02-0013": PEPProfile(
        pep_id="PEP-02-0013",
        full_name="Mateo Morales",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #13",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Mateo", "Hon. Mateo Morales"]
    ),
    "PEP-02-0014": PEPProfile(
        pep_id="PEP-02-0014",
        full_name="Nadia Sterling",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #14",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Nadia", "Hon. Nadia Sterling"]
    ),
    "PEP-02-0015": PEPProfile(
        pep_id="PEP-02-0015",
        full_name="Omar Volkov",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #15",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Omar", "Hon. Omar Volkov"]
    ),
    "PEP-02-0016": PEPProfile(
        pep_id="PEP-02-0016",
        full_name="Pradeep Silva",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #16",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Pradeep", "Hon. Pradeep Silva"]
    ),
    "PEP-02-0017": PEPProfile(
        pep_id="PEP-02-0017",
        full_name="Qasim Chen",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #17",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Qasim", "Hon. Qasim Chen"]
    ),
    "PEP-02-0018": PEPProfile(
        pep_id="PEP-02-0018",
        full_name="Rosa Fernandez",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #18",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Rosa", "Hon. Rosa Fernandez"]
    ),
    "PEP-02-0019": PEPProfile(
        pep_id="PEP-02-0019",
        full_name="Siddharth Patel",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #19",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Siddharth", "Hon. Siddharth Patel"]
    ),
    "PEP-02-0020": PEPProfile(
        pep_id="PEP-02-0020",
        full_name="Tariq Reddy",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #20",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Tariq", "Hon. Tariq Reddy"]
    ),
    "PEP-02-0021": PEPProfile(
        pep_id="PEP-02-0021",
        full_name="Arthur Mercer",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #21",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Arthur", "Hon. Arthur Mercer"]
    ),
    "PEP-02-0022": PEPProfile(
        pep_id="PEP-02-0022",
        full_name="Beatrice Schneider",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #22",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Beatrice", "Hon. Beatrice Schneider"]
    ),
    "PEP-02-0023": PEPProfile(
        pep_id="PEP-02-0023",
        full_name="Carlos Lombardi",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #23",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Carlos", "Hon. Carlos Lombardi"]
    ),
    "PEP-02-0024": PEPProfile(
        pep_id="PEP-02-0024",
        full_name="Dmitri Weber",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #24",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Dmitri", "Hon. Dmitri Weber"]
    ),
    "PEP-02-0025": PEPProfile(
        pep_id="PEP-02-0025",
        full_name="Elena Kovacs",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #25",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Elena", "Hon. Elena Kovacs"]
    ),
    "PEP-02-0026": PEPProfile(
        pep_id="PEP-02-0026",
        full_name="Fatima Khan",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #26",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Fatima", "Hon. Fatima Khan"]
    ),
    "PEP-02-0027": PEPProfile(
        pep_id="PEP-02-0027",
        full_name="Gabriel Rahman",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #27",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Gabriel", "Hon. Gabriel Rahman"]
    ),
    "PEP-02-0028": PEPProfile(
        pep_id="PEP-02-0028",
        full_name="Helena Vargas",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #28",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Helena", "Hon. Helena Vargas"]
    ),
    "PEP-02-0029": PEPProfile(
        pep_id="PEP-02-0029",
        full_name="Ibrahim Al-Sayed",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #29",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Ibrahim", "Hon. Ibrahim Al-Sayed"]
    ),
    "PEP-02-0030": PEPProfile(
        pep_id="PEP-02-0030",
        full_name="Julia Mansour",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #30",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Julia", "Hon. Julia Mansour"]
    ),
    "PEP-02-0031": PEPProfile(
        pep_id="PEP-02-0031",
        full_name="Klaus Santos",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #31",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Klaus", "Hon. Klaus Santos"]
    ),
    "PEP-02-0032": PEPProfile(
        pep_id="PEP-02-0032",
        full_name="Lucia Haddad",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #32",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Lucia", "Hon. Lucia Haddad"]
    ),
    "PEP-02-0033": PEPProfile(
        pep_id="PEP-02-0033",
        full_name="Mateo Morales",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #33",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Mateo", "Hon. Mateo Morales"]
    ),
    "PEP-02-0034": PEPProfile(
        pep_id="PEP-02-0034",
        full_name="Nadia Sterling",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #34",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Nadia", "Hon. Nadia Sterling"]
    ),
    "PEP-02-0035": PEPProfile(
        pep_id="PEP-02-0035",
        full_name="Omar Volkov",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #35",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Omar", "Hon. Omar Volkov"]
    ),
    "PEP-02-0036": PEPProfile(
        pep_id="PEP-02-0036",
        full_name="Pradeep Silva",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #36",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Pradeep", "Hon. Pradeep Silva"]
    ),
    "PEP-02-0037": PEPProfile(
        pep_id="PEP-02-0037",
        full_name="Qasim Chen",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #37",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Qasim", "Hon. Qasim Chen"]
    ),
    "PEP-02-0038": PEPProfile(
        pep_id="PEP-02-0038",
        full_name="Rosa Fernandez",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #38",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Rosa", "Hon. Rosa Fernandez"]
    ),
    "PEP-02-0039": PEPProfile(
        pep_id="PEP-02-0039",
        full_name="Siddharth Patel",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #39",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Siddharth", "Hon. Siddharth Patel"]
    ),
    "PEP-02-0040": PEPProfile(
        pep_id="PEP-02-0040",
        full_name="Tariq Reddy",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #40",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Tariq", "Hon. Tariq Reddy"]
    ),
    "PEP-02-0041": PEPProfile(
        pep_id="PEP-02-0041",
        full_name="Arthur Mercer",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #41",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Arthur", "Hon. Arthur Mercer"]
    ),
    "PEP-02-0042": PEPProfile(
        pep_id="PEP-02-0042",
        full_name="Beatrice Schneider",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #42",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Beatrice", "Hon. Beatrice Schneider"]
    ),
    "PEP-02-0043": PEPProfile(
        pep_id="PEP-02-0043",
        full_name="Carlos Lombardi",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #43",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Carlos", "Hon. Carlos Lombardi"]
    ),
    "PEP-02-0044": PEPProfile(
        pep_id="PEP-02-0044",
        full_name="Dmitri Weber",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #44",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Dmitri", "Hon. Dmitri Weber"]
    ),
    "PEP-02-0045": PEPProfile(
        pep_id="PEP-02-0045",
        full_name="Elena Kovacs",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #45",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Elena", "Hon. Elena Kovacs"]
    ),
    "PEP-02-0046": PEPProfile(
        pep_id="PEP-02-0046",
        full_name="Fatima Khan",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #46",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Fatima", "Hon. Fatima Khan"]
    ),
    "PEP-02-0047": PEPProfile(
        pep_id="PEP-02-0047",
        full_name="Gabriel Rahman",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #47",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Gabriel", "Hon. Gabriel Rahman"]
    ),
    "PEP-02-0048": PEPProfile(
        pep_id="PEP-02-0048",
        full_name="Helena Vargas",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #48",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Helena", "Hon. Helena Vargas"]
    ),
    "PEP-02-0049": PEPProfile(
        pep_id="PEP-02-0049",
        full_name="Ibrahim Al-Sayed",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #49",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Ibrahim", "Hon. Ibrahim Al-Sayed"]
    ),
    "PEP-02-0050": PEPProfile(
        pep_id="PEP-02-0050",
        full_name="Julia Mansour",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #50",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Julia", "Hon. Julia Mansour"]
    ),
    "PEP-02-0051": PEPProfile(
        pep_id="PEP-02-0051",
        full_name="Klaus Santos",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #51",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Klaus", "Hon. Klaus Santos"]
    ),
    "PEP-02-0052": PEPProfile(
        pep_id="PEP-02-0052",
        full_name="Lucia Haddad",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #52",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Lucia", "Hon. Lucia Haddad"]
    ),
    "PEP-02-0053": PEPProfile(
        pep_id="PEP-02-0053",
        full_name="Mateo Morales",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #53",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Mateo", "Hon. Mateo Morales"]
    ),
    "PEP-02-0054": PEPProfile(
        pep_id="PEP-02-0054",
        full_name="Nadia Sterling",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #54",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Nadia", "Hon. Nadia Sterling"]
    ),
    "PEP-02-0055": PEPProfile(
        pep_id="PEP-02-0055",
        full_name="Omar Volkov",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #55",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Omar", "Hon. Omar Volkov"]
    ),
    "PEP-02-0056": PEPProfile(
        pep_id="PEP-02-0056",
        full_name="Pradeep Silva",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #56",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Pradeep", "Hon. Pradeep Silva"]
    ),
    "PEP-02-0057": PEPProfile(
        pep_id="PEP-02-0057",
        full_name="Qasim Chen",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #57",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Qasim", "Hon. Qasim Chen"]
    ),
    "PEP-02-0058": PEPProfile(
        pep_id="PEP-02-0058",
        full_name="Rosa Fernandez",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #58",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Rosa", "Hon. Rosa Fernandez"]
    ),
    "PEP-02-0059": PEPProfile(
        pep_id="PEP-02-0059",
        full_name="Siddharth Patel",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #59",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Siddharth", "Hon. Siddharth Patel"]
    ),
    "PEP-02-0060": PEPProfile(
        pep_id="PEP-02-0060",
        full_name="Tariq Reddy",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #60",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Tariq", "Hon. Tariq Reddy"]
    ),
    "PEP-02-0061": PEPProfile(
        pep_id="PEP-02-0061",
        full_name="Arthur Mercer",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #61",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Arthur", "Hon. Arthur Mercer"]
    ),
    "PEP-02-0062": PEPProfile(
        pep_id="PEP-02-0062",
        full_name="Beatrice Schneider",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #62",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Beatrice", "Hon. Beatrice Schneider"]
    ),
    "PEP-02-0063": PEPProfile(
        pep_id="PEP-02-0063",
        full_name="Carlos Lombardi",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #63",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Carlos", "Hon. Carlos Lombardi"]
    ),
    "PEP-02-0064": PEPProfile(
        pep_id="PEP-02-0064",
        full_name="Dmitri Weber",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #64",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Dmitri", "Hon. Dmitri Weber"]
    ),
    "PEP-02-0065": PEPProfile(
        pep_id="PEP-02-0065",
        full_name="Elena Kovacs",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #65",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Elena", "Hon. Elena Kovacs"]
    ),
    "PEP-02-0066": PEPProfile(
        pep_id="PEP-02-0066",
        full_name="Fatima Khan",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #66",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Fatima", "Hon. Fatima Khan"]
    ),
    "PEP-02-0067": PEPProfile(
        pep_id="PEP-02-0067",
        full_name="Gabriel Rahman",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #67",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Gabriel", "Hon. Gabriel Rahman"]
    ),
    "PEP-02-0068": PEPProfile(
        pep_id="PEP-02-0068",
        full_name="Helena Vargas",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #68",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Helena", "Hon. Helena Vargas"]
    ),
    "PEP-02-0069": PEPProfile(
        pep_id="PEP-02-0069",
        full_name="Ibrahim Al-Sayed",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #69",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Ibrahim", "Hon. Ibrahim Al-Sayed"]
    ),
    "PEP-02-0070": PEPProfile(
        pep_id="PEP-02-0070",
        full_name="Julia Mansour",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #70",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Julia", "Hon. Julia Mansour"]
    ),
    "PEP-02-0071": PEPProfile(
        pep_id="PEP-02-0071",
        full_name="Klaus Santos",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #71",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Klaus", "Hon. Klaus Santos"]
    ),
    "PEP-02-0072": PEPProfile(
        pep_id="PEP-02-0072",
        full_name="Lucia Haddad",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #72",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Lucia", "Hon. Lucia Haddad"]
    ),
    "PEP-02-0073": PEPProfile(
        pep_id="PEP-02-0073",
        full_name="Mateo Morales",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #73",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Mateo", "Hon. Mateo Morales"]
    ),
    "PEP-02-0074": PEPProfile(
        pep_id="PEP-02-0074",
        full_name="Nadia Sterling",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #74",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Nadia", "Hon. Nadia Sterling"]
    ),
    "PEP-02-0075": PEPProfile(
        pep_id="PEP-02-0075",
        full_name="Omar Volkov",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #75",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Omar", "Hon. Omar Volkov"]
    ),
    "PEP-02-0076": PEPProfile(
        pep_id="PEP-02-0076",
        full_name="Pradeep Silva",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #76",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Pradeep", "Hon. Pradeep Silva"]
    ),
    "PEP-02-0077": PEPProfile(
        pep_id="PEP-02-0077",
        full_name="Qasim Chen",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #77",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Qasim", "Hon. Qasim Chen"]
    ),
    "PEP-02-0078": PEPProfile(
        pep_id="PEP-02-0078",
        full_name="Rosa Fernandez",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #78",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Rosa", "Hon. Rosa Fernandez"]
    ),
    "PEP-02-0079": PEPProfile(
        pep_id="PEP-02-0079",
        full_name="Siddharth Patel",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #79",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Siddharth", "Hon. Siddharth Patel"]
    ),
    "PEP-02-0080": PEPProfile(
        pep_id="PEP-02-0080",
        full_name="Tariq Reddy",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #80",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Tariq", "Hon. Tariq Reddy"]
    ),
    "PEP-02-0081": PEPProfile(
        pep_id="PEP-02-0081",
        full_name="Arthur Mercer",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #81",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Arthur", "Hon. Arthur Mercer"]
    ),
    "PEP-02-0082": PEPProfile(
        pep_id="PEP-02-0082",
        full_name="Beatrice Schneider",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #82",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Beatrice", "Hon. Beatrice Schneider"]
    ),
    "PEP-02-0083": PEPProfile(
        pep_id="PEP-02-0083",
        full_name="Carlos Lombardi",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #83",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Carlos", "Hon. Carlos Lombardi"]
    ),
    "PEP-02-0084": PEPProfile(
        pep_id="PEP-02-0084",
        full_name="Dmitri Weber",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #84",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Dmitri", "Hon. Dmitri Weber"]
    ),
    "PEP-02-0085": PEPProfile(
        pep_id="PEP-02-0085",
        full_name="Elena Kovacs",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #85",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Elena", "Hon. Elena Kovacs"]
    ),
    "PEP-02-0086": PEPProfile(
        pep_id="PEP-02-0086",
        full_name="Fatima Khan",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #86",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Fatima", "Hon. Fatima Khan"]
    ),
    "PEP-02-0087": PEPProfile(
        pep_id="PEP-02-0087",
        full_name="Gabriel Rahman",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #87",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Gabriel", "Hon. Gabriel Rahman"]
    ),
    "PEP-02-0088": PEPProfile(
        pep_id="PEP-02-0088",
        full_name="Helena Vargas",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #88",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Helena", "Hon. Helena Vargas"]
    ),
    "PEP-02-0089": PEPProfile(
        pep_id="PEP-02-0089",
        full_name="Ibrahim Al-Sayed",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #89",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Ibrahim", "Hon. Ibrahim Al-Sayed"]
    ),
    "PEP-02-0090": PEPProfile(
        pep_id="PEP-02-0090",
        full_name="Julia Mansour",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #90",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Julia", "Hon. Julia Mansour"]
    ),
    "PEP-02-0091": PEPProfile(
        pep_id="PEP-02-0091",
        full_name="Klaus Santos",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #91",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Klaus", "Hon. Klaus Santos"]
    ),
    "PEP-02-0092": PEPProfile(
        pep_id="PEP-02-0092",
        full_name="Lucia Haddad",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #92",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Lucia", "Hon. Lucia Haddad"]
    ),
    "PEP-02-0093": PEPProfile(
        pep_id="PEP-02-0093",
        full_name="Mateo Morales",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #93",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Mateo", "Hon. Mateo Morales"]
    ),
    "PEP-02-0094": PEPProfile(
        pep_id="PEP-02-0094",
        full_name="Nadia Sterling",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #94",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Nadia", "Hon. Nadia Sterling"]
    ),
    "PEP-02-0095": PEPProfile(
        pep_id="PEP-02-0095",
        full_name="Omar Volkov",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #95",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Omar", "Hon. Omar Volkov"]
    ),
    "PEP-02-0096": PEPProfile(
        pep_id="PEP-02-0096",
        full_name="Pradeep Silva",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #96",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Pradeep", "Hon. Pradeep Silva"]
    ),
    "PEP-02-0097": PEPProfile(
        pep_id="PEP-02-0097",
        full_name="Qasim Chen",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #97",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Qasim", "Hon. Qasim Chen"]
    ),
    "PEP-02-0098": PEPProfile(
        pep_id="PEP-02-0098",
        full_name="Rosa Fernandez",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #98",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Rosa", "Hon. Rosa Fernandez"]
    ),
    "PEP-02-0099": PEPProfile(
        pep_id="PEP-02-0099",
        full_name="Siddharth Patel",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #99",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Siddharth", "Hon. Siddharth Patel"]
    ),
    "PEP-02-0100": PEPProfile(
        pep_id="PEP-02-0100",
        full_name="Tariq Reddy",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #100",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Tariq", "Hon. Tariq Reddy"]
    ),
    "PEP-02-0101": PEPProfile(
        pep_id="PEP-02-0101",
        full_name="Arthur Mercer",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #101",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Arthur", "Hon. Arthur Mercer"]
    ),
    "PEP-02-0102": PEPProfile(
        pep_id="PEP-02-0102",
        full_name="Beatrice Schneider",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #102",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Beatrice", "Hon. Beatrice Schneider"]
    ),
    "PEP-02-0103": PEPProfile(
        pep_id="PEP-02-0103",
        full_name="Carlos Lombardi",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #103",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Carlos", "Hon. Carlos Lombardi"]
    ),
    "PEP-02-0104": PEPProfile(
        pep_id="PEP-02-0104",
        full_name="Dmitri Weber",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #104",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Dmitri", "Hon. Dmitri Weber"]
    ),
    "PEP-02-0105": PEPProfile(
        pep_id="PEP-02-0105",
        full_name="Elena Kovacs",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #105",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Elena", "Hon. Elena Kovacs"]
    ),
    "PEP-02-0106": PEPProfile(
        pep_id="PEP-02-0106",
        full_name="Fatima Khan",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #106",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Fatima", "Hon. Fatima Khan"]
    ),
    "PEP-02-0107": PEPProfile(
        pep_id="PEP-02-0107",
        full_name="Gabriel Rahman",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #107",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Gabriel", "Hon. Gabriel Rahman"]
    ),
    "PEP-02-0108": PEPProfile(
        pep_id="PEP-02-0108",
        full_name="Helena Vargas",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #108",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Helena", "Hon. Helena Vargas"]
    ),
    "PEP-02-0109": PEPProfile(
        pep_id="PEP-02-0109",
        full_name="Ibrahim Al-Sayed",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #109",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Ibrahim", "Hon. Ibrahim Al-Sayed"]
    ),
    "PEP-02-0110": PEPProfile(
        pep_id="PEP-02-0110",
        full_name="Julia Mansour",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #110",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Julia", "Hon. Julia Mansour"]
    ),
    "PEP-02-0111": PEPProfile(
        pep_id="PEP-02-0111",
        full_name="Klaus Santos",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #111",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Klaus", "Hon. Klaus Santos"]
    ),
    "PEP-02-0112": PEPProfile(
        pep_id="PEP-02-0112",
        full_name="Lucia Haddad",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #112",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Lucia", "Hon. Lucia Haddad"]
    ),
    "PEP-02-0113": PEPProfile(
        pep_id="PEP-02-0113",
        full_name="Mateo Morales",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #113",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Mateo", "Hon. Mateo Morales"]
    ),
    "PEP-02-0114": PEPProfile(
        pep_id="PEP-02-0114",
        full_name="Nadia Sterling",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #114",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Nadia", "Hon. Nadia Sterling"]
    ),
    "PEP-02-0115": PEPProfile(
        pep_id="PEP-02-0115",
        full_name="Omar Volkov",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #115",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Omar", "Hon. Omar Volkov"]
    ),
    "PEP-02-0116": PEPProfile(
        pep_id="PEP-02-0116",
        full_name="Pradeep Silva",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #116",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Pradeep", "Hon. Pradeep Silva"]
    ),
    "PEP-02-0117": PEPProfile(
        pep_id="PEP-02-0117",
        full_name="Qasim Chen",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #117",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Qasim", "Hon. Qasim Chen"]
    ),
    "PEP-02-0118": PEPProfile(
        pep_id="PEP-02-0118",
        full_name="Rosa Fernandez",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #118",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Rosa", "Hon. Rosa Fernandez"]
    ),
    "PEP-02-0119": PEPProfile(
        pep_id="PEP-02-0119",
        full_name="Siddharth Patel",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #119",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Siddharth", "Hon. Siddharth Patel"]
    ),
    "PEP-02-0120": PEPProfile(
        pep_id="PEP-02-0120",
        full_name="Tariq Reddy",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #120",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Tariq", "Hon. Tariq Reddy"]
    ),
    "PEP-02-0121": PEPProfile(
        pep_id="PEP-02-0121",
        full_name="Arthur Mercer",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #121",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Arthur", "Hon. Arthur Mercer"]
    ),
    "PEP-02-0122": PEPProfile(
        pep_id="PEP-02-0122",
        full_name="Beatrice Schneider",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #122",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Beatrice", "Hon. Beatrice Schneider"]
    ),
    "PEP-02-0123": PEPProfile(
        pep_id="PEP-02-0123",
        full_name="Carlos Lombardi",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #123",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Carlos", "Hon. Carlos Lombardi"]
    ),
    "PEP-02-0124": PEPProfile(
        pep_id="PEP-02-0124",
        full_name="Dmitri Weber",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #124",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Dmitri", "Hon. Dmitri Weber"]
    ),
    "PEP-02-0125": PEPProfile(
        pep_id="PEP-02-0125",
        full_name="Elena Kovacs",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #125",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Elena", "Hon. Elena Kovacs"]
    ),
    "PEP-02-0126": PEPProfile(
        pep_id="PEP-02-0126",
        full_name="Fatima Khan",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #126",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Fatima", "Hon. Fatima Khan"]
    ),
    "PEP-02-0127": PEPProfile(
        pep_id="PEP-02-0127",
        full_name="Gabriel Rahman",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #127",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Gabriel", "Hon. Gabriel Rahman"]
    ),
    "PEP-02-0128": PEPProfile(
        pep_id="PEP-02-0128",
        full_name="Helena Vargas",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #128",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Helena", "Hon. Helena Vargas"]
    ),
    "PEP-02-0129": PEPProfile(
        pep_id="PEP-02-0129",
        full_name="Ibrahim Al-Sayed",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #129",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Ibrahim", "Hon. Ibrahim Al-Sayed"]
    ),
    "PEP-02-0130": PEPProfile(
        pep_id="PEP-02-0130",
        full_name="Julia Mansour",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #130",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Julia", "Hon. Julia Mansour"]
    ),
    "PEP-02-0131": PEPProfile(
        pep_id="PEP-02-0131",
        full_name="Klaus Santos",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #131",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Klaus", "Hon. Klaus Santos"]
    ),
    "PEP-02-0132": PEPProfile(
        pep_id="PEP-02-0132",
        full_name="Lucia Haddad",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #132",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Lucia", "Hon. Lucia Haddad"]
    ),
    "PEP-02-0133": PEPProfile(
        pep_id="PEP-02-0133",
        full_name="Mateo Morales",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #133",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Mateo", "Hon. Mateo Morales"]
    ),
    "PEP-02-0134": PEPProfile(
        pep_id="PEP-02-0134",
        full_name="Nadia Sterling",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #134",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Nadia", "Hon. Nadia Sterling"]
    ),
    "PEP-02-0135": PEPProfile(
        pep_id="PEP-02-0135",
        full_name="Omar Volkov",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #135",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Omar", "Hon. Omar Volkov"]
    ),
    "PEP-02-0136": PEPProfile(
        pep_id="PEP-02-0136",
        full_name="Pradeep Silva",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #136",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Pradeep", "Hon. Pradeep Silva"]
    ),
    "PEP-02-0137": PEPProfile(
        pep_id="PEP-02-0137",
        full_name="Qasim Chen",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #137",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Qasim", "Hon. Qasim Chen"]
    ),
    "PEP-02-0138": PEPProfile(
        pep_id="PEP-02-0138",
        full_name="Rosa Fernandez",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #138",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Rosa", "Hon. Rosa Fernandez"]
    ),
    "PEP-02-0139": PEPProfile(
        pep_id="PEP-02-0139",
        full_name="Siddharth Patel",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #139",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Siddharth", "Hon. Siddharth Patel"]
    ),
    "PEP-02-0140": PEPProfile(
        pep_id="PEP-02-0140",
        full_name="Tariq Reddy",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #140",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Tariq", "Hon. Tariq Reddy"]
    ),
    "PEP-02-0141": PEPProfile(
        pep_id="PEP-02-0141",
        full_name="Arthur Mercer",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #141",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Arthur", "Hon. Arthur Mercer"]
    ),
    "PEP-02-0142": PEPProfile(
        pep_id="PEP-02-0142",
        full_name="Beatrice Schneider",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #142",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Beatrice", "Hon. Beatrice Schneider"]
    ),
    "PEP-02-0143": PEPProfile(
        pep_id="PEP-02-0143",
        full_name="Carlos Lombardi",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #143",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Carlos", "Hon. Carlos Lombardi"]
    ),
    "PEP-02-0144": PEPProfile(
        pep_id="PEP-02-0144",
        full_name="Dmitri Weber",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #144",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Dmitri", "Hon. Dmitri Weber"]
    ),
    "PEP-02-0145": PEPProfile(
        pep_id="PEP-02-0145",
        full_name="Elena Kovacs",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #145",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Elena", "Hon. Elena Kovacs"]
    ),
    "PEP-02-0146": PEPProfile(
        pep_id="PEP-02-0146",
        full_name="Fatima Khan",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #146",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Fatima", "Hon. Fatima Khan"]
    ),
    "PEP-02-0147": PEPProfile(
        pep_id="PEP-02-0147",
        full_name="Gabriel Rahman",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #147",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Gabriel", "Hon. Gabriel Rahman"]
    ),
    "PEP-02-0148": PEPProfile(
        pep_id="PEP-02-0148",
        full_name="Helena Vargas",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #148",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Helena", "Hon. Helena Vargas"]
    ),
    "PEP-02-0149": PEPProfile(
        pep_id="PEP-02-0149",
        full_name="Ibrahim Al-Sayed",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #149",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Ibrahim", "Hon. Ibrahim Al-Sayed"]
    ),
    "PEP-02-0150": PEPProfile(
        pep_id="PEP-02-0150",
        full_name="Julia Mansour",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #150",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Julia", "Hon. Julia Mansour"]
    ),
    "PEP-02-0151": PEPProfile(
        pep_id="PEP-02-0151",
        full_name="Klaus Santos",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #151",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Klaus", "Hon. Klaus Santos"]
    ),
    "PEP-02-0152": PEPProfile(
        pep_id="PEP-02-0152",
        full_name="Lucia Haddad",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #152",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Lucia", "Hon. Lucia Haddad"]
    ),
    "PEP-02-0153": PEPProfile(
        pep_id="PEP-02-0153",
        full_name="Mateo Morales",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #153",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Mateo", "Hon. Mateo Morales"]
    ),
    "PEP-02-0154": PEPProfile(
        pep_id="PEP-02-0154",
        full_name="Nadia Sterling",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #154",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Nadia", "Hon. Nadia Sterling"]
    ),
    "PEP-02-0155": PEPProfile(
        pep_id="PEP-02-0155",
        full_name="Omar Volkov",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #155",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Omar", "Hon. Omar Volkov"]
    ),
    "PEP-02-0156": PEPProfile(
        pep_id="PEP-02-0156",
        full_name="Pradeep Silva",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #156",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Pradeep", "Hon. Pradeep Silva"]
    ),
    "PEP-02-0157": PEPProfile(
        pep_id="PEP-02-0157",
        full_name="Qasim Chen",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #157",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Qasim", "Hon. Qasim Chen"]
    ),
    "PEP-02-0158": PEPProfile(
        pep_id="PEP-02-0158",
        full_name="Rosa Fernandez",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #158",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Rosa", "Hon. Rosa Fernandez"]
    ),
    "PEP-02-0159": PEPProfile(
        pep_id="PEP-02-0159",
        full_name="Siddharth Patel",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #159",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Siddharth", "Hon. Siddharth Patel"]
    ),
    "PEP-02-0160": PEPProfile(
        pep_id="PEP-02-0160",
        full_name="Tariq Reddy",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #160",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Tariq", "Hon. Tariq Reddy"]
    ),
    "PEP-02-0161": PEPProfile(
        pep_id="PEP-02-0161",
        full_name="Arthur Mercer",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #161",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Arthur", "Hon. Arthur Mercer"]
    ),
    "PEP-02-0162": PEPProfile(
        pep_id="PEP-02-0162",
        full_name="Beatrice Schneider",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #162",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Beatrice", "Hon. Beatrice Schneider"]
    ),
    "PEP-02-0163": PEPProfile(
        pep_id="PEP-02-0163",
        full_name="Carlos Lombardi",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #163",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Carlos", "Hon. Carlos Lombardi"]
    ),
    "PEP-02-0164": PEPProfile(
        pep_id="PEP-02-0164",
        full_name="Dmitri Weber",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #164",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Dmitri", "Hon. Dmitri Weber"]
    ),
    "PEP-02-0165": PEPProfile(
        pep_id="PEP-02-0165",
        full_name="Elena Kovacs",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #165",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Elena", "Hon. Elena Kovacs"]
    ),
    "PEP-02-0166": PEPProfile(
        pep_id="PEP-02-0166",
        full_name="Fatima Khan",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #166",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Fatima", "Hon. Fatima Khan"]
    ),
    "PEP-02-0167": PEPProfile(
        pep_id="PEP-02-0167",
        full_name="Gabriel Rahman",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #167",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Gabriel", "Hon. Gabriel Rahman"]
    ),
    "PEP-02-0168": PEPProfile(
        pep_id="PEP-02-0168",
        full_name="Helena Vargas",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #168",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Helena", "Hon. Helena Vargas"]
    ),
    "PEP-02-0169": PEPProfile(
        pep_id="PEP-02-0169",
        full_name="Ibrahim Al-Sayed",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #169",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Ibrahim", "Hon. Ibrahim Al-Sayed"]
    ),
    "PEP-02-0170": PEPProfile(
        pep_id="PEP-02-0170",
        full_name="Julia Mansour",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #170",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Julia", "Hon. Julia Mansour"]
    ),
    "PEP-02-0171": PEPProfile(
        pep_id="PEP-02-0171",
        full_name="Klaus Santos",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #171",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Klaus", "Hon. Klaus Santos"]
    ),
    "PEP-02-0172": PEPProfile(
        pep_id="PEP-02-0172",
        full_name="Lucia Haddad",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #172",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Lucia", "Hon. Lucia Haddad"]
    ),
    "PEP-02-0173": PEPProfile(
        pep_id="PEP-02-0173",
        full_name="Mateo Morales",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #173",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Mateo", "Hon. Mateo Morales"]
    ),
    "PEP-02-0174": PEPProfile(
        pep_id="PEP-02-0174",
        full_name="Nadia Sterling",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #174",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Nadia", "Hon. Nadia Sterling"]
    ),
    "PEP-02-0175": PEPProfile(
        pep_id="PEP-02-0175",
        full_name="Omar Volkov",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #175",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Omar", "Hon. Omar Volkov"]
    ),
    "PEP-02-0176": PEPProfile(
        pep_id="PEP-02-0176",
        full_name="Pradeep Silva",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #176",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Pradeep", "Hon. Pradeep Silva"]
    ),
    "PEP-02-0177": PEPProfile(
        pep_id="PEP-02-0177",
        full_name="Qasim Chen",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #177",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Qasim", "Hon. Qasim Chen"]
    ),
    "PEP-02-0178": PEPProfile(
        pep_id="PEP-02-0178",
        full_name="Rosa Fernandez",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #178",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Rosa", "Hon. Rosa Fernandez"]
    ),
    "PEP-02-0179": PEPProfile(
        pep_id="PEP-02-0179",
        full_name="Siddharth Patel",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #179",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Siddharth", "Hon. Siddharth Patel"]
    ),
    "PEP-02-0180": PEPProfile(
        pep_id="PEP-02-0180",
        full_name="Tariq Reddy",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Finance & Treasury Ministers Official #180",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Tariq", "Hon. Tariq Reddy"]
    ),
}
