"""
Tier 2 Supreme Court & Constitutional Justices.
Judicial High Officers.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional

@dataclass
class PEPProfile:
    pep_id: str
    full_name: str
    country_code: str
    country_name: str
    tier: int
    role_title: str
    department_or_agency: str
    is_active: bool = True
    risk_score: float = 8.5
    source_of_wealth: Optional[str] = None
    aliases: List[str] = field(default_factory=list)

PEP_RECORDS_TIER2_SUPREME_JUDGES: Dict[str, PEPProfile] = {
    "PEP-06-0001": PEPProfile(
        pep_id="PEP-06-0001",
        full_name="Arthur Al-Sayed",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #1",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Arthur", "Hon. Arthur Al-Sayed"]
    ),
    "PEP-06-0002": PEPProfile(
        pep_id="PEP-06-0002",
        full_name="Beatrice Mansour",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #2",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Beatrice", "Hon. Beatrice Mansour"]
    ),
    "PEP-06-0003": PEPProfile(
        pep_id="PEP-06-0003",
        full_name="Carlos Santos",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #3",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Carlos", "Hon. Carlos Santos"]
    ),
    "PEP-06-0004": PEPProfile(
        pep_id="PEP-06-0004",
        full_name="Dmitri Haddad",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #4",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Dmitri", "Hon. Dmitri Haddad"]
    ),
    "PEP-06-0005": PEPProfile(
        pep_id="PEP-06-0005",
        full_name="Elena Morales",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #5",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Elena", "Hon. Elena Morales"]
    ),
    "PEP-06-0006": PEPProfile(
        pep_id="PEP-06-0006",
        full_name="Fatima Sterling",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #6",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Fatima", "Hon. Fatima Sterling"]
    ),
    "PEP-06-0007": PEPProfile(
        pep_id="PEP-06-0007",
        full_name="Gabriel Volkov",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #7",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Gabriel", "Hon. Gabriel Volkov"]
    ),
    "PEP-06-0008": PEPProfile(
        pep_id="PEP-06-0008",
        full_name="Helena Silva",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #8",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Helena", "Hon. Helena Silva"]
    ),
    "PEP-06-0009": PEPProfile(
        pep_id="PEP-06-0009",
        full_name="Ibrahim Chen",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #9",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Ibrahim", "Hon. Ibrahim Chen"]
    ),
    "PEP-06-0010": PEPProfile(
        pep_id="PEP-06-0010",
        full_name="Julia Fernandez",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #10",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Julia", "Hon. Julia Fernandez"]
    ),
    "PEP-06-0011": PEPProfile(
        pep_id="PEP-06-0011",
        full_name="Klaus Patel",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #11",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Klaus", "Hon. Klaus Patel"]
    ),
    "PEP-06-0012": PEPProfile(
        pep_id="PEP-06-0012",
        full_name="Lucia Reddy",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #12",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Lucia", "Hon. Lucia Reddy"]
    ),
    "PEP-06-0013": PEPProfile(
        pep_id="PEP-06-0013",
        full_name="Mateo Mercer",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #13",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Mateo", "Hon. Mateo Mercer"]
    ),
    "PEP-06-0014": PEPProfile(
        pep_id="PEP-06-0014",
        full_name="Nadia Schneider",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #14",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Nadia", "Hon. Nadia Schneider"]
    ),
    "PEP-06-0015": PEPProfile(
        pep_id="PEP-06-0015",
        full_name="Omar Lombardi",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #15",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Omar", "Hon. Omar Lombardi"]
    ),
    "PEP-06-0016": PEPProfile(
        pep_id="PEP-06-0016",
        full_name="Pradeep Weber",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #16",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Pradeep", "Hon. Pradeep Weber"]
    ),
    "PEP-06-0017": PEPProfile(
        pep_id="PEP-06-0017",
        full_name="Qasim Kovacs",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #17",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Qasim", "Hon. Qasim Kovacs"]
    ),
    "PEP-06-0018": PEPProfile(
        pep_id="PEP-06-0018",
        full_name="Rosa Khan",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #18",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Rosa", "Hon. Rosa Khan"]
    ),
    "PEP-06-0019": PEPProfile(
        pep_id="PEP-06-0019",
        full_name="Siddharth Rahman",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #19",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Siddharth", "Hon. Siddharth Rahman"]
    ),
    "PEP-06-0020": PEPProfile(
        pep_id="PEP-06-0020",
        full_name="Tariq Vargas",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #20",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Tariq", "Hon. Tariq Vargas"]
    ),
    "PEP-06-0021": PEPProfile(
        pep_id="PEP-06-0021",
        full_name="Arthur Al-Sayed",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #21",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Arthur", "Hon. Arthur Al-Sayed"]
    ),
    "PEP-06-0022": PEPProfile(
        pep_id="PEP-06-0022",
        full_name="Beatrice Mansour",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #22",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Beatrice", "Hon. Beatrice Mansour"]
    ),
    "PEP-06-0023": PEPProfile(
        pep_id="PEP-06-0023",
        full_name="Carlos Santos",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #23",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Carlos", "Hon. Carlos Santos"]
    ),
    "PEP-06-0024": PEPProfile(
        pep_id="PEP-06-0024",
        full_name="Dmitri Haddad",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #24",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Dmitri", "Hon. Dmitri Haddad"]
    ),
    "PEP-06-0025": PEPProfile(
        pep_id="PEP-06-0025",
        full_name="Elena Morales",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #25",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Elena", "Hon. Elena Morales"]
    ),
    "PEP-06-0026": PEPProfile(
        pep_id="PEP-06-0026",
        full_name="Fatima Sterling",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #26",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Fatima", "Hon. Fatima Sterling"]
    ),
    "PEP-06-0027": PEPProfile(
        pep_id="PEP-06-0027",
        full_name="Gabriel Volkov",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #27",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Gabriel", "Hon. Gabriel Volkov"]
    ),
    "PEP-06-0028": PEPProfile(
        pep_id="PEP-06-0028",
        full_name="Helena Silva",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #28",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Helena", "Hon. Helena Silva"]
    ),
    "PEP-06-0029": PEPProfile(
        pep_id="PEP-06-0029",
        full_name="Ibrahim Chen",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #29",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Ibrahim", "Hon. Ibrahim Chen"]
    ),
    "PEP-06-0030": PEPProfile(
        pep_id="PEP-06-0030",
        full_name="Julia Fernandez",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #30",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Julia", "Hon. Julia Fernandez"]
    ),
    "PEP-06-0031": PEPProfile(
        pep_id="PEP-06-0031",
        full_name="Klaus Patel",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #31",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Klaus", "Hon. Klaus Patel"]
    ),
    "PEP-06-0032": PEPProfile(
        pep_id="PEP-06-0032",
        full_name="Lucia Reddy",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #32",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Lucia", "Hon. Lucia Reddy"]
    ),
    "PEP-06-0033": PEPProfile(
        pep_id="PEP-06-0033",
        full_name="Mateo Mercer",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #33",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Mateo", "Hon. Mateo Mercer"]
    ),
    "PEP-06-0034": PEPProfile(
        pep_id="PEP-06-0034",
        full_name="Nadia Schneider",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #34",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Nadia", "Hon. Nadia Schneider"]
    ),
    "PEP-06-0035": PEPProfile(
        pep_id="PEP-06-0035",
        full_name="Omar Lombardi",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #35",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Omar", "Hon. Omar Lombardi"]
    ),
    "PEP-06-0036": PEPProfile(
        pep_id="PEP-06-0036",
        full_name="Pradeep Weber",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #36",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Pradeep", "Hon. Pradeep Weber"]
    ),
    "PEP-06-0037": PEPProfile(
        pep_id="PEP-06-0037",
        full_name="Qasim Kovacs",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #37",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Qasim", "Hon. Qasim Kovacs"]
    ),
    "PEP-06-0038": PEPProfile(
        pep_id="PEP-06-0038",
        full_name="Rosa Khan",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #38",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Rosa", "Hon. Rosa Khan"]
    ),
    "PEP-06-0039": PEPProfile(
        pep_id="PEP-06-0039",
        full_name="Siddharth Rahman",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #39",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Siddharth", "Hon. Siddharth Rahman"]
    ),
    "PEP-06-0040": PEPProfile(
        pep_id="PEP-06-0040",
        full_name="Tariq Vargas",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #40",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Tariq", "Hon. Tariq Vargas"]
    ),
    "PEP-06-0041": PEPProfile(
        pep_id="PEP-06-0041",
        full_name="Arthur Al-Sayed",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #41",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Arthur", "Hon. Arthur Al-Sayed"]
    ),
    "PEP-06-0042": PEPProfile(
        pep_id="PEP-06-0042",
        full_name="Beatrice Mansour",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #42",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Beatrice", "Hon. Beatrice Mansour"]
    ),
    "PEP-06-0043": PEPProfile(
        pep_id="PEP-06-0043",
        full_name="Carlos Santos",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #43",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Carlos", "Hon. Carlos Santos"]
    ),
    "PEP-06-0044": PEPProfile(
        pep_id="PEP-06-0044",
        full_name="Dmitri Haddad",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #44",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Dmitri", "Hon. Dmitri Haddad"]
    ),
    "PEP-06-0045": PEPProfile(
        pep_id="PEP-06-0045",
        full_name="Elena Morales",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #45",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Elena", "Hon. Elena Morales"]
    ),
    "PEP-06-0046": PEPProfile(
        pep_id="PEP-06-0046",
        full_name="Fatima Sterling",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #46",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Fatima", "Hon. Fatima Sterling"]
    ),
    "PEP-06-0047": PEPProfile(
        pep_id="PEP-06-0047",
        full_name="Gabriel Volkov",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #47",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Gabriel", "Hon. Gabriel Volkov"]
    ),
    "PEP-06-0048": PEPProfile(
        pep_id="PEP-06-0048",
        full_name="Helena Silva",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #48",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Helena", "Hon. Helena Silva"]
    ),
    "PEP-06-0049": PEPProfile(
        pep_id="PEP-06-0049",
        full_name="Ibrahim Chen",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #49",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Ibrahim", "Hon. Ibrahim Chen"]
    ),
    "PEP-06-0050": PEPProfile(
        pep_id="PEP-06-0050",
        full_name="Julia Fernandez",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #50",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Julia", "Hon. Julia Fernandez"]
    ),
    "PEP-06-0051": PEPProfile(
        pep_id="PEP-06-0051",
        full_name="Klaus Patel",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #51",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Klaus", "Hon. Klaus Patel"]
    ),
    "PEP-06-0052": PEPProfile(
        pep_id="PEP-06-0052",
        full_name="Lucia Reddy",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #52",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Lucia", "Hon. Lucia Reddy"]
    ),
    "PEP-06-0053": PEPProfile(
        pep_id="PEP-06-0053",
        full_name="Mateo Mercer",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #53",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Mateo", "Hon. Mateo Mercer"]
    ),
    "PEP-06-0054": PEPProfile(
        pep_id="PEP-06-0054",
        full_name="Nadia Schneider",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #54",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Nadia", "Hon. Nadia Schneider"]
    ),
    "PEP-06-0055": PEPProfile(
        pep_id="PEP-06-0055",
        full_name="Omar Lombardi",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #55",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Omar", "Hon. Omar Lombardi"]
    ),
    "PEP-06-0056": PEPProfile(
        pep_id="PEP-06-0056",
        full_name="Pradeep Weber",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #56",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Pradeep", "Hon. Pradeep Weber"]
    ),
    "PEP-06-0057": PEPProfile(
        pep_id="PEP-06-0057",
        full_name="Qasim Kovacs",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #57",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Qasim", "Hon. Qasim Kovacs"]
    ),
    "PEP-06-0058": PEPProfile(
        pep_id="PEP-06-0058",
        full_name="Rosa Khan",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #58",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Rosa", "Hon. Rosa Khan"]
    ),
    "PEP-06-0059": PEPProfile(
        pep_id="PEP-06-0059",
        full_name="Siddharth Rahman",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #59",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Siddharth", "Hon. Siddharth Rahman"]
    ),
    "PEP-06-0060": PEPProfile(
        pep_id="PEP-06-0060",
        full_name="Tariq Vargas",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #60",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Tariq", "Hon. Tariq Vargas"]
    ),
    "PEP-06-0061": PEPProfile(
        pep_id="PEP-06-0061",
        full_name="Arthur Al-Sayed",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #61",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Arthur", "Hon. Arthur Al-Sayed"]
    ),
    "PEP-06-0062": PEPProfile(
        pep_id="PEP-06-0062",
        full_name="Beatrice Mansour",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #62",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Beatrice", "Hon. Beatrice Mansour"]
    ),
    "PEP-06-0063": PEPProfile(
        pep_id="PEP-06-0063",
        full_name="Carlos Santos",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #63",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Carlos", "Hon. Carlos Santos"]
    ),
    "PEP-06-0064": PEPProfile(
        pep_id="PEP-06-0064",
        full_name="Dmitri Haddad",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #64",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Dmitri", "Hon. Dmitri Haddad"]
    ),
    "PEP-06-0065": PEPProfile(
        pep_id="PEP-06-0065",
        full_name="Elena Morales",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #65",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Elena", "Hon. Elena Morales"]
    ),
    "PEP-06-0066": PEPProfile(
        pep_id="PEP-06-0066",
        full_name="Fatima Sterling",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #66",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Fatima", "Hon. Fatima Sterling"]
    ),
    "PEP-06-0067": PEPProfile(
        pep_id="PEP-06-0067",
        full_name="Gabriel Volkov",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #67",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Gabriel", "Hon. Gabriel Volkov"]
    ),
    "PEP-06-0068": PEPProfile(
        pep_id="PEP-06-0068",
        full_name="Helena Silva",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #68",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Helena", "Hon. Helena Silva"]
    ),
    "PEP-06-0069": PEPProfile(
        pep_id="PEP-06-0069",
        full_name="Ibrahim Chen",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #69",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Ibrahim", "Hon. Ibrahim Chen"]
    ),
    "PEP-06-0070": PEPProfile(
        pep_id="PEP-06-0070",
        full_name="Julia Fernandez",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #70",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Julia", "Hon. Julia Fernandez"]
    ),
    "PEP-06-0071": PEPProfile(
        pep_id="PEP-06-0071",
        full_name="Klaus Patel",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #71",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Klaus", "Hon. Klaus Patel"]
    ),
    "PEP-06-0072": PEPProfile(
        pep_id="PEP-06-0072",
        full_name="Lucia Reddy",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #72",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Lucia", "Hon. Lucia Reddy"]
    ),
    "PEP-06-0073": PEPProfile(
        pep_id="PEP-06-0073",
        full_name="Mateo Mercer",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #73",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Mateo", "Hon. Mateo Mercer"]
    ),
    "PEP-06-0074": PEPProfile(
        pep_id="PEP-06-0074",
        full_name="Nadia Schneider",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #74",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Nadia", "Hon. Nadia Schneider"]
    ),
    "PEP-06-0075": PEPProfile(
        pep_id="PEP-06-0075",
        full_name="Omar Lombardi",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #75",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Omar", "Hon. Omar Lombardi"]
    ),
    "PEP-06-0076": PEPProfile(
        pep_id="PEP-06-0076",
        full_name="Pradeep Weber",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #76",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Pradeep", "Hon. Pradeep Weber"]
    ),
    "PEP-06-0077": PEPProfile(
        pep_id="PEP-06-0077",
        full_name="Qasim Kovacs",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #77",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Qasim", "Hon. Qasim Kovacs"]
    ),
    "PEP-06-0078": PEPProfile(
        pep_id="PEP-06-0078",
        full_name="Rosa Khan",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #78",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Rosa", "Hon. Rosa Khan"]
    ),
    "PEP-06-0079": PEPProfile(
        pep_id="PEP-06-0079",
        full_name="Siddharth Rahman",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #79",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Siddharth", "Hon. Siddharth Rahman"]
    ),
    "PEP-06-0080": PEPProfile(
        pep_id="PEP-06-0080",
        full_name="Tariq Vargas",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #80",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Tariq", "Hon. Tariq Vargas"]
    ),
    "PEP-06-0081": PEPProfile(
        pep_id="PEP-06-0081",
        full_name="Arthur Al-Sayed",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #81",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Arthur", "Hon. Arthur Al-Sayed"]
    ),
    "PEP-06-0082": PEPProfile(
        pep_id="PEP-06-0082",
        full_name="Beatrice Mansour",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #82",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Beatrice", "Hon. Beatrice Mansour"]
    ),
    "PEP-06-0083": PEPProfile(
        pep_id="PEP-06-0083",
        full_name="Carlos Santos",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #83",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Carlos", "Hon. Carlos Santos"]
    ),
    "PEP-06-0084": PEPProfile(
        pep_id="PEP-06-0084",
        full_name="Dmitri Haddad",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #84",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Dmitri", "Hon. Dmitri Haddad"]
    ),
    "PEP-06-0085": PEPProfile(
        pep_id="PEP-06-0085",
        full_name="Elena Morales",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #85",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Elena", "Hon. Elena Morales"]
    ),
    "PEP-06-0086": PEPProfile(
        pep_id="PEP-06-0086",
        full_name="Fatima Sterling",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #86",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Fatima", "Hon. Fatima Sterling"]
    ),
    "PEP-06-0087": PEPProfile(
        pep_id="PEP-06-0087",
        full_name="Gabriel Volkov",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #87",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Gabriel", "Hon. Gabriel Volkov"]
    ),
    "PEP-06-0088": PEPProfile(
        pep_id="PEP-06-0088",
        full_name="Helena Silva",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #88",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Helena", "Hon. Helena Silva"]
    ),
    "PEP-06-0089": PEPProfile(
        pep_id="PEP-06-0089",
        full_name="Ibrahim Chen",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #89",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Ibrahim", "Hon. Ibrahim Chen"]
    ),
    "PEP-06-0090": PEPProfile(
        pep_id="PEP-06-0090",
        full_name="Julia Fernandez",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #90",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Julia", "Hon. Julia Fernandez"]
    ),
    "PEP-06-0091": PEPProfile(
        pep_id="PEP-06-0091",
        full_name="Klaus Patel",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #91",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Klaus", "Hon. Klaus Patel"]
    ),
    "PEP-06-0092": PEPProfile(
        pep_id="PEP-06-0092",
        full_name="Lucia Reddy",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #92",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Lucia", "Hon. Lucia Reddy"]
    ),
    "PEP-06-0093": PEPProfile(
        pep_id="PEP-06-0093",
        full_name="Mateo Mercer",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #93",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Mateo", "Hon. Mateo Mercer"]
    ),
    "PEP-06-0094": PEPProfile(
        pep_id="PEP-06-0094",
        full_name="Nadia Schneider",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #94",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Nadia", "Hon. Nadia Schneider"]
    ),
    "PEP-06-0095": PEPProfile(
        pep_id="PEP-06-0095",
        full_name="Omar Lombardi",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #95",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Omar", "Hon. Omar Lombardi"]
    ),
    "PEP-06-0096": PEPProfile(
        pep_id="PEP-06-0096",
        full_name="Pradeep Weber",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #96",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Pradeep", "Hon. Pradeep Weber"]
    ),
    "PEP-06-0097": PEPProfile(
        pep_id="PEP-06-0097",
        full_name="Qasim Kovacs",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #97",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Qasim", "Hon. Qasim Kovacs"]
    ),
    "PEP-06-0098": PEPProfile(
        pep_id="PEP-06-0098",
        full_name="Rosa Khan",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #98",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Rosa", "Hon. Rosa Khan"]
    ),
    "PEP-06-0099": PEPProfile(
        pep_id="PEP-06-0099",
        full_name="Siddharth Rahman",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #99",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Siddharth", "Hon. Siddharth Rahman"]
    ),
    "PEP-06-0100": PEPProfile(
        pep_id="PEP-06-0100",
        full_name="Tariq Vargas",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #100",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Tariq", "Hon. Tariq Vargas"]
    ),
    "PEP-06-0101": PEPProfile(
        pep_id="PEP-06-0101",
        full_name="Arthur Al-Sayed",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #101",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Arthur", "Hon. Arthur Al-Sayed"]
    ),
    "PEP-06-0102": PEPProfile(
        pep_id="PEP-06-0102",
        full_name="Beatrice Mansour",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #102",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Beatrice", "Hon. Beatrice Mansour"]
    ),
    "PEP-06-0103": PEPProfile(
        pep_id="PEP-06-0103",
        full_name="Carlos Santos",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #103",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Carlos", "Hon. Carlos Santos"]
    ),
    "PEP-06-0104": PEPProfile(
        pep_id="PEP-06-0104",
        full_name="Dmitri Haddad",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #104",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Dmitri", "Hon. Dmitri Haddad"]
    ),
    "PEP-06-0105": PEPProfile(
        pep_id="PEP-06-0105",
        full_name="Elena Morales",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #105",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Elena", "Hon. Elena Morales"]
    ),
    "PEP-06-0106": PEPProfile(
        pep_id="PEP-06-0106",
        full_name="Fatima Sterling",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #106",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Fatima", "Hon. Fatima Sterling"]
    ),
    "PEP-06-0107": PEPProfile(
        pep_id="PEP-06-0107",
        full_name="Gabriel Volkov",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #107",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Gabriel", "Hon. Gabriel Volkov"]
    ),
    "PEP-06-0108": PEPProfile(
        pep_id="PEP-06-0108",
        full_name="Helena Silva",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #108",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Helena", "Hon. Helena Silva"]
    ),
    "PEP-06-0109": PEPProfile(
        pep_id="PEP-06-0109",
        full_name="Ibrahim Chen",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #109",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Ibrahim", "Hon. Ibrahim Chen"]
    ),
    "PEP-06-0110": PEPProfile(
        pep_id="PEP-06-0110",
        full_name="Julia Fernandez",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #110",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Julia", "Hon. Julia Fernandez"]
    ),
    "PEP-06-0111": PEPProfile(
        pep_id="PEP-06-0111",
        full_name="Klaus Patel",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #111",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Klaus", "Hon. Klaus Patel"]
    ),
    "PEP-06-0112": PEPProfile(
        pep_id="PEP-06-0112",
        full_name="Lucia Reddy",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #112",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Lucia", "Hon. Lucia Reddy"]
    ),
    "PEP-06-0113": PEPProfile(
        pep_id="PEP-06-0113",
        full_name="Mateo Mercer",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #113",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Mateo", "Hon. Mateo Mercer"]
    ),
    "PEP-06-0114": PEPProfile(
        pep_id="PEP-06-0114",
        full_name="Nadia Schneider",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #114",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Nadia", "Hon. Nadia Schneider"]
    ),
    "PEP-06-0115": PEPProfile(
        pep_id="PEP-06-0115",
        full_name="Omar Lombardi",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #115",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Omar", "Hon. Omar Lombardi"]
    ),
    "PEP-06-0116": PEPProfile(
        pep_id="PEP-06-0116",
        full_name="Pradeep Weber",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #116",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Pradeep", "Hon. Pradeep Weber"]
    ),
    "PEP-06-0117": PEPProfile(
        pep_id="PEP-06-0117",
        full_name="Qasim Kovacs",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #117",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Qasim", "Hon. Qasim Kovacs"]
    ),
    "PEP-06-0118": PEPProfile(
        pep_id="PEP-06-0118",
        full_name="Rosa Khan",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #118",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Rosa", "Hon. Rosa Khan"]
    ),
    "PEP-06-0119": PEPProfile(
        pep_id="PEP-06-0119",
        full_name="Siddharth Rahman",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #119",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Siddharth", "Hon. Siddharth Rahman"]
    ),
    "PEP-06-0120": PEPProfile(
        pep_id="PEP-06-0120",
        full_name="Tariq Vargas",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #120",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Tariq", "Hon. Tariq Vargas"]
    ),
    "PEP-06-0121": PEPProfile(
        pep_id="PEP-06-0121",
        full_name="Arthur Al-Sayed",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #121",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Arthur", "Hon. Arthur Al-Sayed"]
    ),
    "PEP-06-0122": PEPProfile(
        pep_id="PEP-06-0122",
        full_name="Beatrice Mansour",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #122",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Beatrice", "Hon. Beatrice Mansour"]
    ),
    "PEP-06-0123": PEPProfile(
        pep_id="PEP-06-0123",
        full_name="Carlos Santos",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #123",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Carlos", "Hon. Carlos Santos"]
    ),
    "PEP-06-0124": PEPProfile(
        pep_id="PEP-06-0124",
        full_name="Dmitri Haddad",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #124",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Dmitri", "Hon. Dmitri Haddad"]
    ),
    "PEP-06-0125": PEPProfile(
        pep_id="PEP-06-0125",
        full_name="Elena Morales",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #125",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Elena", "Hon. Elena Morales"]
    ),
    "PEP-06-0126": PEPProfile(
        pep_id="PEP-06-0126",
        full_name="Fatima Sterling",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #126",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Fatima", "Hon. Fatima Sterling"]
    ),
    "PEP-06-0127": PEPProfile(
        pep_id="PEP-06-0127",
        full_name="Gabriel Volkov",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #127",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Gabriel", "Hon. Gabriel Volkov"]
    ),
    "PEP-06-0128": PEPProfile(
        pep_id="PEP-06-0128",
        full_name="Helena Silva",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #128",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Helena", "Hon. Helena Silva"]
    ),
    "PEP-06-0129": PEPProfile(
        pep_id="PEP-06-0129",
        full_name="Ibrahim Chen",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #129",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Ibrahim", "Hon. Ibrahim Chen"]
    ),
    "PEP-06-0130": PEPProfile(
        pep_id="PEP-06-0130",
        full_name="Julia Fernandez",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #130",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Julia", "Hon. Julia Fernandez"]
    ),
    "PEP-06-0131": PEPProfile(
        pep_id="PEP-06-0131",
        full_name="Klaus Patel",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #131",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Klaus", "Hon. Klaus Patel"]
    ),
    "PEP-06-0132": PEPProfile(
        pep_id="PEP-06-0132",
        full_name="Lucia Reddy",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #132",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Lucia", "Hon. Lucia Reddy"]
    ),
    "PEP-06-0133": PEPProfile(
        pep_id="PEP-06-0133",
        full_name="Mateo Mercer",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #133",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Mateo", "Hon. Mateo Mercer"]
    ),
    "PEP-06-0134": PEPProfile(
        pep_id="PEP-06-0134",
        full_name="Nadia Schneider",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #134",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Nadia", "Hon. Nadia Schneider"]
    ),
    "PEP-06-0135": PEPProfile(
        pep_id="PEP-06-0135",
        full_name="Omar Lombardi",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #135",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Omar", "Hon. Omar Lombardi"]
    ),
    "PEP-06-0136": PEPProfile(
        pep_id="PEP-06-0136",
        full_name="Pradeep Weber",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #136",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Pradeep", "Hon. Pradeep Weber"]
    ),
    "PEP-06-0137": PEPProfile(
        pep_id="PEP-06-0137",
        full_name="Qasim Kovacs",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #137",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Qasim", "Hon. Qasim Kovacs"]
    ),
    "PEP-06-0138": PEPProfile(
        pep_id="PEP-06-0138",
        full_name="Rosa Khan",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #138",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Rosa", "Hon. Rosa Khan"]
    ),
    "PEP-06-0139": PEPProfile(
        pep_id="PEP-06-0139",
        full_name="Siddharth Rahman",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #139",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Siddharth", "Hon. Siddharth Rahman"]
    ),
    "PEP-06-0140": PEPProfile(
        pep_id="PEP-06-0140",
        full_name="Tariq Vargas",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #140",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Tariq", "Hon. Tariq Vargas"]
    ),
    "PEP-06-0141": PEPProfile(
        pep_id="PEP-06-0141",
        full_name="Arthur Al-Sayed",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #141",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Arthur", "Hon. Arthur Al-Sayed"]
    ),
    "PEP-06-0142": PEPProfile(
        pep_id="PEP-06-0142",
        full_name="Beatrice Mansour",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #142",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Beatrice", "Hon. Beatrice Mansour"]
    ),
    "PEP-06-0143": PEPProfile(
        pep_id="PEP-06-0143",
        full_name="Carlos Santos",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #143",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Carlos", "Hon. Carlos Santos"]
    ),
    "PEP-06-0144": PEPProfile(
        pep_id="PEP-06-0144",
        full_name="Dmitri Haddad",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #144",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Dmitri", "Hon. Dmitri Haddad"]
    ),
    "PEP-06-0145": PEPProfile(
        pep_id="PEP-06-0145",
        full_name="Elena Morales",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #145",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Elena", "Hon. Elena Morales"]
    ),
    "PEP-06-0146": PEPProfile(
        pep_id="PEP-06-0146",
        full_name="Fatima Sterling",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #146",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Fatima", "Hon. Fatima Sterling"]
    ),
    "PEP-06-0147": PEPProfile(
        pep_id="PEP-06-0147",
        full_name="Gabriel Volkov",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #147",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Gabriel", "Hon. Gabriel Volkov"]
    ),
    "PEP-06-0148": PEPProfile(
        pep_id="PEP-06-0148",
        full_name="Helena Silva",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #148",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Helena", "Hon. Helena Silva"]
    ),
    "PEP-06-0149": PEPProfile(
        pep_id="PEP-06-0149",
        full_name="Ibrahim Chen",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #149",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Ibrahim", "Hon. Ibrahim Chen"]
    ),
    "PEP-06-0150": PEPProfile(
        pep_id="PEP-06-0150",
        full_name="Julia Fernandez",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #150",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Julia", "Hon. Julia Fernandez"]
    ),
    "PEP-06-0151": PEPProfile(
        pep_id="PEP-06-0151",
        full_name="Klaus Patel",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #151",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Klaus", "Hon. Klaus Patel"]
    ),
    "PEP-06-0152": PEPProfile(
        pep_id="PEP-06-0152",
        full_name="Lucia Reddy",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #152",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Lucia", "Hon. Lucia Reddy"]
    ),
    "PEP-06-0153": PEPProfile(
        pep_id="PEP-06-0153",
        full_name="Mateo Mercer",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #153",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Mateo", "Hon. Mateo Mercer"]
    ),
    "PEP-06-0154": PEPProfile(
        pep_id="PEP-06-0154",
        full_name="Nadia Schneider",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #154",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Nadia", "Hon. Nadia Schneider"]
    ),
    "PEP-06-0155": PEPProfile(
        pep_id="PEP-06-0155",
        full_name="Omar Lombardi",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #155",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Omar", "Hon. Omar Lombardi"]
    ),
    "PEP-06-0156": PEPProfile(
        pep_id="PEP-06-0156",
        full_name="Pradeep Weber",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #156",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Pradeep", "Hon. Pradeep Weber"]
    ),
    "PEP-06-0157": PEPProfile(
        pep_id="PEP-06-0157",
        full_name="Qasim Kovacs",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #157",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Qasim", "Hon. Qasim Kovacs"]
    ),
    "PEP-06-0158": PEPProfile(
        pep_id="PEP-06-0158",
        full_name="Rosa Khan",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #158",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Rosa", "Hon. Rosa Khan"]
    ),
    "PEP-06-0159": PEPProfile(
        pep_id="PEP-06-0159",
        full_name="Siddharth Rahman",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #159",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Siddharth", "Hon. Siddharth Rahman"]
    ),
    "PEP-06-0160": PEPProfile(
        pep_id="PEP-06-0160",
        full_name="Tariq Vargas",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #160",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Tariq", "Hon. Tariq Vargas"]
    ),
    "PEP-06-0161": PEPProfile(
        pep_id="PEP-06-0161",
        full_name="Arthur Al-Sayed",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #161",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Arthur", "Hon. Arthur Al-Sayed"]
    ),
    "PEP-06-0162": PEPProfile(
        pep_id="PEP-06-0162",
        full_name="Beatrice Mansour",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #162",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Beatrice", "Hon. Beatrice Mansour"]
    ),
    "PEP-06-0163": PEPProfile(
        pep_id="PEP-06-0163",
        full_name="Carlos Santos",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #163",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Carlos", "Hon. Carlos Santos"]
    ),
    "PEP-06-0164": PEPProfile(
        pep_id="PEP-06-0164",
        full_name="Dmitri Haddad",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #164",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Dmitri", "Hon. Dmitri Haddad"]
    ),
    "PEP-06-0165": PEPProfile(
        pep_id="PEP-06-0165",
        full_name="Elena Morales",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #165",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Elena", "Hon. Elena Morales"]
    ),
    "PEP-06-0166": PEPProfile(
        pep_id="PEP-06-0166",
        full_name="Fatima Sterling",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #166",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Fatima", "Hon. Fatima Sterling"]
    ),
    "PEP-06-0167": PEPProfile(
        pep_id="PEP-06-0167",
        full_name="Gabriel Volkov",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #167",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Gabriel", "Hon. Gabriel Volkov"]
    ),
    "PEP-06-0168": PEPProfile(
        pep_id="PEP-06-0168",
        full_name="Helena Silva",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #168",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Helena", "Hon. Helena Silva"]
    ),
    "PEP-06-0169": PEPProfile(
        pep_id="PEP-06-0169",
        full_name="Ibrahim Chen",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #169",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Ibrahim", "Hon. Ibrahim Chen"]
    ),
    "PEP-06-0170": PEPProfile(
        pep_id="PEP-06-0170",
        full_name="Julia Fernandez",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #170",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Julia", "Hon. Julia Fernandez"]
    ),
    "PEP-06-0171": PEPProfile(
        pep_id="PEP-06-0171",
        full_name="Klaus Patel",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #171",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Klaus", "Hon. Klaus Patel"]
    ),
    "PEP-06-0172": PEPProfile(
        pep_id="PEP-06-0172",
        full_name="Lucia Reddy",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #172",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Lucia", "Hon. Lucia Reddy"]
    ),
    "PEP-06-0173": PEPProfile(
        pep_id="PEP-06-0173",
        full_name="Mateo Mercer",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #173",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Mateo", "Hon. Mateo Mercer"]
    ),
    "PEP-06-0174": PEPProfile(
        pep_id="PEP-06-0174",
        full_name="Nadia Schneider",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #174",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Nadia", "Hon. Nadia Schneider"]
    ),
    "PEP-06-0175": PEPProfile(
        pep_id="PEP-06-0175",
        full_name="Omar Lombardi",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #175",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Omar", "Hon. Omar Lombardi"]
    ),
    "PEP-06-0176": PEPProfile(
        pep_id="PEP-06-0176",
        full_name="Pradeep Weber",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #176",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Pradeep", "Hon. Pradeep Weber"]
    ),
    "PEP-06-0177": PEPProfile(
        pep_id="PEP-06-0177",
        full_name="Qasim Kovacs",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #177",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Qasim", "Hon. Qasim Kovacs"]
    ),
    "PEP-06-0178": PEPProfile(
        pep_id="PEP-06-0178",
        full_name="Rosa Khan",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #178",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Rosa", "Hon. Rosa Khan"]
    ),
    "PEP-06-0179": PEPProfile(
        pep_id="PEP-06-0179",
        full_name="Siddharth Rahman",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #179",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Siddharth", "Hon. Siddharth Rahman"]
    ),
    "PEP-06-0180": PEPProfile(
        pep_id="PEP-06-0180",
        full_name="Tariq Vargas",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Supreme Court & Constitutional Justices Official #180",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Tariq", "Hon. Tariq Vargas"]
    ),
}
