"""
Tier 1 Heads of State & Government.
Sovereign Executive Leaders.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional

@dataclass
class PEPProfile:
    pep_id: str
    full_name: str
    country_code: str
    country_name: str
    tier: int
    role_title: str
    department_or_agency: str
    is_active: bool = True
    risk_score: float = 8.5
    source_of_wealth: Optional[str] = None
    aliases: List[str] = field(default_factory=list)

PEP_RECORDS_TIER1_HEADS_OF_STATE: Dict[str, PEPProfile] = {
    "PEP-01-0001": PEPProfile(
        pep_id="PEP-01-0001",
        full_name="Arthur Sterling",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #1",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Arthur", "Hon. Arthur Sterling"]
    ),
    "PEP-01-0002": PEPProfile(
        pep_id="PEP-01-0002",
        full_name="Beatrice Volkov",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #2",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Beatrice", "Hon. Beatrice Volkov"]
    ),
    "PEP-01-0003": PEPProfile(
        pep_id="PEP-01-0003",
        full_name="Carlos Silva",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #3",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Carlos", "Hon. Carlos Silva"]
    ),
    "PEP-01-0004": PEPProfile(
        pep_id="PEP-01-0004",
        full_name="Dmitri Chen",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #4",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Dmitri", "Hon. Dmitri Chen"]
    ),
    "PEP-01-0005": PEPProfile(
        pep_id="PEP-01-0005",
        full_name="Elena Fernandez",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #5",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Elena", "Hon. Elena Fernandez"]
    ),
    "PEP-01-0006": PEPProfile(
        pep_id="PEP-01-0006",
        full_name="Fatima Patel",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #6",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Fatima", "Hon. Fatima Patel"]
    ),
    "PEP-01-0007": PEPProfile(
        pep_id="PEP-01-0007",
        full_name="Gabriel Reddy",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #7",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Gabriel", "Hon. Gabriel Reddy"]
    ),
    "PEP-01-0008": PEPProfile(
        pep_id="PEP-01-0008",
        full_name="Helena Mercer",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #8",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Helena", "Hon. Helena Mercer"]
    ),
    "PEP-01-0009": PEPProfile(
        pep_id="PEP-01-0009",
        full_name="Ibrahim Schneider",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #9",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Ibrahim", "Hon. Ibrahim Schneider"]
    ),
    "PEP-01-0010": PEPProfile(
        pep_id="PEP-01-0010",
        full_name="Julia Lombardi",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #10",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Julia", "Hon. Julia Lombardi"]
    ),
    "PEP-01-0011": PEPProfile(
        pep_id="PEP-01-0011",
        full_name="Klaus Weber",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #11",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Klaus", "Hon. Klaus Weber"]
    ),
    "PEP-01-0012": PEPProfile(
        pep_id="PEP-01-0012",
        full_name="Lucia Kovacs",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #12",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Lucia", "Hon. Lucia Kovacs"]
    ),
    "PEP-01-0013": PEPProfile(
        pep_id="PEP-01-0013",
        full_name="Mateo Khan",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #13",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Mateo", "Hon. Mateo Khan"]
    ),
    "PEP-01-0014": PEPProfile(
        pep_id="PEP-01-0014",
        full_name="Nadia Rahman",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #14",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Nadia", "Hon. Nadia Rahman"]
    ),
    "PEP-01-0015": PEPProfile(
        pep_id="PEP-01-0015",
        full_name="Omar Vargas",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #15",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Omar", "Hon. Omar Vargas"]
    ),
    "PEP-01-0016": PEPProfile(
        pep_id="PEP-01-0016",
        full_name="Pradeep Al-Sayed",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #16",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Pradeep", "Hon. Pradeep Al-Sayed"]
    ),
    "PEP-01-0017": PEPProfile(
        pep_id="PEP-01-0017",
        full_name="Qasim Mansour",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #17",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Qasim", "Hon. Qasim Mansour"]
    ),
    "PEP-01-0018": PEPProfile(
        pep_id="PEP-01-0018",
        full_name="Rosa Santos",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #18",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Rosa", "Hon. Rosa Santos"]
    ),
    "PEP-01-0019": PEPProfile(
        pep_id="PEP-01-0019",
        full_name="Siddharth Haddad",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #19",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Siddharth", "Hon. Siddharth Haddad"]
    ),
    "PEP-01-0020": PEPProfile(
        pep_id="PEP-01-0020",
        full_name="Tariq Morales",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #20",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Tariq", "Hon. Tariq Morales"]
    ),
    "PEP-01-0021": PEPProfile(
        pep_id="PEP-01-0021",
        full_name="Arthur Sterling",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #21",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Arthur", "Hon. Arthur Sterling"]
    ),
    "PEP-01-0022": PEPProfile(
        pep_id="PEP-01-0022",
        full_name="Beatrice Volkov",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #22",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Beatrice", "Hon. Beatrice Volkov"]
    ),
    "PEP-01-0023": PEPProfile(
        pep_id="PEP-01-0023",
        full_name="Carlos Silva",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #23",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Carlos", "Hon. Carlos Silva"]
    ),
    "PEP-01-0024": PEPProfile(
        pep_id="PEP-01-0024",
        full_name="Dmitri Chen",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #24",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Dmitri", "Hon. Dmitri Chen"]
    ),
    "PEP-01-0025": PEPProfile(
        pep_id="PEP-01-0025",
        full_name="Elena Fernandez",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #25",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Elena", "Hon. Elena Fernandez"]
    ),
    "PEP-01-0026": PEPProfile(
        pep_id="PEP-01-0026",
        full_name="Fatima Patel",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #26",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Fatima", "Hon. Fatima Patel"]
    ),
    "PEP-01-0027": PEPProfile(
        pep_id="PEP-01-0027",
        full_name="Gabriel Reddy",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #27",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Gabriel", "Hon. Gabriel Reddy"]
    ),
    "PEP-01-0028": PEPProfile(
        pep_id="PEP-01-0028",
        full_name="Helena Mercer",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #28",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Helena", "Hon. Helena Mercer"]
    ),
    "PEP-01-0029": PEPProfile(
        pep_id="PEP-01-0029",
        full_name="Ibrahim Schneider",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #29",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Ibrahim", "Hon. Ibrahim Schneider"]
    ),
    "PEP-01-0030": PEPProfile(
        pep_id="PEP-01-0030",
        full_name="Julia Lombardi",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #30",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Julia", "Hon. Julia Lombardi"]
    ),
    "PEP-01-0031": PEPProfile(
        pep_id="PEP-01-0031",
        full_name="Klaus Weber",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #31",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Klaus", "Hon. Klaus Weber"]
    ),
    "PEP-01-0032": PEPProfile(
        pep_id="PEP-01-0032",
        full_name="Lucia Kovacs",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #32",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Lucia", "Hon. Lucia Kovacs"]
    ),
    "PEP-01-0033": PEPProfile(
        pep_id="PEP-01-0033",
        full_name="Mateo Khan",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #33",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Mateo", "Hon. Mateo Khan"]
    ),
    "PEP-01-0034": PEPProfile(
        pep_id="PEP-01-0034",
        full_name="Nadia Rahman",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #34",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Nadia", "Hon. Nadia Rahman"]
    ),
    "PEP-01-0035": PEPProfile(
        pep_id="PEP-01-0035",
        full_name="Omar Vargas",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #35",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Omar", "Hon. Omar Vargas"]
    ),
    "PEP-01-0036": PEPProfile(
        pep_id="PEP-01-0036",
        full_name="Pradeep Al-Sayed",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #36",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Pradeep", "Hon. Pradeep Al-Sayed"]
    ),
    "PEP-01-0037": PEPProfile(
        pep_id="PEP-01-0037",
        full_name="Qasim Mansour",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #37",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Qasim", "Hon. Qasim Mansour"]
    ),
    "PEP-01-0038": PEPProfile(
        pep_id="PEP-01-0038",
        full_name="Rosa Santos",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #38",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Rosa", "Hon. Rosa Santos"]
    ),
    "PEP-01-0039": PEPProfile(
        pep_id="PEP-01-0039",
        full_name="Siddharth Haddad",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #39",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Siddharth", "Hon. Siddharth Haddad"]
    ),
    "PEP-01-0040": PEPProfile(
        pep_id="PEP-01-0040",
        full_name="Tariq Morales",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #40",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Tariq", "Hon. Tariq Morales"]
    ),
    "PEP-01-0041": PEPProfile(
        pep_id="PEP-01-0041",
        full_name="Arthur Sterling",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #41",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Arthur", "Hon. Arthur Sterling"]
    ),
    "PEP-01-0042": PEPProfile(
        pep_id="PEP-01-0042",
        full_name="Beatrice Volkov",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #42",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Beatrice", "Hon. Beatrice Volkov"]
    ),
    "PEP-01-0043": PEPProfile(
        pep_id="PEP-01-0043",
        full_name="Carlos Silva",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #43",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Carlos", "Hon. Carlos Silva"]
    ),
    "PEP-01-0044": PEPProfile(
        pep_id="PEP-01-0044",
        full_name="Dmitri Chen",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #44",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Dmitri", "Hon. Dmitri Chen"]
    ),
    "PEP-01-0045": PEPProfile(
        pep_id="PEP-01-0045",
        full_name="Elena Fernandez",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #45",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Elena", "Hon. Elena Fernandez"]
    ),
    "PEP-01-0046": PEPProfile(
        pep_id="PEP-01-0046",
        full_name="Fatima Patel",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #46",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Fatima", "Hon. Fatima Patel"]
    ),
    "PEP-01-0047": PEPProfile(
        pep_id="PEP-01-0047",
        full_name="Gabriel Reddy",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #47",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Gabriel", "Hon. Gabriel Reddy"]
    ),
    "PEP-01-0048": PEPProfile(
        pep_id="PEP-01-0048",
        full_name="Helena Mercer",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #48",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Helena", "Hon. Helena Mercer"]
    ),
    "PEP-01-0049": PEPProfile(
        pep_id="PEP-01-0049",
        full_name="Ibrahim Schneider",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #49",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Ibrahim", "Hon. Ibrahim Schneider"]
    ),
    "PEP-01-0050": PEPProfile(
        pep_id="PEP-01-0050",
        full_name="Julia Lombardi",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #50",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Julia", "Hon. Julia Lombardi"]
    ),
    "PEP-01-0051": PEPProfile(
        pep_id="PEP-01-0051",
        full_name="Klaus Weber",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #51",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Klaus", "Hon. Klaus Weber"]
    ),
    "PEP-01-0052": PEPProfile(
        pep_id="PEP-01-0052",
        full_name="Lucia Kovacs",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #52",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Lucia", "Hon. Lucia Kovacs"]
    ),
    "PEP-01-0053": PEPProfile(
        pep_id="PEP-01-0053",
        full_name="Mateo Khan",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #53",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Mateo", "Hon. Mateo Khan"]
    ),
    "PEP-01-0054": PEPProfile(
        pep_id="PEP-01-0054",
        full_name="Nadia Rahman",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #54",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Nadia", "Hon. Nadia Rahman"]
    ),
    "PEP-01-0055": PEPProfile(
        pep_id="PEP-01-0055",
        full_name="Omar Vargas",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #55",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Omar", "Hon. Omar Vargas"]
    ),
    "PEP-01-0056": PEPProfile(
        pep_id="PEP-01-0056",
        full_name="Pradeep Al-Sayed",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #56",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Pradeep", "Hon. Pradeep Al-Sayed"]
    ),
    "PEP-01-0057": PEPProfile(
        pep_id="PEP-01-0057",
        full_name="Qasim Mansour",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #57",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Qasim", "Hon. Qasim Mansour"]
    ),
    "PEP-01-0058": PEPProfile(
        pep_id="PEP-01-0058",
        full_name="Rosa Santos",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #58",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Rosa", "Hon. Rosa Santos"]
    ),
    "PEP-01-0059": PEPProfile(
        pep_id="PEP-01-0059",
        full_name="Siddharth Haddad",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #59",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Siddharth", "Hon. Siddharth Haddad"]
    ),
    "PEP-01-0060": PEPProfile(
        pep_id="PEP-01-0060",
        full_name="Tariq Morales",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #60",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Tariq", "Hon. Tariq Morales"]
    ),
    "PEP-01-0061": PEPProfile(
        pep_id="PEP-01-0061",
        full_name="Arthur Sterling",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #61",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Arthur", "Hon. Arthur Sterling"]
    ),
    "PEP-01-0062": PEPProfile(
        pep_id="PEP-01-0062",
        full_name="Beatrice Volkov",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #62",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Beatrice", "Hon. Beatrice Volkov"]
    ),
    "PEP-01-0063": PEPProfile(
        pep_id="PEP-01-0063",
        full_name="Carlos Silva",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #63",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Carlos", "Hon. Carlos Silva"]
    ),
    "PEP-01-0064": PEPProfile(
        pep_id="PEP-01-0064",
        full_name="Dmitri Chen",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #64",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Dmitri", "Hon. Dmitri Chen"]
    ),
    "PEP-01-0065": PEPProfile(
        pep_id="PEP-01-0065",
        full_name="Elena Fernandez",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #65",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Elena", "Hon. Elena Fernandez"]
    ),
    "PEP-01-0066": PEPProfile(
        pep_id="PEP-01-0066",
        full_name="Fatima Patel",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #66",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Fatima", "Hon. Fatima Patel"]
    ),
    "PEP-01-0067": PEPProfile(
        pep_id="PEP-01-0067",
        full_name="Gabriel Reddy",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #67",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Gabriel", "Hon. Gabriel Reddy"]
    ),
    "PEP-01-0068": PEPProfile(
        pep_id="PEP-01-0068",
        full_name="Helena Mercer",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #68",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Helena", "Hon. Helena Mercer"]
    ),
    "PEP-01-0069": PEPProfile(
        pep_id="PEP-01-0069",
        full_name="Ibrahim Schneider",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #69",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Ibrahim", "Hon. Ibrahim Schneider"]
    ),
    "PEP-01-0070": PEPProfile(
        pep_id="PEP-01-0070",
        full_name="Julia Lombardi",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #70",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Julia", "Hon. Julia Lombardi"]
    ),
    "PEP-01-0071": PEPProfile(
        pep_id="PEP-01-0071",
        full_name="Klaus Weber",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #71",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Klaus", "Hon. Klaus Weber"]
    ),
    "PEP-01-0072": PEPProfile(
        pep_id="PEP-01-0072",
        full_name="Lucia Kovacs",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #72",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Lucia", "Hon. Lucia Kovacs"]
    ),
    "PEP-01-0073": PEPProfile(
        pep_id="PEP-01-0073",
        full_name="Mateo Khan",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #73",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Mateo", "Hon. Mateo Khan"]
    ),
    "PEP-01-0074": PEPProfile(
        pep_id="PEP-01-0074",
        full_name="Nadia Rahman",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #74",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Nadia", "Hon. Nadia Rahman"]
    ),
    "PEP-01-0075": PEPProfile(
        pep_id="PEP-01-0075",
        full_name="Omar Vargas",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #75",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Omar", "Hon. Omar Vargas"]
    ),
    "PEP-01-0076": PEPProfile(
        pep_id="PEP-01-0076",
        full_name="Pradeep Al-Sayed",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #76",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Pradeep", "Hon. Pradeep Al-Sayed"]
    ),
    "PEP-01-0077": PEPProfile(
        pep_id="PEP-01-0077",
        full_name="Qasim Mansour",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #77",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Qasim", "Hon. Qasim Mansour"]
    ),
    "PEP-01-0078": PEPProfile(
        pep_id="PEP-01-0078",
        full_name="Rosa Santos",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #78",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Rosa", "Hon. Rosa Santos"]
    ),
    "PEP-01-0079": PEPProfile(
        pep_id="PEP-01-0079",
        full_name="Siddharth Haddad",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #79",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Siddharth", "Hon. Siddharth Haddad"]
    ),
    "PEP-01-0080": PEPProfile(
        pep_id="PEP-01-0080",
        full_name="Tariq Morales",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #80",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Tariq", "Hon. Tariq Morales"]
    ),
    "PEP-01-0081": PEPProfile(
        pep_id="PEP-01-0081",
        full_name="Arthur Sterling",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #81",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Arthur", "Hon. Arthur Sterling"]
    ),
    "PEP-01-0082": PEPProfile(
        pep_id="PEP-01-0082",
        full_name="Beatrice Volkov",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #82",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Beatrice", "Hon. Beatrice Volkov"]
    ),
    "PEP-01-0083": PEPProfile(
        pep_id="PEP-01-0083",
        full_name="Carlos Silva",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #83",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Carlos", "Hon. Carlos Silva"]
    ),
    "PEP-01-0084": PEPProfile(
        pep_id="PEP-01-0084",
        full_name="Dmitri Chen",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #84",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Dmitri", "Hon. Dmitri Chen"]
    ),
    "PEP-01-0085": PEPProfile(
        pep_id="PEP-01-0085",
        full_name="Elena Fernandez",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #85",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Elena", "Hon. Elena Fernandez"]
    ),
    "PEP-01-0086": PEPProfile(
        pep_id="PEP-01-0086",
        full_name="Fatima Patel",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #86",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Fatima", "Hon. Fatima Patel"]
    ),
    "PEP-01-0087": PEPProfile(
        pep_id="PEP-01-0087",
        full_name="Gabriel Reddy",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #87",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Gabriel", "Hon. Gabriel Reddy"]
    ),
    "PEP-01-0088": PEPProfile(
        pep_id="PEP-01-0088",
        full_name="Helena Mercer",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #88",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Helena", "Hon. Helena Mercer"]
    ),
    "PEP-01-0089": PEPProfile(
        pep_id="PEP-01-0089",
        full_name="Ibrahim Schneider",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #89",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Ibrahim", "Hon. Ibrahim Schneider"]
    ),
    "PEP-01-0090": PEPProfile(
        pep_id="PEP-01-0090",
        full_name="Julia Lombardi",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #90",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Julia", "Hon. Julia Lombardi"]
    ),
    "PEP-01-0091": PEPProfile(
        pep_id="PEP-01-0091",
        full_name="Klaus Weber",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #91",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Klaus", "Hon. Klaus Weber"]
    ),
    "PEP-01-0092": PEPProfile(
        pep_id="PEP-01-0092",
        full_name="Lucia Kovacs",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #92",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Lucia", "Hon. Lucia Kovacs"]
    ),
    "PEP-01-0093": PEPProfile(
        pep_id="PEP-01-0093",
        full_name="Mateo Khan",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #93",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Mateo", "Hon. Mateo Khan"]
    ),
    "PEP-01-0094": PEPProfile(
        pep_id="PEP-01-0094",
        full_name="Nadia Rahman",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #94",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Nadia", "Hon. Nadia Rahman"]
    ),
    "PEP-01-0095": PEPProfile(
        pep_id="PEP-01-0095",
        full_name="Omar Vargas",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #95",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Omar", "Hon. Omar Vargas"]
    ),
    "PEP-01-0096": PEPProfile(
        pep_id="PEP-01-0096",
        full_name="Pradeep Al-Sayed",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #96",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Pradeep", "Hon. Pradeep Al-Sayed"]
    ),
    "PEP-01-0097": PEPProfile(
        pep_id="PEP-01-0097",
        full_name="Qasim Mansour",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #97",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Qasim", "Hon. Qasim Mansour"]
    ),
    "PEP-01-0098": PEPProfile(
        pep_id="PEP-01-0098",
        full_name="Rosa Santos",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #98",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Rosa", "Hon. Rosa Santos"]
    ),
    "PEP-01-0099": PEPProfile(
        pep_id="PEP-01-0099",
        full_name="Siddharth Haddad",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #99",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Siddharth", "Hon. Siddharth Haddad"]
    ),
    "PEP-01-0100": PEPProfile(
        pep_id="PEP-01-0100",
        full_name="Tariq Morales",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #100",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Tariq", "Hon. Tariq Morales"]
    ),
    "PEP-01-0101": PEPProfile(
        pep_id="PEP-01-0101",
        full_name="Arthur Sterling",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #101",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Arthur", "Hon. Arthur Sterling"]
    ),
    "PEP-01-0102": PEPProfile(
        pep_id="PEP-01-0102",
        full_name="Beatrice Volkov",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #102",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Beatrice", "Hon. Beatrice Volkov"]
    ),
    "PEP-01-0103": PEPProfile(
        pep_id="PEP-01-0103",
        full_name="Carlos Silva",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #103",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Carlos", "Hon. Carlos Silva"]
    ),
    "PEP-01-0104": PEPProfile(
        pep_id="PEP-01-0104",
        full_name="Dmitri Chen",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #104",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Dmitri", "Hon. Dmitri Chen"]
    ),
    "PEP-01-0105": PEPProfile(
        pep_id="PEP-01-0105",
        full_name="Elena Fernandez",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #105",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Elena", "Hon. Elena Fernandez"]
    ),
    "PEP-01-0106": PEPProfile(
        pep_id="PEP-01-0106",
        full_name="Fatima Patel",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #106",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Fatima", "Hon. Fatima Patel"]
    ),
    "PEP-01-0107": PEPProfile(
        pep_id="PEP-01-0107",
        full_name="Gabriel Reddy",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #107",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Gabriel", "Hon. Gabriel Reddy"]
    ),
    "PEP-01-0108": PEPProfile(
        pep_id="PEP-01-0108",
        full_name="Helena Mercer",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #108",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Helena", "Hon. Helena Mercer"]
    ),
    "PEP-01-0109": PEPProfile(
        pep_id="PEP-01-0109",
        full_name="Ibrahim Schneider",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #109",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Ibrahim", "Hon. Ibrahim Schneider"]
    ),
    "PEP-01-0110": PEPProfile(
        pep_id="PEP-01-0110",
        full_name="Julia Lombardi",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #110",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Julia", "Hon. Julia Lombardi"]
    ),
    "PEP-01-0111": PEPProfile(
        pep_id="PEP-01-0111",
        full_name="Klaus Weber",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #111",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Klaus", "Hon. Klaus Weber"]
    ),
    "PEP-01-0112": PEPProfile(
        pep_id="PEP-01-0112",
        full_name="Lucia Kovacs",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #112",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Lucia", "Hon. Lucia Kovacs"]
    ),
    "PEP-01-0113": PEPProfile(
        pep_id="PEP-01-0113",
        full_name="Mateo Khan",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #113",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Mateo", "Hon. Mateo Khan"]
    ),
    "PEP-01-0114": PEPProfile(
        pep_id="PEP-01-0114",
        full_name="Nadia Rahman",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #114",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Nadia", "Hon. Nadia Rahman"]
    ),
    "PEP-01-0115": PEPProfile(
        pep_id="PEP-01-0115",
        full_name="Omar Vargas",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #115",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Omar", "Hon. Omar Vargas"]
    ),
    "PEP-01-0116": PEPProfile(
        pep_id="PEP-01-0116",
        full_name="Pradeep Al-Sayed",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #116",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Pradeep", "Hon. Pradeep Al-Sayed"]
    ),
    "PEP-01-0117": PEPProfile(
        pep_id="PEP-01-0117",
        full_name="Qasim Mansour",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #117",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Qasim", "Hon. Qasim Mansour"]
    ),
    "PEP-01-0118": PEPProfile(
        pep_id="PEP-01-0118",
        full_name="Rosa Santos",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #118",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Rosa", "Hon. Rosa Santos"]
    ),
    "PEP-01-0119": PEPProfile(
        pep_id="PEP-01-0119",
        full_name="Siddharth Haddad",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #119",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Siddharth", "Hon. Siddharth Haddad"]
    ),
    "PEP-01-0120": PEPProfile(
        pep_id="PEP-01-0120",
        full_name="Tariq Morales",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #120",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Tariq", "Hon. Tariq Morales"]
    ),
    "PEP-01-0121": PEPProfile(
        pep_id="PEP-01-0121",
        full_name="Arthur Sterling",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #121",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Arthur", "Hon. Arthur Sterling"]
    ),
    "PEP-01-0122": PEPProfile(
        pep_id="PEP-01-0122",
        full_name="Beatrice Volkov",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #122",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Beatrice", "Hon. Beatrice Volkov"]
    ),
    "PEP-01-0123": PEPProfile(
        pep_id="PEP-01-0123",
        full_name="Carlos Silva",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #123",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Carlos", "Hon. Carlos Silva"]
    ),
    "PEP-01-0124": PEPProfile(
        pep_id="PEP-01-0124",
        full_name="Dmitri Chen",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #124",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Dmitri", "Hon. Dmitri Chen"]
    ),
    "PEP-01-0125": PEPProfile(
        pep_id="PEP-01-0125",
        full_name="Elena Fernandez",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #125",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Elena", "Hon. Elena Fernandez"]
    ),
    "PEP-01-0126": PEPProfile(
        pep_id="PEP-01-0126",
        full_name="Fatima Patel",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #126",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Fatima", "Hon. Fatima Patel"]
    ),
    "PEP-01-0127": PEPProfile(
        pep_id="PEP-01-0127",
        full_name="Gabriel Reddy",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #127",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Gabriel", "Hon. Gabriel Reddy"]
    ),
    "PEP-01-0128": PEPProfile(
        pep_id="PEP-01-0128",
        full_name="Helena Mercer",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #128",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Helena", "Hon. Helena Mercer"]
    ),
    "PEP-01-0129": PEPProfile(
        pep_id="PEP-01-0129",
        full_name="Ibrahim Schneider",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #129",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Ibrahim", "Hon. Ibrahim Schneider"]
    ),
    "PEP-01-0130": PEPProfile(
        pep_id="PEP-01-0130",
        full_name="Julia Lombardi",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #130",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Julia", "Hon. Julia Lombardi"]
    ),
    "PEP-01-0131": PEPProfile(
        pep_id="PEP-01-0131",
        full_name="Klaus Weber",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #131",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Klaus", "Hon. Klaus Weber"]
    ),
    "PEP-01-0132": PEPProfile(
        pep_id="PEP-01-0132",
        full_name="Lucia Kovacs",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #132",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Lucia", "Hon. Lucia Kovacs"]
    ),
    "PEP-01-0133": PEPProfile(
        pep_id="PEP-01-0133",
        full_name="Mateo Khan",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #133",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Mateo", "Hon. Mateo Khan"]
    ),
    "PEP-01-0134": PEPProfile(
        pep_id="PEP-01-0134",
        full_name="Nadia Rahman",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #134",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Nadia", "Hon. Nadia Rahman"]
    ),
    "PEP-01-0135": PEPProfile(
        pep_id="PEP-01-0135",
        full_name="Omar Vargas",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #135",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Omar", "Hon. Omar Vargas"]
    ),
    "PEP-01-0136": PEPProfile(
        pep_id="PEP-01-0136",
        full_name="Pradeep Al-Sayed",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #136",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Pradeep", "Hon. Pradeep Al-Sayed"]
    ),
    "PEP-01-0137": PEPProfile(
        pep_id="PEP-01-0137",
        full_name="Qasim Mansour",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #137",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Qasim", "Hon. Qasim Mansour"]
    ),
    "PEP-01-0138": PEPProfile(
        pep_id="PEP-01-0138",
        full_name="Rosa Santos",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #138",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Rosa", "Hon. Rosa Santos"]
    ),
    "PEP-01-0139": PEPProfile(
        pep_id="PEP-01-0139",
        full_name="Siddharth Haddad",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #139",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Siddharth", "Hon. Siddharth Haddad"]
    ),
    "PEP-01-0140": PEPProfile(
        pep_id="PEP-01-0140",
        full_name="Tariq Morales",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #140",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Tariq", "Hon. Tariq Morales"]
    ),
    "PEP-01-0141": PEPProfile(
        pep_id="PEP-01-0141",
        full_name="Arthur Sterling",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #141",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Arthur", "Hon. Arthur Sterling"]
    ),
    "PEP-01-0142": PEPProfile(
        pep_id="PEP-01-0142",
        full_name="Beatrice Volkov",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #142",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Beatrice", "Hon. Beatrice Volkov"]
    ),
    "PEP-01-0143": PEPProfile(
        pep_id="PEP-01-0143",
        full_name="Carlos Silva",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #143",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Carlos", "Hon. Carlos Silva"]
    ),
    "PEP-01-0144": PEPProfile(
        pep_id="PEP-01-0144",
        full_name="Dmitri Chen",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #144",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Dmitri", "Hon. Dmitri Chen"]
    ),
    "PEP-01-0145": PEPProfile(
        pep_id="PEP-01-0145",
        full_name="Elena Fernandez",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #145",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Elena", "Hon. Elena Fernandez"]
    ),
    "PEP-01-0146": PEPProfile(
        pep_id="PEP-01-0146",
        full_name="Fatima Patel",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #146",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Fatima", "Hon. Fatima Patel"]
    ),
    "PEP-01-0147": PEPProfile(
        pep_id="PEP-01-0147",
        full_name="Gabriel Reddy",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #147",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Gabriel", "Hon. Gabriel Reddy"]
    ),
    "PEP-01-0148": PEPProfile(
        pep_id="PEP-01-0148",
        full_name="Helena Mercer",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #148",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Helena", "Hon. Helena Mercer"]
    ),
    "PEP-01-0149": PEPProfile(
        pep_id="PEP-01-0149",
        full_name="Ibrahim Schneider",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #149",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Ibrahim", "Hon. Ibrahim Schneider"]
    ),
    "PEP-01-0150": PEPProfile(
        pep_id="PEP-01-0150",
        full_name="Julia Lombardi",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #150",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Julia", "Hon. Julia Lombardi"]
    ),
    "PEP-01-0151": PEPProfile(
        pep_id="PEP-01-0151",
        full_name="Klaus Weber",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #151",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Klaus", "Hon. Klaus Weber"]
    ),
    "PEP-01-0152": PEPProfile(
        pep_id="PEP-01-0152",
        full_name="Lucia Kovacs",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #152",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Lucia", "Hon. Lucia Kovacs"]
    ),
    "PEP-01-0153": PEPProfile(
        pep_id="PEP-01-0153",
        full_name="Mateo Khan",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #153",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Mateo", "Hon. Mateo Khan"]
    ),
    "PEP-01-0154": PEPProfile(
        pep_id="PEP-01-0154",
        full_name="Nadia Rahman",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #154",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Nadia", "Hon. Nadia Rahman"]
    ),
    "PEP-01-0155": PEPProfile(
        pep_id="PEP-01-0155",
        full_name="Omar Vargas",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #155",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Omar", "Hon. Omar Vargas"]
    ),
    "PEP-01-0156": PEPProfile(
        pep_id="PEP-01-0156",
        full_name="Pradeep Al-Sayed",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #156",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Pradeep", "Hon. Pradeep Al-Sayed"]
    ),
    "PEP-01-0157": PEPProfile(
        pep_id="PEP-01-0157",
        full_name="Qasim Mansour",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #157",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Qasim", "Hon. Qasim Mansour"]
    ),
    "PEP-01-0158": PEPProfile(
        pep_id="PEP-01-0158",
        full_name="Rosa Santos",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #158",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Rosa", "Hon. Rosa Santos"]
    ),
    "PEP-01-0159": PEPProfile(
        pep_id="PEP-01-0159",
        full_name="Siddharth Haddad",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #159",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Siddharth", "Hon. Siddharth Haddad"]
    ),
    "PEP-01-0160": PEPProfile(
        pep_id="PEP-01-0160",
        full_name="Tariq Morales",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #160",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Tariq", "Hon. Tariq Morales"]
    ),
    "PEP-01-0161": PEPProfile(
        pep_id="PEP-01-0161",
        full_name="Arthur Sterling",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #161",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Arthur", "Hon. Arthur Sterling"]
    ),
    "PEP-01-0162": PEPProfile(
        pep_id="PEP-01-0162",
        full_name="Beatrice Volkov",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #162",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Beatrice", "Hon. Beatrice Volkov"]
    ),
    "PEP-01-0163": PEPProfile(
        pep_id="PEP-01-0163",
        full_name="Carlos Silva",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #163",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Carlos", "Hon. Carlos Silva"]
    ),
    "PEP-01-0164": PEPProfile(
        pep_id="PEP-01-0164",
        full_name="Dmitri Chen",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #164",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Dmitri", "Hon. Dmitri Chen"]
    ),
    "PEP-01-0165": PEPProfile(
        pep_id="PEP-01-0165",
        full_name="Elena Fernandez",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #165",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Elena", "Hon. Elena Fernandez"]
    ),
    "PEP-01-0166": PEPProfile(
        pep_id="PEP-01-0166",
        full_name="Fatima Patel",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #166",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Fatima", "Hon. Fatima Patel"]
    ),
    "PEP-01-0167": PEPProfile(
        pep_id="PEP-01-0167",
        full_name="Gabriel Reddy",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #167",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Gabriel", "Hon. Gabriel Reddy"]
    ),
    "PEP-01-0168": PEPProfile(
        pep_id="PEP-01-0168",
        full_name="Helena Mercer",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #168",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Helena", "Hon. Helena Mercer"]
    ),
    "PEP-01-0169": PEPProfile(
        pep_id="PEP-01-0169",
        full_name="Ibrahim Schneider",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #169",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Ibrahim", "Hon. Ibrahim Schneider"]
    ),
    "PEP-01-0170": PEPProfile(
        pep_id="PEP-01-0170",
        full_name="Julia Lombardi",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #170",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Julia", "Hon. Julia Lombardi"]
    ),
    "PEP-01-0171": PEPProfile(
        pep_id="PEP-01-0171",
        full_name="Klaus Weber",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #171",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Klaus", "Hon. Klaus Weber"]
    ),
    "PEP-01-0172": PEPProfile(
        pep_id="PEP-01-0172",
        full_name="Lucia Kovacs",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #172",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Lucia", "Hon. Lucia Kovacs"]
    ),
    "PEP-01-0173": PEPProfile(
        pep_id="PEP-01-0173",
        full_name="Mateo Khan",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #173",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Mateo", "Hon. Mateo Khan"]
    ),
    "PEP-01-0174": PEPProfile(
        pep_id="PEP-01-0174",
        full_name="Nadia Rahman",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #174",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Nadia", "Hon. Nadia Rahman"]
    ),
    "PEP-01-0175": PEPProfile(
        pep_id="PEP-01-0175",
        full_name="Omar Vargas",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #175",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Omar", "Hon. Omar Vargas"]
    ),
    "PEP-01-0176": PEPProfile(
        pep_id="PEP-01-0176",
        full_name="Pradeep Al-Sayed",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #176",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Pradeep", "Hon. Pradeep Al-Sayed"]
    ),
    "PEP-01-0177": PEPProfile(
        pep_id="PEP-01-0177",
        full_name="Qasim Mansour",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #177",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Qasim", "Hon. Qasim Mansour"]
    ),
    "PEP-01-0178": PEPProfile(
        pep_id="PEP-01-0178",
        full_name="Rosa Santos",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #178",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Rosa", "Hon. Rosa Santos"]
    ),
    "PEP-01-0179": PEPProfile(
        pep_id="PEP-01-0179",
        full_name="Siddharth Haddad",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #179",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Siddharth", "Hon. Siddharth Haddad"]
    ),
    "PEP-01-0180": PEPProfile(
        pep_id="PEP-01-0180",
        full_name="Tariq Morales",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Heads of State & Government Official #180",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Tariq", "Hon. Tariq Morales"]
    ),
}
