"""
Tier 1 Central Bank Governors.
Monetary Policy Authorities.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional

@dataclass
class PEPProfile:
    pep_id: str
    full_name: str
    country_code: str
    country_name: str
    tier: int
    role_title: str
    department_or_agency: str
    is_active: bool = True
    risk_score: float = 8.5
    source_of_wealth: Optional[str] = None
    aliases: List[str] = field(default_factory=list)

PEP_RECORDS_TIER1_CENTRAL_BANKERS: Dict[str, PEPProfile] = {
    "PEP-03-0001": PEPProfile(
        pep_id="PEP-03-0001",
        full_name="Arthur Vargas",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #1",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Arthur", "Hon. Arthur Vargas"]
    ),
    "PEP-03-0002": PEPProfile(
        pep_id="PEP-03-0002",
        full_name="Beatrice Al-Sayed",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #2",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Beatrice", "Hon. Beatrice Al-Sayed"]
    ),
    "PEP-03-0003": PEPProfile(
        pep_id="PEP-03-0003",
        full_name="Carlos Mansour",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #3",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Carlos", "Hon. Carlos Mansour"]
    ),
    "PEP-03-0004": PEPProfile(
        pep_id="PEP-03-0004",
        full_name="Dmitri Santos",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #4",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Dmitri", "Hon. Dmitri Santos"]
    ),
    "PEP-03-0005": PEPProfile(
        pep_id="PEP-03-0005",
        full_name="Elena Haddad",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #5",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Elena", "Hon. Elena Haddad"]
    ),
    "PEP-03-0006": PEPProfile(
        pep_id="PEP-03-0006",
        full_name="Fatima Morales",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #6",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Fatima", "Hon. Fatima Morales"]
    ),
    "PEP-03-0007": PEPProfile(
        pep_id="PEP-03-0007",
        full_name="Gabriel Sterling",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #7",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Gabriel", "Hon. Gabriel Sterling"]
    ),
    "PEP-03-0008": PEPProfile(
        pep_id="PEP-03-0008",
        full_name="Helena Volkov",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #8",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Helena", "Hon. Helena Volkov"]
    ),
    "PEP-03-0009": PEPProfile(
        pep_id="PEP-03-0009",
        full_name="Ibrahim Silva",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #9",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Ibrahim", "Hon. Ibrahim Silva"]
    ),
    "PEP-03-0010": PEPProfile(
        pep_id="PEP-03-0010",
        full_name="Julia Chen",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #10",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Julia", "Hon. Julia Chen"]
    ),
    "PEP-03-0011": PEPProfile(
        pep_id="PEP-03-0011",
        full_name="Klaus Fernandez",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #11",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Klaus", "Hon. Klaus Fernandez"]
    ),
    "PEP-03-0012": PEPProfile(
        pep_id="PEP-03-0012",
        full_name="Lucia Patel",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #12",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Lucia", "Hon. Lucia Patel"]
    ),
    "PEP-03-0013": PEPProfile(
        pep_id="PEP-03-0013",
        full_name="Mateo Reddy",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #13",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Mateo", "Hon. Mateo Reddy"]
    ),
    "PEP-03-0014": PEPProfile(
        pep_id="PEP-03-0014",
        full_name="Nadia Mercer",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #14",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Nadia", "Hon. Nadia Mercer"]
    ),
    "PEP-03-0015": PEPProfile(
        pep_id="PEP-03-0015",
        full_name="Omar Schneider",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #15",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Omar", "Hon. Omar Schneider"]
    ),
    "PEP-03-0016": PEPProfile(
        pep_id="PEP-03-0016",
        full_name="Pradeep Lombardi",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #16",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Pradeep", "Hon. Pradeep Lombardi"]
    ),
    "PEP-03-0017": PEPProfile(
        pep_id="PEP-03-0017",
        full_name="Qasim Weber",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #17",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Qasim", "Hon. Qasim Weber"]
    ),
    "PEP-03-0018": PEPProfile(
        pep_id="PEP-03-0018",
        full_name="Rosa Kovacs",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #18",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Rosa", "Hon. Rosa Kovacs"]
    ),
    "PEP-03-0019": PEPProfile(
        pep_id="PEP-03-0019",
        full_name="Siddharth Khan",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #19",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Siddharth", "Hon. Siddharth Khan"]
    ),
    "PEP-03-0020": PEPProfile(
        pep_id="PEP-03-0020",
        full_name="Tariq Rahman",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #20",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Tariq", "Hon. Tariq Rahman"]
    ),
    "PEP-03-0021": PEPProfile(
        pep_id="PEP-03-0021",
        full_name="Arthur Vargas",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #21",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Arthur", "Hon. Arthur Vargas"]
    ),
    "PEP-03-0022": PEPProfile(
        pep_id="PEP-03-0022",
        full_name="Beatrice Al-Sayed",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #22",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Beatrice", "Hon. Beatrice Al-Sayed"]
    ),
    "PEP-03-0023": PEPProfile(
        pep_id="PEP-03-0023",
        full_name="Carlos Mansour",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #23",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Carlos", "Hon. Carlos Mansour"]
    ),
    "PEP-03-0024": PEPProfile(
        pep_id="PEP-03-0024",
        full_name="Dmitri Santos",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #24",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Dmitri", "Hon. Dmitri Santos"]
    ),
    "PEP-03-0025": PEPProfile(
        pep_id="PEP-03-0025",
        full_name="Elena Haddad",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #25",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Elena", "Hon. Elena Haddad"]
    ),
    "PEP-03-0026": PEPProfile(
        pep_id="PEP-03-0026",
        full_name="Fatima Morales",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #26",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Fatima", "Hon. Fatima Morales"]
    ),
    "PEP-03-0027": PEPProfile(
        pep_id="PEP-03-0027",
        full_name="Gabriel Sterling",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #27",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Gabriel", "Hon. Gabriel Sterling"]
    ),
    "PEP-03-0028": PEPProfile(
        pep_id="PEP-03-0028",
        full_name="Helena Volkov",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #28",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Helena", "Hon. Helena Volkov"]
    ),
    "PEP-03-0029": PEPProfile(
        pep_id="PEP-03-0029",
        full_name="Ibrahim Silva",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #29",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Ibrahim", "Hon. Ibrahim Silva"]
    ),
    "PEP-03-0030": PEPProfile(
        pep_id="PEP-03-0030",
        full_name="Julia Chen",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #30",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Julia", "Hon. Julia Chen"]
    ),
    "PEP-03-0031": PEPProfile(
        pep_id="PEP-03-0031",
        full_name="Klaus Fernandez",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #31",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Klaus", "Hon. Klaus Fernandez"]
    ),
    "PEP-03-0032": PEPProfile(
        pep_id="PEP-03-0032",
        full_name="Lucia Patel",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #32",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Lucia", "Hon. Lucia Patel"]
    ),
    "PEP-03-0033": PEPProfile(
        pep_id="PEP-03-0033",
        full_name="Mateo Reddy",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #33",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Mateo", "Hon. Mateo Reddy"]
    ),
    "PEP-03-0034": PEPProfile(
        pep_id="PEP-03-0034",
        full_name="Nadia Mercer",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #34",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Nadia", "Hon. Nadia Mercer"]
    ),
    "PEP-03-0035": PEPProfile(
        pep_id="PEP-03-0035",
        full_name="Omar Schneider",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #35",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Omar", "Hon. Omar Schneider"]
    ),
    "PEP-03-0036": PEPProfile(
        pep_id="PEP-03-0036",
        full_name="Pradeep Lombardi",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #36",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Pradeep", "Hon. Pradeep Lombardi"]
    ),
    "PEP-03-0037": PEPProfile(
        pep_id="PEP-03-0037",
        full_name="Qasim Weber",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #37",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Qasim", "Hon. Qasim Weber"]
    ),
    "PEP-03-0038": PEPProfile(
        pep_id="PEP-03-0038",
        full_name="Rosa Kovacs",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #38",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Rosa", "Hon. Rosa Kovacs"]
    ),
    "PEP-03-0039": PEPProfile(
        pep_id="PEP-03-0039",
        full_name="Siddharth Khan",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #39",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Siddharth", "Hon. Siddharth Khan"]
    ),
    "PEP-03-0040": PEPProfile(
        pep_id="PEP-03-0040",
        full_name="Tariq Rahman",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #40",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Tariq", "Hon. Tariq Rahman"]
    ),
    "PEP-03-0041": PEPProfile(
        pep_id="PEP-03-0041",
        full_name="Arthur Vargas",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #41",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Arthur", "Hon. Arthur Vargas"]
    ),
    "PEP-03-0042": PEPProfile(
        pep_id="PEP-03-0042",
        full_name="Beatrice Al-Sayed",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #42",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Beatrice", "Hon. Beatrice Al-Sayed"]
    ),
    "PEP-03-0043": PEPProfile(
        pep_id="PEP-03-0043",
        full_name="Carlos Mansour",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #43",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Carlos", "Hon. Carlos Mansour"]
    ),
    "PEP-03-0044": PEPProfile(
        pep_id="PEP-03-0044",
        full_name="Dmitri Santos",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #44",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Dmitri", "Hon. Dmitri Santos"]
    ),
    "PEP-03-0045": PEPProfile(
        pep_id="PEP-03-0045",
        full_name="Elena Haddad",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #45",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Elena", "Hon. Elena Haddad"]
    ),
    "PEP-03-0046": PEPProfile(
        pep_id="PEP-03-0046",
        full_name="Fatima Morales",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #46",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Fatima", "Hon. Fatima Morales"]
    ),
    "PEP-03-0047": PEPProfile(
        pep_id="PEP-03-0047",
        full_name="Gabriel Sterling",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #47",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Gabriel", "Hon. Gabriel Sterling"]
    ),
    "PEP-03-0048": PEPProfile(
        pep_id="PEP-03-0048",
        full_name="Helena Volkov",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #48",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Helena", "Hon. Helena Volkov"]
    ),
    "PEP-03-0049": PEPProfile(
        pep_id="PEP-03-0049",
        full_name="Ibrahim Silva",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #49",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Ibrahim", "Hon. Ibrahim Silva"]
    ),
    "PEP-03-0050": PEPProfile(
        pep_id="PEP-03-0050",
        full_name="Julia Chen",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #50",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Julia", "Hon. Julia Chen"]
    ),
    "PEP-03-0051": PEPProfile(
        pep_id="PEP-03-0051",
        full_name="Klaus Fernandez",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #51",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Klaus", "Hon. Klaus Fernandez"]
    ),
    "PEP-03-0052": PEPProfile(
        pep_id="PEP-03-0052",
        full_name="Lucia Patel",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #52",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Lucia", "Hon. Lucia Patel"]
    ),
    "PEP-03-0053": PEPProfile(
        pep_id="PEP-03-0053",
        full_name="Mateo Reddy",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #53",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Mateo", "Hon. Mateo Reddy"]
    ),
    "PEP-03-0054": PEPProfile(
        pep_id="PEP-03-0054",
        full_name="Nadia Mercer",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #54",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Nadia", "Hon. Nadia Mercer"]
    ),
    "PEP-03-0055": PEPProfile(
        pep_id="PEP-03-0055",
        full_name="Omar Schneider",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #55",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Omar", "Hon. Omar Schneider"]
    ),
    "PEP-03-0056": PEPProfile(
        pep_id="PEP-03-0056",
        full_name="Pradeep Lombardi",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #56",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Pradeep", "Hon. Pradeep Lombardi"]
    ),
    "PEP-03-0057": PEPProfile(
        pep_id="PEP-03-0057",
        full_name="Qasim Weber",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #57",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Qasim", "Hon. Qasim Weber"]
    ),
    "PEP-03-0058": PEPProfile(
        pep_id="PEP-03-0058",
        full_name="Rosa Kovacs",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #58",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Rosa", "Hon. Rosa Kovacs"]
    ),
    "PEP-03-0059": PEPProfile(
        pep_id="PEP-03-0059",
        full_name="Siddharth Khan",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #59",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Siddharth", "Hon. Siddharth Khan"]
    ),
    "PEP-03-0060": PEPProfile(
        pep_id="PEP-03-0060",
        full_name="Tariq Rahman",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #60",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Tariq", "Hon. Tariq Rahman"]
    ),
    "PEP-03-0061": PEPProfile(
        pep_id="PEP-03-0061",
        full_name="Arthur Vargas",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #61",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Arthur", "Hon. Arthur Vargas"]
    ),
    "PEP-03-0062": PEPProfile(
        pep_id="PEP-03-0062",
        full_name="Beatrice Al-Sayed",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #62",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Beatrice", "Hon. Beatrice Al-Sayed"]
    ),
    "PEP-03-0063": PEPProfile(
        pep_id="PEP-03-0063",
        full_name="Carlos Mansour",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #63",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Carlos", "Hon. Carlos Mansour"]
    ),
    "PEP-03-0064": PEPProfile(
        pep_id="PEP-03-0064",
        full_name="Dmitri Santos",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #64",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Dmitri", "Hon. Dmitri Santos"]
    ),
    "PEP-03-0065": PEPProfile(
        pep_id="PEP-03-0065",
        full_name="Elena Haddad",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #65",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Elena", "Hon. Elena Haddad"]
    ),
    "PEP-03-0066": PEPProfile(
        pep_id="PEP-03-0066",
        full_name="Fatima Morales",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #66",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Fatima", "Hon. Fatima Morales"]
    ),
    "PEP-03-0067": PEPProfile(
        pep_id="PEP-03-0067",
        full_name="Gabriel Sterling",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #67",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Gabriel", "Hon. Gabriel Sterling"]
    ),
    "PEP-03-0068": PEPProfile(
        pep_id="PEP-03-0068",
        full_name="Helena Volkov",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #68",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Helena", "Hon. Helena Volkov"]
    ),
    "PEP-03-0069": PEPProfile(
        pep_id="PEP-03-0069",
        full_name="Ibrahim Silva",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #69",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Ibrahim", "Hon. Ibrahim Silva"]
    ),
    "PEP-03-0070": PEPProfile(
        pep_id="PEP-03-0070",
        full_name="Julia Chen",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #70",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Julia", "Hon. Julia Chen"]
    ),
    "PEP-03-0071": PEPProfile(
        pep_id="PEP-03-0071",
        full_name="Klaus Fernandez",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #71",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Klaus", "Hon. Klaus Fernandez"]
    ),
    "PEP-03-0072": PEPProfile(
        pep_id="PEP-03-0072",
        full_name="Lucia Patel",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #72",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Lucia", "Hon. Lucia Patel"]
    ),
    "PEP-03-0073": PEPProfile(
        pep_id="PEP-03-0073",
        full_name="Mateo Reddy",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #73",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Mateo", "Hon. Mateo Reddy"]
    ),
    "PEP-03-0074": PEPProfile(
        pep_id="PEP-03-0074",
        full_name="Nadia Mercer",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #74",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Nadia", "Hon. Nadia Mercer"]
    ),
    "PEP-03-0075": PEPProfile(
        pep_id="PEP-03-0075",
        full_name="Omar Schneider",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #75",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Omar", "Hon. Omar Schneider"]
    ),
    "PEP-03-0076": PEPProfile(
        pep_id="PEP-03-0076",
        full_name="Pradeep Lombardi",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #76",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Pradeep", "Hon. Pradeep Lombardi"]
    ),
    "PEP-03-0077": PEPProfile(
        pep_id="PEP-03-0077",
        full_name="Qasim Weber",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #77",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Qasim", "Hon. Qasim Weber"]
    ),
    "PEP-03-0078": PEPProfile(
        pep_id="PEP-03-0078",
        full_name="Rosa Kovacs",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #78",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Rosa", "Hon. Rosa Kovacs"]
    ),
    "PEP-03-0079": PEPProfile(
        pep_id="PEP-03-0079",
        full_name="Siddharth Khan",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #79",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Siddharth", "Hon. Siddharth Khan"]
    ),
    "PEP-03-0080": PEPProfile(
        pep_id="PEP-03-0080",
        full_name="Tariq Rahman",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #80",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Tariq", "Hon. Tariq Rahman"]
    ),
    "PEP-03-0081": PEPProfile(
        pep_id="PEP-03-0081",
        full_name="Arthur Vargas",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #81",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Arthur", "Hon. Arthur Vargas"]
    ),
    "PEP-03-0082": PEPProfile(
        pep_id="PEP-03-0082",
        full_name="Beatrice Al-Sayed",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #82",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Beatrice", "Hon. Beatrice Al-Sayed"]
    ),
    "PEP-03-0083": PEPProfile(
        pep_id="PEP-03-0083",
        full_name="Carlos Mansour",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #83",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Carlos", "Hon. Carlos Mansour"]
    ),
    "PEP-03-0084": PEPProfile(
        pep_id="PEP-03-0084",
        full_name="Dmitri Santos",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #84",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Dmitri", "Hon. Dmitri Santos"]
    ),
    "PEP-03-0085": PEPProfile(
        pep_id="PEP-03-0085",
        full_name="Elena Haddad",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #85",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Elena", "Hon. Elena Haddad"]
    ),
    "PEP-03-0086": PEPProfile(
        pep_id="PEP-03-0086",
        full_name="Fatima Morales",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #86",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Fatima", "Hon. Fatima Morales"]
    ),
    "PEP-03-0087": PEPProfile(
        pep_id="PEP-03-0087",
        full_name="Gabriel Sterling",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #87",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Gabriel", "Hon. Gabriel Sterling"]
    ),
    "PEP-03-0088": PEPProfile(
        pep_id="PEP-03-0088",
        full_name="Helena Volkov",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #88",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Helena", "Hon. Helena Volkov"]
    ),
    "PEP-03-0089": PEPProfile(
        pep_id="PEP-03-0089",
        full_name="Ibrahim Silva",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #89",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Ibrahim", "Hon. Ibrahim Silva"]
    ),
    "PEP-03-0090": PEPProfile(
        pep_id="PEP-03-0090",
        full_name="Julia Chen",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #90",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Julia", "Hon. Julia Chen"]
    ),
    "PEP-03-0091": PEPProfile(
        pep_id="PEP-03-0091",
        full_name="Klaus Fernandez",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #91",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Klaus", "Hon. Klaus Fernandez"]
    ),
    "PEP-03-0092": PEPProfile(
        pep_id="PEP-03-0092",
        full_name="Lucia Patel",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #92",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Lucia", "Hon. Lucia Patel"]
    ),
    "PEP-03-0093": PEPProfile(
        pep_id="PEP-03-0093",
        full_name="Mateo Reddy",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #93",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Mateo", "Hon. Mateo Reddy"]
    ),
    "PEP-03-0094": PEPProfile(
        pep_id="PEP-03-0094",
        full_name="Nadia Mercer",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #94",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Nadia", "Hon. Nadia Mercer"]
    ),
    "PEP-03-0095": PEPProfile(
        pep_id="PEP-03-0095",
        full_name="Omar Schneider",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #95",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Omar", "Hon. Omar Schneider"]
    ),
    "PEP-03-0096": PEPProfile(
        pep_id="PEP-03-0096",
        full_name="Pradeep Lombardi",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #96",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Pradeep", "Hon. Pradeep Lombardi"]
    ),
    "PEP-03-0097": PEPProfile(
        pep_id="PEP-03-0097",
        full_name="Qasim Weber",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #97",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Qasim", "Hon. Qasim Weber"]
    ),
    "PEP-03-0098": PEPProfile(
        pep_id="PEP-03-0098",
        full_name="Rosa Kovacs",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #98",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Rosa", "Hon. Rosa Kovacs"]
    ),
    "PEP-03-0099": PEPProfile(
        pep_id="PEP-03-0099",
        full_name="Siddharth Khan",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #99",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Siddharth", "Hon. Siddharth Khan"]
    ),
    "PEP-03-0100": PEPProfile(
        pep_id="PEP-03-0100",
        full_name="Tariq Rahman",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #100",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Tariq", "Hon. Tariq Rahman"]
    ),
    "PEP-03-0101": PEPProfile(
        pep_id="PEP-03-0101",
        full_name="Arthur Vargas",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #101",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Arthur", "Hon. Arthur Vargas"]
    ),
    "PEP-03-0102": PEPProfile(
        pep_id="PEP-03-0102",
        full_name="Beatrice Al-Sayed",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #102",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Beatrice", "Hon. Beatrice Al-Sayed"]
    ),
    "PEP-03-0103": PEPProfile(
        pep_id="PEP-03-0103",
        full_name="Carlos Mansour",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #103",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Carlos", "Hon. Carlos Mansour"]
    ),
    "PEP-03-0104": PEPProfile(
        pep_id="PEP-03-0104",
        full_name="Dmitri Santos",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #104",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Dmitri", "Hon. Dmitri Santos"]
    ),
    "PEP-03-0105": PEPProfile(
        pep_id="PEP-03-0105",
        full_name="Elena Haddad",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #105",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Elena", "Hon. Elena Haddad"]
    ),
    "PEP-03-0106": PEPProfile(
        pep_id="PEP-03-0106",
        full_name="Fatima Morales",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #106",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Fatima", "Hon. Fatima Morales"]
    ),
    "PEP-03-0107": PEPProfile(
        pep_id="PEP-03-0107",
        full_name="Gabriel Sterling",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #107",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Gabriel", "Hon. Gabriel Sterling"]
    ),
    "PEP-03-0108": PEPProfile(
        pep_id="PEP-03-0108",
        full_name="Helena Volkov",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #108",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Helena", "Hon. Helena Volkov"]
    ),
    "PEP-03-0109": PEPProfile(
        pep_id="PEP-03-0109",
        full_name="Ibrahim Silva",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #109",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Ibrahim", "Hon. Ibrahim Silva"]
    ),
    "PEP-03-0110": PEPProfile(
        pep_id="PEP-03-0110",
        full_name="Julia Chen",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #110",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Julia", "Hon. Julia Chen"]
    ),
    "PEP-03-0111": PEPProfile(
        pep_id="PEP-03-0111",
        full_name="Klaus Fernandez",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #111",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Klaus", "Hon. Klaus Fernandez"]
    ),
    "PEP-03-0112": PEPProfile(
        pep_id="PEP-03-0112",
        full_name="Lucia Patel",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #112",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Lucia", "Hon. Lucia Patel"]
    ),
    "PEP-03-0113": PEPProfile(
        pep_id="PEP-03-0113",
        full_name="Mateo Reddy",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #113",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Mateo", "Hon. Mateo Reddy"]
    ),
    "PEP-03-0114": PEPProfile(
        pep_id="PEP-03-0114",
        full_name="Nadia Mercer",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #114",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Nadia", "Hon. Nadia Mercer"]
    ),
    "PEP-03-0115": PEPProfile(
        pep_id="PEP-03-0115",
        full_name="Omar Schneider",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #115",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Omar", "Hon. Omar Schneider"]
    ),
    "PEP-03-0116": PEPProfile(
        pep_id="PEP-03-0116",
        full_name="Pradeep Lombardi",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #116",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Pradeep", "Hon. Pradeep Lombardi"]
    ),
    "PEP-03-0117": PEPProfile(
        pep_id="PEP-03-0117",
        full_name="Qasim Weber",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #117",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Qasim", "Hon. Qasim Weber"]
    ),
    "PEP-03-0118": PEPProfile(
        pep_id="PEP-03-0118",
        full_name="Rosa Kovacs",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #118",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Rosa", "Hon. Rosa Kovacs"]
    ),
    "PEP-03-0119": PEPProfile(
        pep_id="PEP-03-0119",
        full_name="Siddharth Khan",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #119",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Siddharth", "Hon. Siddharth Khan"]
    ),
    "PEP-03-0120": PEPProfile(
        pep_id="PEP-03-0120",
        full_name="Tariq Rahman",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #120",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Tariq", "Hon. Tariq Rahman"]
    ),
    "PEP-03-0121": PEPProfile(
        pep_id="PEP-03-0121",
        full_name="Arthur Vargas",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #121",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Arthur", "Hon. Arthur Vargas"]
    ),
    "PEP-03-0122": PEPProfile(
        pep_id="PEP-03-0122",
        full_name="Beatrice Al-Sayed",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #122",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Beatrice", "Hon. Beatrice Al-Sayed"]
    ),
    "PEP-03-0123": PEPProfile(
        pep_id="PEP-03-0123",
        full_name="Carlos Mansour",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #123",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Carlos", "Hon. Carlos Mansour"]
    ),
    "PEP-03-0124": PEPProfile(
        pep_id="PEP-03-0124",
        full_name="Dmitri Santos",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #124",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Dmitri", "Hon. Dmitri Santos"]
    ),
    "PEP-03-0125": PEPProfile(
        pep_id="PEP-03-0125",
        full_name="Elena Haddad",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #125",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Elena", "Hon. Elena Haddad"]
    ),
    "PEP-03-0126": PEPProfile(
        pep_id="PEP-03-0126",
        full_name="Fatima Morales",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #126",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Fatima", "Hon. Fatima Morales"]
    ),
    "PEP-03-0127": PEPProfile(
        pep_id="PEP-03-0127",
        full_name="Gabriel Sterling",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #127",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Gabriel", "Hon. Gabriel Sterling"]
    ),
    "PEP-03-0128": PEPProfile(
        pep_id="PEP-03-0128",
        full_name="Helena Volkov",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #128",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Helena", "Hon. Helena Volkov"]
    ),
    "PEP-03-0129": PEPProfile(
        pep_id="PEP-03-0129",
        full_name="Ibrahim Silva",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #129",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Ibrahim", "Hon. Ibrahim Silva"]
    ),
    "PEP-03-0130": PEPProfile(
        pep_id="PEP-03-0130",
        full_name="Julia Chen",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #130",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Julia", "Hon. Julia Chen"]
    ),
    "PEP-03-0131": PEPProfile(
        pep_id="PEP-03-0131",
        full_name="Klaus Fernandez",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #131",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Klaus", "Hon. Klaus Fernandez"]
    ),
    "PEP-03-0132": PEPProfile(
        pep_id="PEP-03-0132",
        full_name="Lucia Patel",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #132",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Lucia", "Hon. Lucia Patel"]
    ),
    "PEP-03-0133": PEPProfile(
        pep_id="PEP-03-0133",
        full_name="Mateo Reddy",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #133",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Mateo", "Hon. Mateo Reddy"]
    ),
    "PEP-03-0134": PEPProfile(
        pep_id="PEP-03-0134",
        full_name="Nadia Mercer",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #134",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Nadia", "Hon. Nadia Mercer"]
    ),
    "PEP-03-0135": PEPProfile(
        pep_id="PEP-03-0135",
        full_name="Omar Schneider",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #135",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Omar", "Hon. Omar Schneider"]
    ),
    "PEP-03-0136": PEPProfile(
        pep_id="PEP-03-0136",
        full_name="Pradeep Lombardi",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #136",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Pradeep", "Hon. Pradeep Lombardi"]
    ),
    "PEP-03-0137": PEPProfile(
        pep_id="PEP-03-0137",
        full_name="Qasim Weber",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #137",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Qasim", "Hon. Qasim Weber"]
    ),
    "PEP-03-0138": PEPProfile(
        pep_id="PEP-03-0138",
        full_name="Rosa Kovacs",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #138",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Rosa", "Hon. Rosa Kovacs"]
    ),
    "PEP-03-0139": PEPProfile(
        pep_id="PEP-03-0139",
        full_name="Siddharth Khan",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #139",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Siddharth", "Hon. Siddharth Khan"]
    ),
    "PEP-03-0140": PEPProfile(
        pep_id="PEP-03-0140",
        full_name="Tariq Rahman",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #140",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Tariq", "Hon. Tariq Rahman"]
    ),
    "PEP-03-0141": PEPProfile(
        pep_id="PEP-03-0141",
        full_name="Arthur Vargas",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #141",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Arthur", "Hon. Arthur Vargas"]
    ),
    "PEP-03-0142": PEPProfile(
        pep_id="PEP-03-0142",
        full_name="Beatrice Al-Sayed",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #142",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Beatrice", "Hon. Beatrice Al-Sayed"]
    ),
    "PEP-03-0143": PEPProfile(
        pep_id="PEP-03-0143",
        full_name="Carlos Mansour",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #143",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Carlos", "Hon. Carlos Mansour"]
    ),
    "PEP-03-0144": PEPProfile(
        pep_id="PEP-03-0144",
        full_name="Dmitri Santos",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #144",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Dmitri", "Hon. Dmitri Santos"]
    ),
    "PEP-03-0145": PEPProfile(
        pep_id="PEP-03-0145",
        full_name="Elena Haddad",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #145",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Elena", "Hon. Elena Haddad"]
    ),
    "PEP-03-0146": PEPProfile(
        pep_id="PEP-03-0146",
        full_name="Fatima Morales",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #146",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Fatima", "Hon. Fatima Morales"]
    ),
    "PEP-03-0147": PEPProfile(
        pep_id="PEP-03-0147",
        full_name="Gabriel Sterling",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #147",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Gabriel", "Hon. Gabriel Sterling"]
    ),
    "PEP-03-0148": PEPProfile(
        pep_id="PEP-03-0148",
        full_name="Helena Volkov",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #148",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Helena", "Hon. Helena Volkov"]
    ),
    "PEP-03-0149": PEPProfile(
        pep_id="PEP-03-0149",
        full_name="Ibrahim Silva",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #149",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Ibrahim", "Hon. Ibrahim Silva"]
    ),
    "PEP-03-0150": PEPProfile(
        pep_id="PEP-03-0150",
        full_name="Julia Chen",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #150",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Julia", "Hon. Julia Chen"]
    ),
    "PEP-03-0151": PEPProfile(
        pep_id="PEP-03-0151",
        full_name="Klaus Fernandez",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #151",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Klaus", "Hon. Klaus Fernandez"]
    ),
    "PEP-03-0152": PEPProfile(
        pep_id="PEP-03-0152",
        full_name="Lucia Patel",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #152",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Lucia", "Hon. Lucia Patel"]
    ),
    "PEP-03-0153": PEPProfile(
        pep_id="PEP-03-0153",
        full_name="Mateo Reddy",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #153",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Mateo", "Hon. Mateo Reddy"]
    ),
    "PEP-03-0154": PEPProfile(
        pep_id="PEP-03-0154",
        full_name="Nadia Mercer",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #154",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Nadia", "Hon. Nadia Mercer"]
    ),
    "PEP-03-0155": PEPProfile(
        pep_id="PEP-03-0155",
        full_name="Omar Schneider",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #155",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Omar", "Hon. Omar Schneider"]
    ),
    "PEP-03-0156": PEPProfile(
        pep_id="PEP-03-0156",
        full_name="Pradeep Lombardi",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #156",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Pradeep", "Hon. Pradeep Lombardi"]
    ),
    "PEP-03-0157": PEPProfile(
        pep_id="PEP-03-0157",
        full_name="Qasim Weber",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #157",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Qasim", "Hon. Qasim Weber"]
    ),
    "PEP-03-0158": PEPProfile(
        pep_id="PEP-03-0158",
        full_name="Rosa Kovacs",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #158",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Rosa", "Hon. Rosa Kovacs"]
    ),
    "PEP-03-0159": PEPProfile(
        pep_id="PEP-03-0159",
        full_name="Siddharth Khan",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #159",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Siddharth", "Hon. Siddharth Khan"]
    ),
    "PEP-03-0160": PEPProfile(
        pep_id="PEP-03-0160",
        full_name="Tariq Rahman",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #160",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Tariq", "Hon. Tariq Rahman"]
    ),
    "PEP-03-0161": PEPProfile(
        pep_id="PEP-03-0161",
        full_name="Arthur Vargas",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #161",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Arthur", "Hon. Arthur Vargas"]
    ),
    "PEP-03-0162": PEPProfile(
        pep_id="PEP-03-0162",
        full_name="Beatrice Al-Sayed",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #162",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Beatrice", "Hon. Beatrice Al-Sayed"]
    ),
    "PEP-03-0163": PEPProfile(
        pep_id="PEP-03-0163",
        full_name="Carlos Mansour",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #163",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Carlos", "Hon. Carlos Mansour"]
    ),
    "PEP-03-0164": PEPProfile(
        pep_id="PEP-03-0164",
        full_name="Dmitri Santos",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #164",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Dmitri", "Hon. Dmitri Santos"]
    ),
    "PEP-03-0165": PEPProfile(
        pep_id="PEP-03-0165",
        full_name="Elena Haddad",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #165",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Elena", "Hon. Elena Haddad"]
    ),
    "PEP-03-0166": PEPProfile(
        pep_id="PEP-03-0166",
        full_name="Fatima Morales",
        country_code="DEU",
        country_name="Germany",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #166",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Fatima", "Hon. Fatima Morales"]
    ),
    "PEP-03-0167": PEPProfile(
        pep_id="PEP-03-0167",
        full_name="Gabriel Sterling",
        country_code="FRA",
        country_name="France",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #167",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Gabriel", "Hon. Gabriel Sterling"]
    ),
    "PEP-03-0168": PEPProfile(
        pep_id="PEP-03-0168",
        full_name="Helena Volkov",
        country_code="CHE",
        country_name="Switzerland",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #168",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Helena", "Hon. Helena Volkov"]
    ),
    "PEP-03-0169": PEPProfile(
        pep_id="PEP-03-0169",
        full_name="Ibrahim Silva",
        country_code="SGP",
        country_name="Singapore",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #169",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Ibrahim", "Hon. Ibrahim Silva"]
    ),
    "PEP-03-0170": PEPProfile(
        pep_id="PEP-03-0170",
        full_name="Julia Chen",
        country_code="HKG",
        country_name="Hong Kong",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #170",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Julia", "Hon. Julia Chen"]
    ),
    "PEP-03-0171": PEPProfile(
        pep_id="PEP-03-0171",
        full_name="Klaus Fernandez",
        country_code="JPN",
        country_name="Japan",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #171",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Klaus", "Hon. Klaus Fernandez"]
    ),
    "PEP-03-0172": PEPProfile(
        pep_id="PEP-03-0172",
        full_name="Lucia Patel",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #172",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Lucia", "Hon. Lucia Patel"]
    ),
    "PEP-03-0173": PEPProfile(
        pep_id="PEP-03-0173",
        full_name="Mateo Reddy",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #173",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Mateo", "Hon. Mateo Reddy"]
    ),
    "PEP-03-0174": PEPProfile(
        pep_id="PEP-03-0174",
        full_name="Nadia Mercer",
        country_code="BRA",
        country_name="Brazil",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #174",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Nadia", "Hon. Nadia Mercer"]
    ),
    "PEP-03-0175": PEPProfile(
        pep_id="PEP-03-0175",
        full_name="Omar Schneider",
        country_code="IND",
        country_name="India",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #175",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Omar", "Hon. Omar Schneider"]
    ),
    "PEP-03-0176": PEPProfile(
        pep_id="PEP-03-0176",
        full_name="Pradeep Lombardi",
        country_code="ZAF",
        country_name="South Africa",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #176",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Pradeep", "Hon. Pradeep Lombardi"]
    ),
    "PEP-03-0177": PEPProfile(
        pep_id="PEP-03-0177",
        full_name="Qasim Weber",
        country_code="AUS",
        country_name="Australia",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #177",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Qasim", "Hon. Qasim Weber"]
    ),
    "PEP-03-0178": PEPProfile(
        pep_id="PEP-03-0178",
        full_name="Rosa Kovacs",
        country_code="CAN",
        country_name="Canada",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #178",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Rosa", "Hon. Rosa Kovacs"]
    ),
    "PEP-03-0179": PEPProfile(
        pep_id="PEP-03-0179",
        full_name="Siddharth Khan",
        country_code="USA",
        country_name="United States",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #179",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Siddharth", "Hon. Siddharth Khan"]
    ),
    "PEP-03-0180": PEPProfile(
        pep_id="PEP-03-0180",
        full_name="Tariq Rahman",
        country_code="GBR",
        country_name="United Kingdom",
        tier=1,
        role_title="Tier 1 Central Bank Governors Official #180",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=9.5,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Tariq", "Hon. Tariq Rahman"]
    ),
}
