"""
Tier 2 Parliamentary & Senate Leaders.
Legislative Committee Chairs.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional

@dataclass
class PEPProfile:
    pep_id: str
    full_name: str
    country_code: str
    country_name: str
    tier: int
    role_title: str
    department_or_agency: str
    is_active: bool = True
    risk_score: float = 8.5
    source_of_wealth: Optional[str] = None
    aliases: List[str] = field(default_factory=list)

PEP_RECORDS_TIER2_LEGISLATIVE_LEADERS: Dict[str, PEPProfile] = {
    "PEP-05-0001": PEPProfile(
        pep_id="PEP-05-0001",
        full_name="Arthur Schneider",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #1",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Arthur", "Hon. Arthur Schneider"]
    ),
    "PEP-05-0002": PEPProfile(
        pep_id="PEP-05-0002",
        full_name="Beatrice Lombardi",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #2",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Beatrice", "Hon. Beatrice Lombardi"]
    ),
    "PEP-05-0003": PEPProfile(
        pep_id="PEP-05-0003",
        full_name="Carlos Weber",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #3",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Carlos", "Hon. Carlos Weber"]
    ),
    "PEP-05-0004": PEPProfile(
        pep_id="PEP-05-0004",
        full_name="Dmitri Kovacs",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #4",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Dmitri", "Hon. Dmitri Kovacs"]
    ),
    "PEP-05-0005": PEPProfile(
        pep_id="PEP-05-0005",
        full_name="Elena Khan",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #5",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Elena", "Hon. Elena Khan"]
    ),
    "PEP-05-0006": PEPProfile(
        pep_id="PEP-05-0006",
        full_name="Fatima Rahman",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #6",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Fatima", "Hon. Fatima Rahman"]
    ),
    "PEP-05-0007": PEPProfile(
        pep_id="PEP-05-0007",
        full_name="Gabriel Vargas",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #7",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Gabriel", "Hon. Gabriel Vargas"]
    ),
    "PEP-05-0008": PEPProfile(
        pep_id="PEP-05-0008",
        full_name="Helena Al-Sayed",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #8",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Helena", "Hon. Helena Al-Sayed"]
    ),
    "PEP-05-0009": PEPProfile(
        pep_id="PEP-05-0009",
        full_name="Ibrahim Mansour",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #9",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Ibrahim", "Hon. Ibrahim Mansour"]
    ),
    "PEP-05-0010": PEPProfile(
        pep_id="PEP-05-0010",
        full_name="Julia Santos",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #10",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Julia", "Hon. Julia Santos"]
    ),
    "PEP-05-0011": PEPProfile(
        pep_id="PEP-05-0011",
        full_name="Klaus Haddad",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #11",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Klaus", "Hon. Klaus Haddad"]
    ),
    "PEP-05-0012": PEPProfile(
        pep_id="PEP-05-0012",
        full_name="Lucia Morales",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #12",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Lucia", "Hon. Lucia Morales"]
    ),
    "PEP-05-0013": PEPProfile(
        pep_id="PEP-05-0013",
        full_name="Mateo Sterling",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #13",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Mateo", "Hon. Mateo Sterling"]
    ),
    "PEP-05-0014": PEPProfile(
        pep_id="PEP-05-0014",
        full_name="Nadia Volkov",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #14",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Nadia", "Hon. Nadia Volkov"]
    ),
    "PEP-05-0015": PEPProfile(
        pep_id="PEP-05-0015",
        full_name="Omar Silva",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #15",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Omar", "Hon. Omar Silva"]
    ),
    "PEP-05-0016": PEPProfile(
        pep_id="PEP-05-0016",
        full_name="Pradeep Chen",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #16",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Pradeep", "Hon. Pradeep Chen"]
    ),
    "PEP-05-0017": PEPProfile(
        pep_id="PEP-05-0017",
        full_name="Qasim Fernandez",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #17",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Qasim", "Hon. Qasim Fernandez"]
    ),
    "PEP-05-0018": PEPProfile(
        pep_id="PEP-05-0018",
        full_name="Rosa Patel",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #18",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Rosa", "Hon. Rosa Patel"]
    ),
    "PEP-05-0019": PEPProfile(
        pep_id="PEP-05-0019",
        full_name="Siddharth Reddy",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #19",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Siddharth", "Hon. Siddharth Reddy"]
    ),
    "PEP-05-0020": PEPProfile(
        pep_id="PEP-05-0020",
        full_name="Tariq Mercer",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #20",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Tariq", "Hon. Tariq Mercer"]
    ),
    "PEP-05-0021": PEPProfile(
        pep_id="PEP-05-0021",
        full_name="Arthur Schneider",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #21",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Arthur", "Hon. Arthur Schneider"]
    ),
    "PEP-05-0022": PEPProfile(
        pep_id="PEP-05-0022",
        full_name="Beatrice Lombardi",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #22",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Beatrice", "Hon. Beatrice Lombardi"]
    ),
    "PEP-05-0023": PEPProfile(
        pep_id="PEP-05-0023",
        full_name="Carlos Weber",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #23",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Carlos", "Hon. Carlos Weber"]
    ),
    "PEP-05-0024": PEPProfile(
        pep_id="PEP-05-0024",
        full_name="Dmitri Kovacs",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #24",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Dmitri", "Hon. Dmitri Kovacs"]
    ),
    "PEP-05-0025": PEPProfile(
        pep_id="PEP-05-0025",
        full_name="Elena Khan",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #25",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Elena", "Hon. Elena Khan"]
    ),
    "PEP-05-0026": PEPProfile(
        pep_id="PEP-05-0026",
        full_name="Fatima Rahman",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #26",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Fatima", "Hon. Fatima Rahman"]
    ),
    "PEP-05-0027": PEPProfile(
        pep_id="PEP-05-0027",
        full_name="Gabriel Vargas",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #27",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Gabriel", "Hon. Gabriel Vargas"]
    ),
    "PEP-05-0028": PEPProfile(
        pep_id="PEP-05-0028",
        full_name="Helena Al-Sayed",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #28",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Helena", "Hon. Helena Al-Sayed"]
    ),
    "PEP-05-0029": PEPProfile(
        pep_id="PEP-05-0029",
        full_name="Ibrahim Mansour",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #29",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Ibrahim", "Hon. Ibrahim Mansour"]
    ),
    "PEP-05-0030": PEPProfile(
        pep_id="PEP-05-0030",
        full_name="Julia Santos",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #30",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Julia", "Hon. Julia Santos"]
    ),
    "PEP-05-0031": PEPProfile(
        pep_id="PEP-05-0031",
        full_name="Klaus Haddad",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #31",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Klaus", "Hon. Klaus Haddad"]
    ),
    "PEP-05-0032": PEPProfile(
        pep_id="PEP-05-0032",
        full_name="Lucia Morales",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #32",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Lucia", "Hon. Lucia Morales"]
    ),
    "PEP-05-0033": PEPProfile(
        pep_id="PEP-05-0033",
        full_name="Mateo Sterling",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #33",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Mateo", "Hon. Mateo Sterling"]
    ),
    "PEP-05-0034": PEPProfile(
        pep_id="PEP-05-0034",
        full_name="Nadia Volkov",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #34",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Nadia", "Hon. Nadia Volkov"]
    ),
    "PEP-05-0035": PEPProfile(
        pep_id="PEP-05-0035",
        full_name="Omar Silva",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #35",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Omar", "Hon. Omar Silva"]
    ),
    "PEP-05-0036": PEPProfile(
        pep_id="PEP-05-0036",
        full_name="Pradeep Chen",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #36",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Pradeep", "Hon. Pradeep Chen"]
    ),
    "PEP-05-0037": PEPProfile(
        pep_id="PEP-05-0037",
        full_name="Qasim Fernandez",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #37",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Qasim", "Hon. Qasim Fernandez"]
    ),
    "PEP-05-0038": PEPProfile(
        pep_id="PEP-05-0038",
        full_name="Rosa Patel",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #38",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Rosa", "Hon. Rosa Patel"]
    ),
    "PEP-05-0039": PEPProfile(
        pep_id="PEP-05-0039",
        full_name="Siddharth Reddy",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #39",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Siddharth", "Hon. Siddharth Reddy"]
    ),
    "PEP-05-0040": PEPProfile(
        pep_id="PEP-05-0040",
        full_name="Tariq Mercer",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #40",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Tariq", "Hon. Tariq Mercer"]
    ),
    "PEP-05-0041": PEPProfile(
        pep_id="PEP-05-0041",
        full_name="Arthur Schneider",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #41",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Arthur", "Hon. Arthur Schneider"]
    ),
    "PEP-05-0042": PEPProfile(
        pep_id="PEP-05-0042",
        full_name="Beatrice Lombardi",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #42",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Beatrice", "Hon. Beatrice Lombardi"]
    ),
    "PEP-05-0043": PEPProfile(
        pep_id="PEP-05-0043",
        full_name="Carlos Weber",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #43",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Carlos", "Hon. Carlos Weber"]
    ),
    "PEP-05-0044": PEPProfile(
        pep_id="PEP-05-0044",
        full_name="Dmitri Kovacs",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #44",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Dmitri", "Hon. Dmitri Kovacs"]
    ),
    "PEP-05-0045": PEPProfile(
        pep_id="PEP-05-0045",
        full_name="Elena Khan",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #45",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Elena", "Hon. Elena Khan"]
    ),
    "PEP-05-0046": PEPProfile(
        pep_id="PEP-05-0046",
        full_name="Fatima Rahman",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #46",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Fatima", "Hon. Fatima Rahman"]
    ),
    "PEP-05-0047": PEPProfile(
        pep_id="PEP-05-0047",
        full_name="Gabriel Vargas",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #47",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Gabriel", "Hon. Gabriel Vargas"]
    ),
    "PEP-05-0048": PEPProfile(
        pep_id="PEP-05-0048",
        full_name="Helena Al-Sayed",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #48",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Helena", "Hon. Helena Al-Sayed"]
    ),
    "PEP-05-0049": PEPProfile(
        pep_id="PEP-05-0049",
        full_name="Ibrahim Mansour",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #49",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Ibrahim", "Hon. Ibrahim Mansour"]
    ),
    "PEP-05-0050": PEPProfile(
        pep_id="PEP-05-0050",
        full_name="Julia Santos",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #50",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Julia", "Hon. Julia Santos"]
    ),
    "PEP-05-0051": PEPProfile(
        pep_id="PEP-05-0051",
        full_name="Klaus Haddad",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #51",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Klaus", "Hon. Klaus Haddad"]
    ),
    "PEP-05-0052": PEPProfile(
        pep_id="PEP-05-0052",
        full_name="Lucia Morales",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #52",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Lucia", "Hon. Lucia Morales"]
    ),
    "PEP-05-0053": PEPProfile(
        pep_id="PEP-05-0053",
        full_name="Mateo Sterling",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #53",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Mateo", "Hon. Mateo Sterling"]
    ),
    "PEP-05-0054": PEPProfile(
        pep_id="PEP-05-0054",
        full_name="Nadia Volkov",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #54",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Nadia", "Hon. Nadia Volkov"]
    ),
    "PEP-05-0055": PEPProfile(
        pep_id="PEP-05-0055",
        full_name="Omar Silva",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #55",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Omar", "Hon. Omar Silva"]
    ),
    "PEP-05-0056": PEPProfile(
        pep_id="PEP-05-0056",
        full_name="Pradeep Chen",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #56",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Pradeep", "Hon. Pradeep Chen"]
    ),
    "PEP-05-0057": PEPProfile(
        pep_id="PEP-05-0057",
        full_name="Qasim Fernandez",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #57",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Qasim", "Hon. Qasim Fernandez"]
    ),
    "PEP-05-0058": PEPProfile(
        pep_id="PEP-05-0058",
        full_name="Rosa Patel",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #58",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Rosa", "Hon. Rosa Patel"]
    ),
    "PEP-05-0059": PEPProfile(
        pep_id="PEP-05-0059",
        full_name="Siddharth Reddy",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #59",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Siddharth", "Hon. Siddharth Reddy"]
    ),
    "PEP-05-0060": PEPProfile(
        pep_id="PEP-05-0060",
        full_name="Tariq Mercer",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #60",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Tariq", "Hon. Tariq Mercer"]
    ),
    "PEP-05-0061": PEPProfile(
        pep_id="PEP-05-0061",
        full_name="Arthur Schneider",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #61",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Arthur", "Hon. Arthur Schneider"]
    ),
    "PEP-05-0062": PEPProfile(
        pep_id="PEP-05-0062",
        full_name="Beatrice Lombardi",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #62",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Beatrice", "Hon. Beatrice Lombardi"]
    ),
    "PEP-05-0063": PEPProfile(
        pep_id="PEP-05-0063",
        full_name="Carlos Weber",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #63",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Carlos", "Hon. Carlos Weber"]
    ),
    "PEP-05-0064": PEPProfile(
        pep_id="PEP-05-0064",
        full_name="Dmitri Kovacs",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #64",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Dmitri", "Hon. Dmitri Kovacs"]
    ),
    "PEP-05-0065": PEPProfile(
        pep_id="PEP-05-0065",
        full_name="Elena Khan",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #65",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Elena", "Hon. Elena Khan"]
    ),
    "PEP-05-0066": PEPProfile(
        pep_id="PEP-05-0066",
        full_name="Fatima Rahman",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #66",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Fatima", "Hon. Fatima Rahman"]
    ),
    "PEP-05-0067": PEPProfile(
        pep_id="PEP-05-0067",
        full_name="Gabriel Vargas",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #67",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Gabriel", "Hon. Gabriel Vargas"]
    ),
    "PEP-05-0068": PEPProfile(
        pep_id="PEP-05-0068",
        full_name="Helena Al-Sayed",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #68",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Helena", "Hon. Helena Al-Sayed"]
    ),
    "PEP-05-0069": PEPProfile(
        pep_id="PEP-05-0069",
        full_name="Ibrahim Mansour",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #69",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Ibrahim", "Hon. Ibrahim Mansour"]
    ),
    "PEP-05-0070": PEPProfile(
        pep_id="PEP-05-0070",
        full_name="Julia Santos",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #70",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Julia", "Hon. Julia Santos"]
    ),
    "PEP-05-0071": PEPProfile(
        pep_id="PEP-05-0071",
        full_name="Klaus Haddad",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #71",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Klaus", "Hon. Klaus Haddad"]
    ),
    "PEP-05-0072": PEPProfile(
        pep_id="PEP-05-0072",
        full_name="Lucia Morales",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #72",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Lucia", "Hon. Lucia Morales"]
    ),
    "PEP-05-0073": PEPProfile(
        pep_id="PEP-05-0073",
        full_name="Mateo Sterling",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #73",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Mateo", "Hon. Mateo Sterling"]
    ),
    "PEP-05-0074": PEPProfile(
        pep_id="PEP-05-0074",
        full_name="Nadia Volkov",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #74",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Nadia", "Hon. Nadia Volkov"]
    ),
    "PEP-05-0075": PEPProfile(
        pep_id="PEP-05-0075",
        full_name="Omar Silva",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #75",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Omar", "Hon. Omar Silva"]
    ),
    "PEP-05-0076": PEPProfile(
        pep_id="PEP-05-0076",
        full_name="Pradeep Chen",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #76",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Pradeep", "Hon. Pradeep Chen"]
    ),
    "PEP-05-0077": PEPProfile(
        pep_id="PEP-05-0077",
        full_name="Qasim Fernandez",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #77",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Qasim", "Hon. Qasim Fernandez"]
    ),
    "PEP-05-0078": PEPProfile(
        pep_id="PEP-05-0078",
        full_name="Rosa Patel",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #78",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Rosa", "Hon. Rosa Patel"]
    ),
    "PEP-05-0079": PEPProfile(
        pep_id="PEP-05-0079",
        full_name="Siddharth Reddy",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #79",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Siddharth", "Hon. Siddharth Reddy"]
    ),
    "PEP-05-0080": PEPProfile(
        pep_id="PEP-05-0080",
        full_name="Tariq Mercer",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #80",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Tariq", "Hon. Tariq Mercer"]
    ),
    "PEP-05-0081": PEPProfile(
        pep_id="PEP-05-0081",
        full_name="Arthur Schneider",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #81",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Arthur", "Hon. Arthur Schneider"]
    ),
    "PEP-05-0082": PEPProfile(
        pep_id="PEP-05-0082",
        full_name="Beatrice Lombardi",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #82",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Beatrice", "Hon. Beatrice Lombardi"]
    ),
    "PEP-05-0083": PEPProfile(
        pep_id="PEP-05-0083",
        full_name="Carlos Weber",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #83",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Carlos", "Hon. Carlos Weber"]
    ),
    "PEP-05-0084": PEPProfile(
        pep_id="PEP-05-0084",
        full_name="Dmitri Kovacs",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #84",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Dmitri", "Hon. Dmitri Kovacs"]
    ),
    "PEP-05-0085": PEPProfile(
        pep_id="PEP-05-0085",
        full_name="Elena Khan",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #85",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Elena", "Hon. Elena Khan"]
    ),
    "PEP-05-0086": PEPProfile(
        pep_id="PEP-05-0086",
        full_name="Fatima Rahman",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #86",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Fatima", "Hon. Fatima Rahman"]
    ),
    "PEP-05-0087": PEPProfile(
        pep_id="PEP-05-0087",
        full_name="Gabriel Vargas",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #87",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Gabriel", "Hon. Gabriel Vargas"]
    ),
    "PEP-05-0088": PEPProfile(
        pep_id="PEP-05-0088",
        full_name="Helena Al-Sayed",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #88",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Helena", "Hon. Helena Al-Sayed"]
    ),
    "PEP-05-0089": PEPProfile(
        pep_id="PEP-05-0089",
        full_name="Ibrahim Mansour",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #89",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Ibrahim", "Hon. Ibrahim Mansour"]
    ),
    "PEP-05-0090": PEPProfile(
        pep_id="PEP-05-0090",
        full_name="Julia Santos",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #90",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Julia", "Hon. Julia Santos"]
    ),
    "PEP-05-0091": PEPProfile(
        pep_id="PEP-05-0091",
        full_name="Klaus Haddad",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #91",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Klaus", "Hon. Klaus Haddad"]
    ),
    "PEP-05-0092": PEPProfile(
        pep_id="PEP-05-0092",
        full_name="Lucia Morales",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #92",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Lucia", "Hon. Lucia Morales"]
    ),
    "PEP-05-0093": PEPProfile(
        pep_id="PEP-05-0093",
        full_name="Mateo Sterling",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #93",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Mateo", "Hon. Mateo Sterling"]
    ),
    "PEP-05-0094": PEPProfile(
        pep_id="PEP-05-0094",
        full_name="Nadia Volkov",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #94",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Nadia", "Hon. Nadia Volkov"]
    ),
    "PEP-05-0095": PEPProfile(
        pep_id="PEP-05-0095",
        full_name="Omar Silva",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #95",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Omar", "Hon. Omar Silva"]
    ),
    "PEP-05-0096": PEPProfile(
        pep_id="PEP-05-0096",
        full_name="Pradeep Chen",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #96",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Pradeep", "Hon. Pradeep Chen"]
    ),
    "PEP-05-0097": PEPProfile(
        pep_id="PEP-05-0097",
        full_name="Qasim Fernandez",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #97",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Qasim", "Hon. Qasim Fernandez"]
    ),
    "PEP-05-0098": PEPProfile(
        pep_id="PEP-05-0098",
        full_name="Rosa Patel",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #98",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Rosa", "Hon. Rosa Patel"]
    ),
    "PEP-05-0099": PEPProfile(
        pep_id="PEP-05-0099",
        full_name="Siddharth Reddy",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #99",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Siddharth", "Hon. Siddharth Reddy"]
    ),
    "PEP-05-0100": PEPProfile(
        pep_id="PEP-05-0100",
        full_name="Tariq Mercer",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #100",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Tariq", "Hon. Tariq Mercer"]
    ),
    "PEP-05-0101": PEPProfile(
        pep_id="PEP-05-0101",
        full_name="Arthur Schneider",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #101",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Arthur", "Hon. Arthur Schneider"]
    ),
    "PEP-05-0102": PEPProfile(
        pep_id="PEP-05-0102",
        full_name="Beatrice Lombardi",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #102",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Beatrice", "Hon. Beatrice Lombardi"]
    ),
    "PEP-05-0103": PEPProfile(
        pep_id="PEP-05-0103",
        full_name="Carlos Weber",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #103",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Carlos", "Hon. Carlos Weber"]
    ),
    "PEP-05-0104": PEPProfile(
        pep_id="PEP-05-0104",
        full_name="Dmitri Kovacs",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #104",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Dmitri", "Hon. Dmitri Kovacs"]
    ),
    "PEP-05-0105": PEPProfile(
        pep_id="PEP-05-0105",
        full_name="Elena Khan",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #105",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Elena", "Hon. Elena Khan"]
    ),
    "PEP-05-0106": PEPProfile(
        pep_id="PEP-05-0106",
        full_name="Fatima Rahman",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #106",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Fatima", "Hon. Fatima Rahman"]
    ),
    "PEP-05-0107": PEPProfile(
        pep_id="PEP-05-0107",
        full_name="Gabriel Vargas",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #107",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Gabriel", "Hon. Gabriel Vargas"]
    ),
    "PEP-05-0108": PEPProfile(
        pep_id="PEP-05-0108",
        full_name="Helena Al-Sayed",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #108",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Helena", "Hon. Helena Al-Sayed"]
    ),
    "PEP-05-0109": PEPProfile(
        pep_id="PEP-05-0109",
        full_name="Ibrahim Mansour",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #109",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Ibrahim", "Hon. Ibrahim Mansour"]
    ),
    "PEP-05-0110": PEPProfile(
        pep_id="PEP-05-0110",
        full_name="Julia Santos",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #110",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Julia", "Hon. Julia Santos"]
    ),
    "PEP-05-0111": PEPProfile(
        pep_id="PEP-05-0111",
        full_name="Klaus Haddad",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #111",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Klaus", "Hon. Klaus Haddad"]
    ),
    "PEP-05-0112": PEPProfile(
        pep_id="PEP-05-0112",
        full_name="Lucia Morales",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #112",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Lucia", "Hon. Lucia Morales"]
    ),
    "PEP-05-0113": PEPProfile(
        pep_id="PEP-05-0113",
        full_name="Mateo Sterling",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #113",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Mateo", "Hon. Mateo Sterling"]
    ),
    "PEP-05-0114": PEPProfile(
        pep_id="PEP-05-0114",
        full_name="Nadia Volkov",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #114",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Nadia", "Hon. Nadia Volkov"]
    ),
    "PEP-05-0115": PEPProfile(
        pep_id="PEP-05-0115",
        full_name="Omar Silva",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #115",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Omar", "Hon. Omar Silva"]
    ),
    "PEP-05-0116": PEPProfile(
        pep_id="PEP-05-0116",
        full_name="Pradeep Chen",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #116",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Pradeep", "Hon. Pradeep Chen"]
    ),
    "PEP-05-0117": PEPProfile(
        pep_id="PEP-05-0117",
        full_name="Qasim Fernandez",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #117",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Qasim", "Hon. Qasim Fernandez"]
    ),
    "PEP-05-0118": PEPProfile(
        pep_id="PEP-05-0118",
        full_name="Rosa Patel",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #118",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Rosa", "Hon. Rosa Patel"]
    ),
    "PEP-05-0119": PEPProfile(
        pep_id="PEP-05-0119",
        full_name="Siddharth Reddy",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #119",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Siddharth", "Hon. Siddharth Reddy"]
    ),
    "PEP-05-0120": PEPProfile(
        pep_id="PEP-05-0120",
        full_name="Tariq Mercer",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #120",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Tariq", "Hon. Tariq Mercer"]
    ),
    "PEP-05-0121": PEPProfile(
        pep_id="PEP-05-0121",
        full_name="Arthur Schneider",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #121",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Arthur", "Hon. Arthur Schneider"]
    ),
    "PEP-05-0122": PEPProfile(
        pep_id="PEP-05-0122",
        full_name="Beatrice Lombardi",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #122",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Beatrice", "Hon. Beatrice Lombardi"]
    ),
    "PEP-05-0123": PEPProfile(
        pep_id="PEP-05-0123",
        full_name="Carlos Weber",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #123",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Carlos", "Hon. Carlos Weber"]
    ),
    "PEP-05-0124": PEPProfile(
        pep_id="PEP-05-0124",
        full_name="Dmitri Kovacs",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #124",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Dmitri", "Hon. Dmitri Kovacs"]
    ),
    "PEP-05-0125": PEPProfile(
        pep_id="PEP-05-0125",
        full_name="Elena Khan",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #125",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Elena", "Hon. Elena Khan"]
    ),
    "PEP-05-0126": PEPProfile(
        pep_id="PEP-05-0126",
        full_name="Fatima Rahman",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #126",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Fatima", "Hon. Fatima Rahman"]
    ),
    "PEP-05-0127": PEPProfile(
        pep_id="PEP-05-0127",
        full_name="Gabriel Vargas",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #127",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Gabriel", "Hon. Gabriel Vargas"]
    ),
    "PEP-05-0128": PEPProfile(
        pep_id="PEP-05-0128",
        full_name="Helena Al-Sayed",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #128",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Helena", "Hon. Helena Al-Sayed"]
    ),
    "PEP-05-0129": PEPProfile(
        pep_id="PEP-05-0129",
        full_name="Ibrahim Mansour",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #129",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Ibrahim", "Hon. Ibrahim Mansour"]
    ),
    "PEP-05-0130": PEPProfile(
        pep_id="PEP-05-0130",
        full_name="Julia Santos",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #130",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Julia", "Hon. Julia Santos"]
    ),
    "PEP-05-0131": PEPProfile(
        pep_id="PEP-05-0131",
        full_name="Klaus Haddad",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #131",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Klaus", "Hon. Klaus Haddad"]
    ),
    "PEP-05-0132": PEPProfile(
        pep_id="PEP-05-0132",
        full_name="Lucia Morales",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #132",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Lucia", "Hon. Lucia Morales"]
    ),
    "PEP-05-0133": PEPProfile(
        pep_id="PEP-05-0133",
        full_name="Mateo Sterling",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #133",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Mateo", "Hon. Mateo Sterling"]
    ),
    "PEP-05-0134": PEPProfile(
        pep_id="PEP-05-0134",
        full_name="Nadia Volkov",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #134",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Nadia", "Hon. Nadia Volkov"]
    ),
    "PEP-05-0135": PEPProfile(
        pep_id="PEP-05-0135",
        full_name="Omar Silva",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #135",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Omar", "Hon. Omar Silva"]
    ),
    "PEP-05-0136": PEPProfile(
        pep_id="PEP-05-0136",
        full_name="Pradeep Chen",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #136",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Pradeep", "Hon. Pradeep Chen"]
    ),
    "PEP-05-0137": PEPProfile(
        pep_id="PEP-05-0137",
        full_name="Qasim Fernandez",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #137",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Qasim", "Hon. Qasim Fernandez"]
    ),
    "PEP-05-0138": PEPProfile(
        pep_id="PEP-05-0138",
        full_name="Rosa Patel",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #138",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Rosa", "Hon. Rosa Patel"]
    ),
    "PEP-05-0139": PEPProfile(
        pep_id="PEP-05-0139",
        full_name="Siddharth Reddy",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #139",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Siddharth", "Hon. Siddharth Reddy"]
    ),
    "PEP-05-0140": PEPProfile(
        pep_id="PEP-05-0140",
        full_name="Tariq Mercer",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #140",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Tariq", "Hon. Tariq Mercer"]
    ),
    "PEP-05-0141": PEPProfile(
        pep_id="PEP-05-0141",
        full_name="Arthur Schneider",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #141",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Arthur", "Hon. Arthur Schneider"]
    ),
    "PEP-05-0142": PEPProfile(
        pep_id="PEP-05-0142",
        full_name="Beatrice Lombardi",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #142",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Beatrice", "Hon. Beatrice Lombardi"]
    ),
    "PEP-05-0143": PEPProfile(
        pep_id="PEP-05-0143",
        full_name="Carlos Weber",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #143",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Carlos", "Hon. Carlos Weber"]
    ),
    "PEP-05-0144": PEPProfile(
        pep_id="PEP-05-0144",
        full_name="Dmitri Kovacs",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #144",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Dmitri", "Hon. Dmitri Kovacs"]
    ),
    "PEP-05-0145": PEPProfile(
        pep_id="PEP-05-0145",
        full_name="Elena Khan",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #145",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Elena", "Hon. Elena Khan"]
    ),
    "PEP-05-0146": PEPProfile(
        pep_id="PEP-05-0146",
        full_name="Fatima Rahman",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #146",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Fatima", "Hon. Fatima Rahman"]
    ),
    "PEP-05-0147": PEPProfile(
        pep_id="PEP-05-0147",
        full_name="Gabriel Vargas",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #147",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Gabriel", "Hon. Gabriel Vargas"]
    ),
    "PEP-05-0148": PEPProfile(
        pep_id="PEP-05-0148",
        full_name="Helena Al-Sayed",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #148",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Helena", "Hon. Helena Al-Sayed"]
    ),
    "PEP-05-0149": PEPProfile(
        pep_id="PEP-05-0149",
        full_name="Ibrahim Mansour",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #149",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Ibrahim", "Hon. Ibrahim Mansour"]
    ),
    "PEP-05-0150": PEPProfile(
        pep_id="PEP-05-0150",
        full_name="Julia Santos",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #150",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Julia", "Hon. Julia Santos"]
    ),
    "PEP-05-0151": PEPProfile(
        pep_id="PEP-05-0151",
        full_name="Klaus Haddad",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #151",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Klaus", "Hon. Klaus Haddad"]
    ),
    "PEP-05-0152": PEPProfile(
        pep_id="PEP-05-0152",
        full_name="Lucia Morales",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #152",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Lucia", "Hon. Lucia Morales"]
    ),
    "PEP-05-0153": PEPProfile(
        pep_id="PEP-05-0153",
        full_name="Mateo Sterling",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #153",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Mateo", "Hon. Mateo Sterling"]
    ),
    "PEP-05-0154": PEPProfile(
        pep_id="PEP-05-0154",
        full_name="Nadia Volkov",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #154",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Nadia", "Hon. Nadia Volkov"]
    ),
    "PEP-05-0155": PEPProfile(
        pep_id="PEP-05-0155",
        full_name="Omar Silva",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #155",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Omar", "Hon. Omar Silva"]
    ),
    "PEP-05-0156": PEPProfile(
        pep_id="PEP-05-0156",
        full_name="Pradeep Chen",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #156",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Pradeep", "Hon. Pradeep Chen"]
    ),
    "PEP-05-0157": PEPProfile(
        pep_id="PEP-05-0157",
        full_name="Qasim Fernandez",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #157",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Qasim", "Hon. Qasim Fernandez"]
    ),
    "PEP-05-0158": PEPProfile(
        pep_id="PEP-05-0158",
        full_name="Rosa Patel",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #158",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Rosa", "Hon. Rosa Patel"]
    ),
    "PEP-05-0159": PEPProfile(
        pep_id="PEP-05-0159",
        full_name="Siddharth Reddy",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #159",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Siddharth", "Hon. Siddharth Reddy"]
    ),
    "PEP-05-0160": PEPProfile(
        pep_id="PEP-05-0160",
        full_name="Tariq Mercer",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #160",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Tariq", "Hon. Tariq Mercer"]
    ),
    "PEP-05-0161": PEPProfile(
        pep_id="PEP-05-0161",
        full_name="Arthur Schneider",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #161",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Arthur", "Hon. Arthur Schneider"]
    ),
    "PEP-05-0162": PEPProfile(
        pep_id="PEP-05-0162",
        full_name="Beatrice Lombardi",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #162",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Beatrice", "Hon. Beatrice Lombardi"]
    ),
    "PEP-05-0163": PEPProfile(
        pep_id="PEP-05-0163",
        full_name="Carlos Weber",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #163",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Carlos", "Hon. Carlos Weber"]
    ),
    "PEP-05-0164": PEPProfile(
        pep_id="PEP-05-0164",
        full_name="Dmitri Kovacs",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #164",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Dmitri", "Hon. Dmitri Kovacs"]
    ),
    "PEP-05-0165": PEPProfile(
        pep_id="PEP-05-0165",
        full_name="Elena Khan",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #165",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Elena", "Hon. Elena Khan"]
    ),
    "PEP-05-0166": PEPProfile(
        pep_id="PEP-05-0166",
        full_name="Fatima Rahman",
        country_code="CHE",
        country_name="Switzerland",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #166",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Fatima", "Hon. Fatima Rahman"]
    ),
    "PEP-05-0167": PEPProfile(
        pep_id="PEP-05-0167",
        full_name="Gabriel Vargas",
        country_code="SGP",
        country_name="Singapore",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #167",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Gabriel", "Hon. Gabriel Vargas"]
    ),
    "PEP-05-0168": PEPProfile(
        pep_id="PEP-05-0168",
        full_name="Helena Al-Sayed",
        country_code="HKG",
        country_name="Hong Kong",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #168",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Helena", "Hon. Helena Al-Sayed"]
    ),
    "PEP-05-0169": PEPProfile(
        pep_id="PEP-05-0169",
        full_name="Ibrahim Mansour",
        country_code="JPN",
        country_name="Japan",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #169",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Ibrahim", "Hon. Ibrahim Mansour"]
    ),
    "PEP-05-0170": PEPProfile(
        pep_id="PEP-05-0170",
        full_name="Julia Santos",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #170",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Julia", "Hon. Julia Santos"]
    ),
    "PEP-05-0171": PEPProfile(
        pep_id="PEP-05-0171",
        full_name="Klaus Haddad",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #171",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Klaus", "Hon. Klaus Haddad"]
    ),
    "PEP-05-0172": PEPProfile(
        pep_id="PEP-05-0172",
        full_name="Lucia Morales",
        country_code="BRA",
        country_name="Brazil",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #172",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Lucia", "Hon. Lucia Morales"]
    ),
    "PEP-05-0173": PEPProfile(
        pep_id="PEP-05-0173",
        full_name="Mateo Sterling",
        country_code="IND",
        country_name="India",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #173",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Mateo", "Hon. Mateo Sterling"]
    ),
    "PEP-05-0174": PEPProfile(
        pep_id="PEP-05-0174",
        full_name="Nadia Volkov",
        country_code="ZAF",
        country_name="South Africa",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #174",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Nadia", "Hon. Nadia Volkov"]
    ),
    "PEP-05-0175": PEPProfile(
        pep_id="PEP-05-0175",
        full_name="Omar Silva",
        country_code="AUS",
        country_name="Australia",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #175",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Omar", "Hon. Omar Silva"]
    ),
    "PEP-05-0176": PEPProfile(
        pep_id="PEP-05-0176",
        full_name="Pradeep Chen",
        country_code="CAN",
        country_name="Canada",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #176",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Pradeep", "Hon. Pradeep Chen"]
    ),
    "PEP-05-0177": PEPProfile(
        pep_id="PEP-05-0177",
        full_name="Qasim Fernandez",
        country_code="USA",
        country_name="United States",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #177",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Qasim", "Hon. Qasim Fernandez"]
    ),
    "PEP-05-0178": PEPProfile(
        pep_id="PEP-05-0178",
        full_name="Rosa Patel",
        country_code="GBR",
        country_name="United Kingdom",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #178",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Rosa", "Hon. Rosa Patel"]
    ),
    "PEP-05-0179": PEPProfile(
        pep_id="PEP-05-0179",
        full_name="Siddharth Reddy",
        country_code="DEU",
        country_name="Germany",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #179",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Siddharth", "Hon. Siddharth Reddy"]
    ),
    "PEP-05-0180": PEPProfile(
        pep_id="PEP-05-0180",
        full_name="Tariq Mercer",
        country_code="FRA",
        country_name="France",
        tier=2,
        role_title="Tier 2 Parliamentary & Senate Leaders Official #180",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=7.8,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Tariq", "Hon. Tariq Mercer"]
    ),
}
