"""
Tier 3 Regional Governors & RCAs.
Subnational Authorities & Relatives.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional

@dataclass
class PEPProfile:
    pep_id: str
    full_name: str
    country_code: str
    country_name: str
    tier: int
    role_title: str
    department_or_agency: str
    is_active: bool = True
    risk_score: float = 8.5
    source_of_wealth: Optional[str] = None
    aliases: List[str] = field(default_factory=list)

PEP_RECORDS_TIER3_REGIONAL_ASSOCIATES: Dict[str, PEPProfile] = {
    "PEP-08-0001": PEPProfile(
        pep_id="PEP-08-0001",
        full_name="Arthur Lombardi",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #1",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Arthur", "Hon. Arthur Lombardi"]
    ),
    "PEP-08-0002": PEPProfile(
        pep_id="PEP-08-0002",
        full_name="Beatrice Weber",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #2",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Beatrice", "Hon. Beatrice Weber"]
    ),
    "PEP-08-0003": PEPProfile(
        pep_id="PEP-08-0003",
        full_name="Carlos Kovacs",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #3",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Carlos", "Hon. Carlos Kovacs"]
    ),
    "PEP-08-0004": PEPProfile(
        pep_id="PEP-08-0004",
        full_name="Dmitri Khan",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #4",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Dmitri", "Hon. Dmitri Khan"]
    ),
    "PEP-08-0005": PEPProfile(
        pep_id="PEP-08-0005",
        full_name="Elena Rahman",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #5",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Elena", "Hon. Elena Rahman"]
    ),
    "PEP-08-0006": PEPProfile(
        pep_id="PEP-08-0006",
        full_name="Fatima Vargas",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #6",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Fatima", "Hon. Fatima Vargas"]
    ),
    "PEP-08-0007": PEPProfile(
        pep_id="PEP-08-0007",
        full_name="Gabriel Al-Sayed",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #7",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Gabriel", "Hon. Gabriel Al-Sayed"]
    ),
    "PEP-08-0008": PEPProfile(
        pep_id="PEP-08-0008",
        full_name="Helena Mansour",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #8",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Helena", "Hon. Helena Mansour"]
    ),
    "PEP-08-0009": PEPProfile(
        pep_id="PEP-08-0009",
        full_name="Ibrahim Santos",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #9",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Ibrahim", "Hon. Ibrahim Santos"]
    ),
    "PEP-08-0010": PEPProfile(
        pep_id="PEP-08-0010",
        full_name="Julia Haddad",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #10",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Julia", "Hon. Julia Haddad"]
    ),
    "PEP-08-0011": PEPProfile(
        pep_id="PEP-08-0011",
        full_name="Klaus Morales",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #11",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Klaus", "Hon. Klaus Morales"]
    ),
    "PEP-08-0012": PEPProfile(
        pep_id="PEP-08-0012",
        full_name="Lucia Sterling",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #12",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Lucia", "Hon. Lucia Sterling"]
    ),
    "PEP-08-0013": PEPProfile(
        pep_id="PEP-08-0013",
        full_name="Mateo Volkov",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #13",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Mateo", "Hon. Mateo Volkov"]
    ),
    "PEP-08-0014": PEPProfile(
        pep_id="PEP-08-0014",
        full_name="Nadia Silva",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #14",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Nadia", "Hon. Nadia Silva"]
    ),
    "PEP-08-0015": PEPProfile(
        pep_id="PEP-08-0015",
        full_name="Omar Chen",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #15",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Omar", "Hon. Omar Chen"]
    ),
    "PEP-08-0016": PEPProfile(
        pep_id="PEP-08-0016",
        full_name="Pradeep Fernandez",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #16",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Pradeep", "Hon. Pradeep Fernandez"]
    ),
    "PEP-08-0017": PEPProfile(
        pep_id="PEP-08-0017",
        full_name="Qasim Patel",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #17",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Qasim", "Hon. Qasim Patel"]
    ),
    "PEP-08-0018": PEPProfile(
        pep_id="PEP-08-0018",
        full_name="Rosa Reddy",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #18",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Rosa", "Hon. Rosa Reddy"]
    ),
    "PEP-08-0019": PEPProfile(
        pep_id="PEP-08-0019",
        full_name="Siddharth Mercer",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #19",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Siddharth", "Hon. Siddharth Mercer"]
    ),
    "PEP-08-0020": PEPProfile(
        pep_id="PEP-08-0020",
        full_name="Tariq Schneider",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #20",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Tariq", "Hon. Tariq Schneider"]
    ),
    "PEP-08-0021": PEPProfile(
        pep_id="PEP-08-0021",
        full_name="Arthur Lombardi",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #21",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Arthur", "Hon. Arthur Lombardi"]
    ),
    "PEP-08-0022": PEPProfile(
        pep_id="PEP-08-0022",
        full_name="Beatrice Weber",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #22",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Beatrice", "Hon. Beatrice Weber"]
    ),
    "PEP-08-0023": PEPProfile(
        pep_id="PEP-08-0023",
        full_name="Carlos Kovacs",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #23",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Carlos", "Hon. Carlos Kovacs"]
    ),
    "PEP-08-0024": PEPProfile(
        pep_id="PEP-08-0024",
        full_name="Dmitri Khan",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #24",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Dmitri", "Hon. Dmitri Khan"]
    ),
    "PEP-08-0025": PEPProfile(
        pep_id="PEP-08-0025",
        full_name="Elena Rahman",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #25",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Elena", "Hon. Elena Rahman"]
    ),
    "PEP-08-0026": PEPProfile(
        pep_id="PEP-08-0026",
        full_name="Fatima Vargas",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #26",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Fatima", "Hon. Fatima Vargas"]
    ),
    "PEP-08-0027": PEPProfile(
        pep_id="PEP-08-0027",
        full_name="Gabriel Al-Sayed",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #27",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Gabriel", "Hon. Gabriel Al-Sayed"]
    ),
    "PEP-08-0028": PEPProfile(
        pep_id="PEP-08-0028",
        full_name="Helena Mansour",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #28",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Helena", "Hon. Helena Mansour"]
    ),
    "PEP-08-0029": PEPProfile(
        pep_id="PEP-08-0029",
        full_name="Ibrahim Santos",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #29",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Ibrahim", "Hon. Ibrahim Santos"]
    ),
    "PEP-08-0030": PEPProfile(
        pep_id="PEP-08-0030",
        full_name="Julia Haddad",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #30",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Julia", "Hon. Julia Haddad"]
    ),
    "PEP-08-0031": PEPProfile(
        pep_id="PEP-08-0031",
        full_name="Klaus Morales",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #31",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Klaus", "Hon. Klaus Morales"]
    ),
    "PEP-08-0032": PEPProfile(
        pep_id="PEP-08-0032",
        full_name="Lucia Sterling",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #32",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Lucia", "Hon. Lucia Sterling"]
    ),
    "PEP-08-0033": PEPProfile(
        pep_id="PEP-08-0033",
        full_name="Mateo Volkov",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #33",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Mateo", "Hon. Mateo Volkov"]
    ),
    "PEP-08-0034": PEPProfile(
        pep_id="PEP-08-0034",
        full_name="Nadia Silva",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #34",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Nadia", "Hon. Nadia Silva"]
    ),
    "PEP-08-0035": PEPProfile(
        pep_id="PEP-08-0035",
        full_name="Omar Chen",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #35",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Omar", "Hon. Omar Chen"]
    ),
    "PEP-08-0036": PEPProfile(
        pep_id="PEP-08-0036",
        full_name="Pradeep Fernandez",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #36",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Pradeep", "Hon. Pradeep Fernandez"]
    ),
    "PEP-08-0037": PEPProfile(
        pep_id="PEP-08-0037",
        full_name="Qasim Patel",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #37",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Qasim", "Hon. Qasim Patel"]
    ),
    "PEP-08-0038": PEPProfile(
        pep_id="PEP-08-0038",
        full_name="Rosa Reddy",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #38",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Rosa", "Hon. Rosa Reddy"]
    ),
    "PEP-08-0039": PEPProfile(
        pep_id="PEP-08-0039",
        full_name="Siddharth Mercer",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #39",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Siddharth", "Hon. Siddharth Mercer"]
    ),
    "PEP-08-0040": PEPProfile(
        pep_id="PEP-08-0040",
        full_name="Tariq Schneider",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #40",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Tariq", "Hon. Tariq Schneider"]
    ),
    "PEP-08-0041": PEPProfile(
        pep_id="PEP-08-0041",
        full_name="Arthur Lombardi",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #41",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Arthur", "Hon. Arthur Lombardi"]
    ),
    "PEP-08-0042": PEPProfile(
        pep_id="PEP-08-0042",
        full_name="Beatrice Weber",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #42",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Beatrice", "Hon. Beatrice Weber"]
    ),
    "PEP-08-0043": PEPProfile(
        pep_id="PEP-08-0043",
        full_name="Carlos Kovacs",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #43",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Carlos", "Hon. Carlos Kovacs"]
    ),
    "PEP-08-0044": PEPProfile(
        pep_id="PEP-08-0044",
        full_name="Dmitri Khan",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #44",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Dmitri", "Hon. Dmitri Khan"]
    ),
    "PEP-08-0045": PEPProfile(
        pep_id="PEP-08-0045",
        full_name="Elena Rahman",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #45",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Elena", "Hon. Elena Rahman"]
    ),
    "PEP-08-0046": PEPProfile(
        pep_id="PEP-08-0046",
        full_name="Fatima Vargas",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #46",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Fatima", "Hon. Fatima Vargas"]
    ),
    "PEP-08-0047": PEPProfile(
        pep_id="PEP-08-0047",
        full_name="Gabriel Al-Sayed",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #47",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Gabriel", "Hon. Gabriel Al-Sayed"]
    ),
    "PEP-08-0048": PEPProfile(
        pep_id="PEP-08-0048",
        full_name="Helena Mansour",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #48",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Helena", "Hon. Helena Mansour"]
    ),
    "PEP-08-0049": PEPProfile(
        pep_id="PEP-08-0049",
        full_name="Ibrahim Santos",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #49",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Ibrahim", "Hon. Ibrahim Santos"]
    ),
    "PEP-08-0050": PEPProfile(
        pep_id="PEP-08-0050",
        full_name="Julia Haddad",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #50",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Julia", "Hon. Julia Haddad"]
    ),
    "PEP-08-0051": PEPProfile(
        pep_id="PEP-08-0051",
        full_name="Klaus Morales",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #51",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Klaus", "Hon. Klaus Morales"]
    ),
    "PEP-08-0052": PEPProfile(
        pep_id="PEP-08-0052",
        full_name="Lucia Sterling",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #52",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Lucia", "Hon. Lucia Sterling"]
    ),
    "PEP-08-0053": PEPProfile(
        pep_id="PEP-08-0053",
        full_name="Mateo Volkov",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #53",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Mateo", "Hon. Mateo Volkov"]
    ),
    "PEP-08-0054": PEPProfile(
        pep_id="PEP-08-0054",
        full_name="Nadia Silva",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #54",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Nadia", "Hon. Nadia Silva"]
    ),
    "PEP-08-0055": PEPProfile(
        pep_id="PEP-08-0055",
        full_name="Omar Chen",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #55",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Omar", "Hon. Omar Chen"]
    ),
    "PEP-08-0056": PEPProfile(
        pep_id="PEP-08-0056",
        full_name="Pradeep Fernandez",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #56",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Pradeep", "Hon. Pradeep Fernandez"]
    ),
    "PEP-08-0057": PEPProfile(
        pep_id="PEP-08-0057",
        full_name="Qasim Patel",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #57",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Qasim", "Hon. Qasim Patel"]
    ),
    "PEP-08-0058": PEPProfile(
        pep_id="PEP-08-0058",
        full_name="Rosa Reddy",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #58",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Rosa", "Hon. Rosa Reddy"]
    ),
    "PEP-08-0059": PEPProfile(
        pep_id="PEP-08-0059",
        full_name="Siddharth Mercer",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #59",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Siddharth", "Hon. Siddharth Mercer"]
    ),
    "PEP-08-0060": PEPProfile(
        pep_id="PEP-08-0060",
        full_name="Tariq Schneider",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #60",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Tariq", "Hon. Tariq Schneider"]
    ),
    "PEP-08-0061": PEPProfile(
        pep_id="PEP-08-0061",
        full_name="Arthur Lombardi",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #61",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Arthur", "Hon. Arthur Lombardi"]
    ),
    "PEP-08-0062": PEPProfile(
        pep_id="PEP-08-0062",
        full_name="Beatrice Weber",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #62",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Beatrice", "Hon. Beatrice Weber"]
    ),
    "PEP-08-0063": PEPProfile(
        pep_id="PEP-08-0063",
        full_name="Carlos Kovacs",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #63",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Carlos", "Hon. Carlos Kovacs"]
    ),
    "PEP-08-0064": PEPProfile(
        pep_id="PEP-08-0064",
        full_name="Dmitri Khan",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #64",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Dmitri", "Hon. Dmitri Khan"]
    ),
    "PEP-08-0065": PEPProfile(
        pep_id="PEP-08-0065",
        full_name="Elena Rahman",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #65",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Elena", "Hon. Elena Rahman"]
    ),
    "PEP-08-0066": PEPProfile(
        pep_id="PEP-08-0066",
        full_name="Fatima Vargas",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #66",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Fatima", "Hon. Fatima Vargas"]
    ),
    "PEP-08-0067": PEPProfile(
        pep_id="PEP-08-0067",
        full_name="Gabriel Al-Sayed",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #67",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Gabriel", "Hon. Gabriel Al-Sayed"]
    ),
    "PEP-08-0068": PEPProfile(
        pep_id="PEP-08-0068",
        full_name="Helena Mansour",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #68",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Helena", "Hon. Helena Mansour"]
    ),
    "PEP-08-0069": PEPProfile(
        pep_id="PEP-08-0069",
        full_name="Ibrahim Santos",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #69",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Ibrahim", "Hon. Ibrahim Santos"]
    ),
    "PEP-08-0070": PEPProfile(
        pep_id="PEP-08-0070",
        full_name="Julia Haddad",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #70",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Julia", "Hon. Julia Haddad"]
    ),
    "PEP-08-0071": PEPProfile(
        pep_id="PEP-08-0071",
        full_name="Klaus Morales",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #71",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Klaus", "Hon. Klaus Morales"]
    ),
    "PEP-08-0072": PEPProfile(
        pep_id="PEP-08-0072",
        full_name="Lucia Sterling",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #72",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Lucia", "Hon. Lucia Sterling"]
    ),
    "PEP-08-0073": PEPProfile(
        pep_id="PEP-08-0073",
        full_name="Mateo Volkov",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #73",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Mateo", "Hon. Mateo Volkov"]
    ),
    "PEP-08-0074": PEPProfile(
        pep_id="PEP-08-0074",
        full_name="Nadia Silva",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #74",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Nadia", "Hon. Nadia Silva"]
    ),
    "PEP-08-0075": PEPProfile(
        pep_id="PEP-08-0075",
        full_name="Omar Chen",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #75",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Omar", "Hon. Omar Chen"]
    ),
    "PEP-08-0076": PEPProfile(
        pep_id="PEP-08-0076",
        full_name="Pradeep Fernandez",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #76",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Pradeep", "Hon. Pradeep Fernandez"]
    ),
    "PEP-08-0077": PEPProfile(
        pep_id="PEP-08-0077",
        full_name="Qasim Patel",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #77",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Qasim", "Hon. Qasim Patel"]
    ),
    "PEP-08-0078": PEPProfile(
        pep_id="PEP-08-0078",
        full_name="Rosa Reddy",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #78",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Rosa", "Hon. Rosa Reddy"]
    ),
    "PEP-08-0079": PEPProfile(
        pep_id="PEP-08-0079",
        full_name="Siddharth Mercer",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #79",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Siddharth", "Hon. Siddharth Mercer"]
    ),
    "PEP-08-0080": PEPProfile(
        pep_id="PEP-08-0080",
        full_name="Tariq Schneider",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #80",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Tariq", "Hon. Tariq Schneider"]
    ),
    "PEP-08-0081": PEPProfile(
        pep_id="PEP-08-0081",
        full_name="Arthur Lombardi",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #81",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Arthur", "Hon. Arthur Lombardi"]
    ),
    "PEP-08-0082": PEPProfile(
        pep_id="PEP-08-0082",
        full_name="Beatrice Weber",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #82",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Beatrice", "Hon. Beatrice Weber"]
    ),
    "PEP-08-0083": PEPProfile(
        pep_id="PEP-08-0083",
        full_name="Carlos Kovacs",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #83",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Carlos", "Hon. Carlos Kovacs"]
    ),
    "PEP-08-0084": PEPProfile(
        pep_id="PEP-08-0084",
        full_name="Dmitri Khan",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #84",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Dmitri", "Hon. Dmitri Khan"]
    ),
    "PEP-08-0085": PEPProfile(
        pep_id="PEP-08-0085",
        full_name="Elena Rahman",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #85",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Elena", "Hon. Elena Rahman"]
    ),
    "PEP-08-0086": PEPProfile(
        pep_id="PEP-08-0086",
        full_name="Fatima Vargas",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #86",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Fatima", "Hon. Fatima Vargas"]
    ),
    "PEP-08-0087": PEPProfile(
        pep_id="PEP-08-0087",
        full_name="Gabriel Al-Sayed",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #87",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Gabriel", "Hon. Gabriel Al-Sayed"]
    ),
    "PEP-08-0088": PEPProfile(
        pep_id="PEP-08-0088",
        full_name="Helena Mansour",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #88",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Helena", "Hon. Helena Mansour"]
    ),
    "PEP-08-0089": PEPProfile(
        pep_id="PEP-08-0089",
        full_name="Ibrahim Santos",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #89",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Ibrahim", "Hon. Ibrahim Santos"]
    ),
    "PEP-08-0090": PEPProfile(
        pep_id="PEP-08-0090",
        full_name="Julia Haddad",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #90",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Julia", "Hon. Julia Haddad"]
    ),
    "PEP-08-0091": PEPProfile(
        pep_id="PEP-08-0091",
        full_name="Klaus Morales",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #91",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Klaus", "Hon. Klaus Morales"]
    ),
    "PEP-08-0092": PEPProfile(
        pep_id="PEP-08-0092",
        full_name="Lucia Sterling",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #92",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Lucia", "Hon. Lucia Sterling"]
    ),
    "PEP-08-0093": PEPProfile(
        pep_id="PEP-08-0093",
        full_name="Mateo Volkov",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #93",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Mateo", "Hon. Mateo Volkov"]
    ),
    "PEP-08-0094": PEPProfile(
        pep_id="PEP-08-0094",
        full_name="Nadia Silva",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #94",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Nadia", "Hon. Nadia Silva"]
    ),
    "PEP-08-0095": PEPProfile(
        pep_id="PEP-08-0095",
        full_name="Omar Chen",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #95",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Omar", "Hon. Omar Chen"]
    ),
    "PEP-08-0096": PEPProfile(
        pep_id="PEP-08-0096",
        full_name="Pradeep Fernandez",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #96",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Pradeep", "Hon. Pradeep Fernandez"]
    ),
    "PEP-08-0097": PEPProfile(
        pep_id="PEP-08-0097",
        full_name="Qasim Patel",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #97",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Qasim", "Hon. Qasim Patel"]
    ),
    "PEP-08-0098": PEPProfile(
        pep_id="PEP-08-0098",
        full_name="Rosa Reddy",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #98",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Rosa", "Hon. Rosa Reddy"]
    ),
    "PEP-08-0099": PEPProfile(
        pep_id="PEP-08-0099",
        full_name="Siddharth Mercer",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #99",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Siddharth", "Hon. Siddharth Mercer"]
    ),
    "PEP-08-0100": PEPProfile(
        pep_id="PEP-08-0100",
        full_name="Tariq Schneider",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #100",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Tariq", "Hon. Tariq Schneider"]
    ),
    "PEP-08-0101": PEPProfile(
        pep_id="PEP-08-0101",
        full_name="Arthur Lombardi",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #101",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Arthur", "Hon. Arthur Lombardi"]
    ),
    "PEP-08-0102": PEPProfile(
        pep_id="PEP-08-0102",
        full_name="Beatrice Weber",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #102",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Beatrice", "Hon. Beatrice Weber"]
    ),
    "PEP-08-0103": PEPProfile(
        pep_id="PEP-08-0103",
        full_name="Carlos Kovacs",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #103",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Carlos", "Hon. Carlos Kovacs"]
    ),
    "PEP-08-0104": PEPProfile(
        pep_id="PEP-08-0104",
        full_name="Dmitri Khan",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #104",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Dmitri", "Hon. Dmitri Khan"]
    ),
    "PEP-08-0105": PEPProfile(
        pep_id="PEP-08-0105",
        full_name="Elena Rahman",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #105",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Elena", "Hon. Elena Rahman"]
    ),
    "PEP-08-0106": PEPProfile(
        pep_id="PEP-08-0106",
        full_name="Fatima Vargas",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #106",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Fatima", "Hon. Fatima Vargas"]
    ),
    "PEP-08-0107": PEPProfile(
        pep_id="PEP-08-0107",
        full_name="Gabriel Al-Sayed",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #107",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Gabriel", "Hon. Gabriel Al-Sayed"]
    ),
    "PEP-08-0108": PEPProfile(
        pep_id="PEP-08-0108",
        full_name="Helena Mansour",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #108",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Helena", "Hon. Helena Mansour"]
    ),
    "PEP-08-0109": PEPProfile(
        pep_id="PEP-08-0109",
        full_name="Ibrahim Santos",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #109",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Ibrahim", "Hon. Ibrahim Santos"]
    ),
    "PEP-08-0110": PEPProfile(
        pep_id="PEP-08-0110",
        full_name="Julia Haddad",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #110",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Julia", "Hon. Julia Haddad"]
    ),
    "PEP-08-0111": PEPProfile(
        pep_id="PEP-08-0111",
        full_name="Klaus Morales",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #111",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Klaus", "Hon. Klaus Morales"]
    ),
    "PEP-08-0112": PEPProfile(
        pep_id="PEP-08-0112",
        full_name="Lucia Sterling",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #112",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Lucia", "Hon. Lucia Sterling"]
    ),
    "PEP-08-0113": PEPProfile(
        pep_id="PEP-08-0113",
        full_name="Mateo Volkov",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #113",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Mateo", "Hon. Mateo Volkov"]
    ),
    "PEP-08-0114": PEPProfile(
        pep_id="PEP-08-0114",
        full_name="Nadia Silva",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #114",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Nadia", "Hon. Nadia Silva"]
    ),
    "PEP-08-0115": PEPProfile(
        pep_id="PEP-08-0115",
        full_name="Omar Chen",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #115",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Omar", "Hon. Omar Chen"]
    ),
    "PEP-08-0116": PEPProfile(
        pep_id="PEP-08-0116",
        full_name="Pradeep Fernandez",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #116",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Pradeep", "Hon. Pradeep Fernandez"]
    ),
    "PEP-08-0117": PEPProfile(
        pep_id="PEP-08-0117",
        full_name="Qasim Patel",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #117",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Qasim", "Hon. Qasim Patel"]
    ),
    "PEP-08-0118": PEPProfile(
        pep_id="PEP-08-0118",
        full_name="Rosa Reddy",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #118",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Rosa", "Hon. Rosa Reddy"]
    ),
    "PEP-08-0119": PEPProfile(
        pep_id="PEP-08-0119",
        full_name="Siddharth Mercer",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #119",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Siddharth", "Hon. Siddharth Mercer"]
    ),
    "PEP-08-0120": PEPProfile(
        pep_id="PEP-08-0120",
        full_name="Tariq Schneider",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #120",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Tariq", "Hon. Tariq Schneider"]
    ),
    "PEP-08-0121": PEPProfile(
        pep_id="PEP-08-0121",
        full_name="Arthur Lombardi",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #121",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Arthur", "Hon. Arthur Lombardi"]
    ),
    "PEP-08-0122": PEPProfile(
        pep_id="PEP-08-0122",
        full_name="Beatrice Weber",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #122",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Beatrice", "Hon. Beatrice Weber"]
    ),
    "PEP-08-0123": PEPProfile(
        pep_id="PEP-08-0123",
        full_name="Carlos Kovacs",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #123",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Carlos", "Hon. Carlos Kovacs"]
    ),
    "PEP-08-0124": PEPProfile(
        pep_id="PEP-08-0124",
        full_name="Dmitri Khan",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #124",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Dmitri", "Hon. Dmitri Khan"]
    ),
    "PEP-08-0125": PEPProfile(
        pep_id="PEP-08-0125",
        full_name="Elena Rahman",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #125",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Elena", "Hon. Elena Rahman"]
    ),
    "PEP-08-0126": PEPProfile(
        pep_id="PEP-08-0126",
        full_name="Fatima Vargas",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #126",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Fatima", "Hon. Fatima Vargas"]
    ),
    "PEP-08-0127": PEPProfile(
        pep_id="PEP-08-0127",
        full_name="Gabriel Al-Sayed",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #127",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Gabriel", "Hon. Gabriel Al-Sayed"]
    ),
    "PEP-08-0128": PEPProfile(
        pep_id="PEP-08-0128",
        full_name="Helena Mansour",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #128",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Helena", "Hon. Helena Mansour"]
    ),
    "PEP-08-0129": PEPProfile(
        pep_id="PEP-08-0129",
        full_name="Ibrahim Santos",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #129",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Ibrahim", "Hon. Ibrahim Santos"]
    ),
    "PEP-08-0130": PEPProfile(
        pep_id="PEP-08-0130",
        full_name="Julia Haddad",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #130",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Julia", "Hon. Julia Haddad"]
    ),
    "PEP-08-0131": PEPProfile(
        pep_id="PEP-08-0131",
        full_name="Klaus Morales",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #131",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Klaus", "Hon. Klaus Morales"]
    ),
    "PEP-08-0132": PEPProfile(
        pep_id="PEP-08-0132",
        full_name="Lucia Sterling",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #132",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Lucia", "Hon. Lucia Sterling"]
    ),
    "PEP-08-0133": PEPProfile(
        pep_id="PEP-08-0133",
        full_name="Mateo Volkov",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #133",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Mateo", "Hon. Mateo Volkov"]
    ),
    "PEP-08-0134": PEPProfile(
        pep_id="PEP-08-0134",
        full_name="Nadia Silva",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #134",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Nadia", "Hon. Nadia Silva"]
    ),
    "PEP-08-0135": PEPProfile(
        pep_id="PEP-08-0135",
        full_name="Omar Chen",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #135",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Omar", "Hon. Omar Chen"]
    ),
    "PEP-08-0136": PEPProfile(
        pep_id="PEP-08-0136",
        full_name="Pradeep Fernandez",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #136",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Pradeep", "Hon. Pradeep Fernandez"]
    ),
    "PEP-08-0137": PEPProfile(
        pep_id="PEP-08-0137",
        full_name="Qasim Patel",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #137",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Qasim", "Hon. Qasim Patel"]
    ),
    "PEP-08-0138": PEPProfile(
        pep_id="PEP-08-0138",
        full_name="Rosa Reddy",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #138",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Rosa", "Hon. Rosa Reddy"]
    ),
    "PEP-08-0139": PEPProfile(
        pep_id="PEP-08-0139",
        full_name="Siddharth Mercer",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #139",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Siddharth", "Hon. Siddharth Mercer"]
    ),
    "PEP-08-0140": PEPProfile(
        pep_id="PEP-08-0140",
        full_name="Tariq Schneider",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #140",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Tariq", "Hon. Tariq Schneider"]
    ),
    "PEP-08-0141": PEPProfile(
        pep_id="PEP-08-0141",
        full_name="Arthur Lombardi",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #141",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Arthur", "Hon. Arthur Lombardi"]
    ),
    "PEP-08-0142": PEPProfile(
        pep_id="PEP-08-0142",
        full_name="Beatrice Weber",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #142",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Beatrice", "Hon. Beatrice Weber"]
    ),
    "PEP-08-0143": PEPProfile(
        pep_id="PEP-08-0143",
        full_name="Carlos Kovacs",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #143",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Carlos", "Hon. Carlos Kovacs"]
    ),
    "PEP-08-0144": PEPProfile(
        pep_id="PEP-08-0144",
        full_name="Dmitri Khan",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #144",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Dmitri", "Hon. Dmitri Khan"]
    ),
    "PEP-08-0145": PEPProfile(
        pep_id="PEP-08-0145",
        full_name="Elena Rahman",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #145",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Elena", "Hon. Elena Rahman"]
    ),
    "PEP-08-0146": PEPProfile(
        pep_id="PEP-08-0146",
        full_name="Fatima Vargas",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #146",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Fatima", "Hon. Fatima Vargas"]
    ),
    "PEP-08-0147": PEPProfile(
        pep_id="PEP-08-0147",
        full_name="Gabriel Al-Sayed",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #147",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Gabriel", "Hon. Gabriel Al-Sayed"]
    ),
    "PEP-08-0148": PEPProfile(
        pep_id="PEP-08-0148",
        full_name="Helena Mansour",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #148",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Helena", "Hon. Helena Mansour"]
    ),
    "PEP-08-0149": PEPProfile(
        pep_id="PEP-08-0149",
        full_name="Ibrahim Santos",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #149",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Ibrahim", "Hon. Ibrahim Santos"]
    ),
    "PEP-08-0150": PEPProfile(
        pep_id="PEP-08-0150",
        full_name="Julia Haddad",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #150",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Julia", "Hon. Julia Haddad"]
    ),
    "PEP-08-0151": PEPProfile(
        pep_id="PEP-08-0151",
        full_name="Klaus Morales",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #151",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Klaus", "Hon. Klaus Morales"]
    ),
    "PEP-08-0152": PEPProfile(
        pep_id="PEP-08-0152",
        full_name="Lucia Sterling",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #152",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Lucia", "Hon. Lucia Sterling"]
    ),
    "PEP-08-0153": PEPProfile(
        pep_id="PEP-08-0153",
        full_name="Mateo Volkov",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #153",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Mateo", "Hon. Mateo Volkov"]
    ),
    "PEP-08-0154": PEPProfile(
        pep_id="PEP-08-0154",
        full_name="Nadia Silva",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #154",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Nadia", "Hon. Nadia Silva"]
    ),
    "PEP-08-0155": PEPProfile(
        pep_id="PEP-08-0155",
        full_name="Omar Chen",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #155",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Omar", "Hon. Omar Chen"]
    ),
    "PEP-08-0156": PEPProfile(
        pep_id="PEP-08-0156",
        full_name="Pradeep Fernandez",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #156",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Pradeep", "Hon. Pradeep Fernandez"]
    ),
    "PEP-08-0157": PEPProfile(
        pep_id="PEP-08-0157",
        full_name="Qasim Patel",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #157",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Qasim", "Hon. Qasim Patel"]
    ),
    "PEP-08-0158": PEPProfile(
        pep_id="PEP-08-0158",
        full_name="Rosa Reddy",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #158",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Rosa", "Hon. Rosa Reddy"]
    ),
    "PEP-08-0159": PEPProfile(
        pep_id="PEP-08-0159",
        full_name="Siddharth Mercer",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #159",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Siddharth", "Hon. Siddharth Mercer"]
    ),
    "PEP-08-0160": PEPProfile(
        pep_id="PEP-08-0160",
        full_name="Tariq Schneider",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #160",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Tariq", "Hon. Tariq Schneider"]
    ),
    "PEP-08-0161": PEPProfile(
        pep_id="PEP-08-0161",
        full_name="Arthur Lombardi",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #161",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Lombardi, Arthur", "Hon. Arthur Lombardi"]
    ),
    "PEP-08-0162": PEPProfile(
        pep_id="PEP-08-0162",
        full_name="Beatrice Weber",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #162",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Weber, Beatrice", "Hon. Beatrice Weber"]
    ),
    "PEP-08-0163": PEPProfile(
        pep_id="PEP-08-0163",
        full_name="Carlos Kovacs",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #163",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Kovacs, Carlos", "Hon. Carlos Kovacs"]
    ),
    "PEP-08-0164": PEPProfile(
        pep_id="PEP-08-0164",
        full_name="Dmitri Khan",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #164",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Khan, Dmitri", "Hon. Dmitri Khan"]
    ),
    "PEP-08-0165": PEPProfile(
        pep_id="PEP-08-0165",
        full_name="Elena Rahman",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #165",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Rahman, Elena", "Hon. Elena Rahman"]
    ),
    "PEP-08-0166": PEPProfile(
        pep_id="PEP-08-0166",
        full_name="Fatima Vargas",
        country_code="JPN",
        country_name="Japan",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #166",
        department_or_agency="Japan Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Vargas, Fatima", "Hon. Fatima Vargas"]
    ),
    "PEP-08-0167": PEPProfile(
        pep_id="PEP-08-0167",
        full_name="Gabriel Al-Sayed",
        country_code="ARE",
        country_name="United Arab Emirates",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #167",
        department_or_agency="United Arab Emirates Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Al-Sayed, Gabriel", "Hon. Gabriel Al-Sayed"]
    ),
    "PEP-08-0168": PEPProfile(
        pep_id="PEP-08-0168",
        full_name="Helena Mansour",
        country_code="SAU",
        country_name="Saudi Arabia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #168",
        department_or_agency="Saudi Arabia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mansour, Helena", "Hon. Helena Mansour"]
    ),
    "PEP-08-0169": PEPProfile(
        pep_id="PEP-08-0169",
        full_name="Ibrahim Santos",
        country_code="BRA",
        country_name="Brazil",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #169",
        department_or_agency="Brazil Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Santos, Ibrahim", "Hon. Ibrahim Santos"]
    ),
    "PEP-08-0170": PEPProfile(
        pep_id="PEP-08-0170",
        full_name="Julia Haddad",
        country_code="IND",
        country_name="India",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #170",
        department_or_agency="India Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Haddad, Julia", "Hon. Julia Haddad"]
    ),
    "PEP-08-0171": PEPProfile(
        pep_id="PEP-08-0171",
        full_name="Klaus Morales",
        country_code="ZAF",
        country_name="South Africa",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #171",
        department_or_agency="South Africa Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Morales, Klaus", "Hon. Klaus Morales"]
    ),
    "PEP-08-0172": PEPProfile(
        pep_id="PEP-08-0172",
        full_name="Lucia Sterling",
        country_code="AUS",
        country_name="Australia",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #172",
        department_or_agency="Australia Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Sterling, Lucia", "Hon. Lucia Sterling"]
    ),
    "PEP-08-0173": PEPProfile(
        pep_id="PEP-08-0173",
        full_name="Mateo Volkov",
        country_code="CAN",
        country_name="Canada",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #173",
        department_or_agency="Canada Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Volkov, Mateo", "Hon. Mateo Volkov"]
    ),
    "PEP-08-0174": PEPProfile(
        pep_id="PEP-08-0174",
        full_name="Nadia Silva",
        country_code="USA",
        country_name="United States",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #174",
        department_or_agency="United States Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Silva, Nadia", "Hon. Nadia Silva"]
    ),
    "PEP-08-0175": PEPProfile(
        pep_id="PEP-08-0175",
        full_name="Omar Chen",
        country_code="GBR",
        country_name="United Kingdom",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #175",
        department_or_agency="United Kingdom Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Chen, Omar", "Hon. Omar Chen"]
    ),
    "PEP-08-0176": PEPProfile(
        pep_id="PEP-08-0176",
        full_name="Pradeep Fernandez",
        country_code="DEU",
        country_name="Germany",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #176",
        department_or_agency="Germany Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Fernandez, Pradeep", "Hon. Pradeep Fernandez"]
    ),
    "PEP-08-0177": PEPProfile(
        pep_id="PEP-08-0177",
        full_name="Qasim Patel",
        country_code="FRA",
        country_name="France",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #177",
        department_or_agency="France Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Patel, Qasim", "Hon. Qasim Patel"]
    ),
    "PEP-08-0178": PEPProfile(
        pep_id="PEP-08-0178",
        full_name="Rosa Reddy",
        country_code="CHE",
        country_name="Switzerland",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #178",
        department_or_agency="Switzerland Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Reddy, Rosa", "Hon. Rosa Reddy"]
    ),
    "PEP-08-0179": PEPProfile(
        pep_id="PEP-08-0179",
        full_name="Siddharth Mercer",
        country_code="SGP",
        country_name="Singapore",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #179",
        department_or_agency="Singapore Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Mercer, Siddharth", "Hon. Siddharth Mercer"]
    ),
    "PEP-08-0180": PEPProfile(
        pep_id="PEP-08-0180",
        full_name="Tariq Schneider",
        country_code="HKG",
        country_name="Hong Kong",
        tier=3,
        role_title="Tier 3 Regional Governors & RCAs Official #180",
        department_or_agency="Hong Kong Ministry of State",
        is_active=True,
        risk_score=6.2,
        source_of_wealth="Government Compensation & Family Estates",
        aliases=["Schneider, Tariq", "Hon. Tariq Schneider"]
    ),
}
