"""
FATF Country Risk & Jurisdictional AML Assessment Database.
Evaluates Basel AML index, FATF High-Risk status, CPI, offshore tax havens, and sanctions regimes.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

@dataclass
class CountryRiskProfile:
    iso2: str
    iso3: str
    country_name: str
    region: str
    basel_aml_index: float  # 0.0 to 10.0 scale (higher = riskier)
    fatf_status: str  # COMPLIANT, INCREASED_MONITORING, CALL_FOR_ACTION_BLACK, HIGH_RISK_SANCTIONED
    cpi_score: int  # Transparency Intl Corruption Perception Index (0-100, higher = cleaner)
    is_offshore_tax_haven: bool
    is_comprehensively_sanctioned: bool
    risk_tier: str  # LOW, MEDIUM, HIGH, PROHIBITED
    risk_multiplier: float
    edd_mandatory: bool

JURISDICTION_PROFILES: Dict[str, CountryRiskProfile] = {
    "US": CountryRiskProfile(
        iso2="US",
        iso3="USA",
        country_name="United States of America",
        region="North America",
        basel_aml_index=4.35,
        fatf_status="COMPLIANT",
        cpi_score=69,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "GB": CountryRiskProfile(
        iso2="GB",
        iso3="GBR",
        country_name="United Kingdom",
        region="Europe",
        basel_aml_index=4.05,
        fatf_status="COMPLIANT",
        cpi_score=71,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "DE": CountryRiskProfile(
        iso2="DE",
        iso3="DEU",
        country_name="Germany",
        region="Europe",
        basel_aml_index=4.25,
        fatf_status="COMPLIANT",
        cpi_score=78,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "FR": CountryRiskProfile(
        iso2="FR",
        iso3="FRA",
        country_name="France",
        region="Europe",
        basel_aml_index=4.12,
        fatf_status="COMPLIANT",
        cpi_score=71,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "CH": CountryRiskProfile(
        iso2="CH",
        iso3="CHE",
        country_name="Switzerland",
        region="Europe",
        basel_aml_index=4.65,
        fatf_status="COMPLIANT",
        cpi_score=82,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "SG": CountryRiskProfile(
        iso2="SG",
        iso3="SGP",
        country_name="Singapore",
        region="Asia-Pacific",
        basel_aml_index=4.1,
        fatf_status="COMPLIANT",
        cpi_score=83,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "HK": CountryRiskProfile(
        iso2="HK",
        iso3="HKG",
        country_name="Hong Kong SAR",
        region="Asia-Pacific",
        basel_aml_index=4.95,
        fatf_status="COMPLIANT",
        cpi_score=75,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "JP": CountryRiskProfile(
        iso2="JP",
        iso3="JPN",
        country_name="Japan",
        region="Asia-Pacific",
        basel_aml_index=3.85,
        fatf_status="COMPLIANT",
        cpi_score=73,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "CA": CountryRiskProfile(
        iso2="CA",
        iso3="CAN",
        country_name="Canada",
        region="North America",
        basel_aml_index=4.4,
        fatf_status="COMPLIANT",
        cpi_score=76,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "AU": CountryRiskProfile(
        iso2="AU",
        iso3="AUS",
        country_name="Australia",
        region="Asia-Pacific",
        basel_aml_index=4.3,
        fatf_status="COMPLIANT",
        cpi_score=75,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "NL": CountryRiskProfile(
        iso2="NL",
        iso3="NLD",
        country_name="Netherlands",
        region="Europe",
        basel_aml_index=4.02,
        fatf_status="COMPLIANT",
        cpi_score=79,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "LU": CountryRiskProfile(
        iso2="LU",
        iso3="LUX",
        country_name="Luxembourg",
        region="Europe",
        basel_aml_index=4.7,
        fatf_status="COMPLIANT",
        cpi_score=78,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "IE": CountryRiskProfile(
        iso2="IE",
        iso3="IRL",
        country_name="Ireland",
        region="Europe",
        basel_aml_index=4.15,
        fatf_status="COMPLIANT",
        cpi_score=77,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "KY": CountryRiskProfile(
        iso2="KY",
        iso3="CYM",
        country_name="Cayman Islands",
        region="Caribbean",
        basel_aml_index=5.25,
        fatf_status="INCREASED_MONITORING",
        cpi_score=65,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "VG": CountryRiskProfile(
        iso2="VG",
        iso3="VGB",
        country_name="British Virgin Islands",
        region="Caribbean",
        basel_aml_index=5.6,
        fatf_status="INCREASED_MONITORING",
        cpi_score=60,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "BM": CountryRiskProfile(
        iso2="BM",
        iso3="BMU",
        country_name="Bermuda",
        region="Caribbean",
        basel_aml_index=4.8,
        fatf_status="COMPLIANT",
        cpi_score=68,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "JE": CountryRiskProfile(
        iso2="JE",
        iso3="JEY",
        country_name="Jersey",
        region="Channel Islands",
        basel_aml_index=4.45,
        fatf_status="COMPLIANT",
        cpi_score=74,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "GG": CountryRiskProfile(
        iso2="GG",
        iso3="GGY",
        country_name="Guernsey",
        region="Channel Islands",
        basel_aml_index=4.48,
        fatf_status="COMPLIANT",
        cpi_score=74,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "IM": CountryRiskProfile(
        iso2="IM",
        iso3="IMN",
        country_name="Isle of Man",
        region="Europe",
        basel_aml_index=4.52,
        fatf_status="COMPLIANT",
        cpi_score=73,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "AE": CountryRiskProfile(
        iso2="AE",
        iso3="ARE",
        country_name="United Arab Emirates",
        region="Middle East",
        basel_aml_index=5.85,
        fatf_status="COMPLIANT",
        cpi_score=68,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "SA": CountryRiskProfile(
        iso2="SA",
        iso3="SAU",
        country_name="Saudi Arabia",
        region="Middle East",
        basel_aml_index=4.82,
        fatf_status="COMPLIANT",
        cpi_score=52,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "QA": CountryRiskProfile(
        iso2="QA",
        iso3="QAT",
        country_name="Qatar",
        region="Middle East",
        basel_aml_index=4.9,
        fatf_status="COMPLIANT",
        cpi_score=58,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "KP": CountryRiskProfile(
        iso2="KP",
        iso3="PRK",
        country_name="Democratic People's Republic of Korea",
        region="East Asia",
        basel_aml_index=9.85,
        fatf_status="CALL_FOR_ACTION_BLACK",
        cpi_score=17,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=True,
        risk_tier="PROHIBITED",
        risk_multiplier=5.0,
        edd_mandatory=True
    ),
    "IR": CountryRiskProfile(
        iso2="IR",
        iso3="IRN",
        country_name="Islamic Republic of Iran",
        region="Middle East",
        basel_aml_index=8.95,
        fatf_status="CALL_FOR_ACTION_BLACK",
        cpi_score=24,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=True,
        risk_tier="PROHIBITED",
        risk_multiplier=5.0,
        edd_mandatory=True
    ),
    "MM": CountryRiskProfile(
        iso2="MM",
        iso3="MMR",
        country_name="Myanmar (Burma)",
        region="Southeast Asia",
        basel_aml_index=8.2,
        fatf_status="CALL_FOR_ACTION_BLACK",
        cpi_score=20,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=True,
        risk_tier="PROHIBITED",
        risk_multiplier=5.0,
        edd_mandatory=True
    ),
    "RU": CountryRiskProfile(
        iso2="RU",
        iso3="RUS",
        country_name="Russian Federation",
        region="Eurasia",
        basel_aml_index=7.6,
        fatf_status="HIGH_RISK_SANCTIONED",
        cpi_score=26,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=True,
        risk_tier="PROHIBITED",
        risk_multiplier=5.0,
        edd_mandatory=True
    ),
    "BY": CountryRiskProfile(
        iso2="BY",
        iso3="BLR",
        country_name="Belarus",
        region="Eastern Europe",
        basel_aml_index=7.15,
        fatf_status="HIGH_RISK_SANCTIONED",
        cpi_score=37,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=True,
        risk_tier="PROHIBITED",
        risk_multiplier=5.0,
        edd_mandatory=True
    ),
    "SY": CountryRiskProfile(
        iso2="SY",
        iso3="SYR",
        country_name="Syrian Arab Republic",
        region="Middle East",
        basel_aml_index=8.8,
        fatf_status="INCREASED_MONITORING",
        cpi_score=13,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=True,
        risk_tier="PROHIBITED",
        risk_multiplier=5.0,
        edd_mandatory=True
    ),
    "YE": CountryRiskProfile(
        iso2="YE",
        iso3="YEM",
        country_name="Yemen",
        region="Middle East",
        basel_aml_index=7.95,
        fatf_status="INCREASED_MONITORING",
        cpi_score=16,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=True,
        risk_tier="PROHIBITED",
        risk_multiplier=5.0,
        edd_mandatory=True
    ),
    "VE": CountryRiskProfile(
        iso2="VE",
        iso3="VEN",
        country_name="Venezuela (Bolivarian Republic of)",
        region="South America",
        basel_aml_index=7.8,
        fatf_status="HIGH_RISK_SANCTIONED",
        cpi_score=13,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=True,
        risk_tier="PROHIBITED",
        risk_multiplier=5.0,
        edd_mandatory=True
    ),
    "CU": CountryRiskProfile(
        iso2="CU",
        iso3="CUB",
        country_name="Cuba",
        region="Caribbean",
        basel_aml_index=6.85,
        fatf_status="HIGH_RISK_SANCTIONED",
        cpi_score=42,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=True,
        risk_tier="PROHIBITED",
        risk_multiplier=5.0,
        edd_mandatory=True
    ),
    "SO": CountryRiskProfile(
        iso2="SO",
        iso3="SOM",
        country_name="Somalia",
        region="Sub-Saharan Africa",
        basel_aml_index=8.9,
        fatf_status="HIGH_RISK_FRAGILE",
        cpi_score=11,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "SS": CountryRiskProfile(
        iso2="SS",
        iso3="SSD",
        country_name="South Sudan",
        region="Sub-Saharan Africa",
        basel_aml_index=8.45,
        fatf_status="INCREASED_MONITORING",
        cpi_score=13,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "ML": CountryRiskProfile(
        iso2="ML",
        iso3="MLI",
        country_name="Mali",
        region="Sub-Saharan Africa",
        basel_aml_index=7.4,
        fatf_status="INCREASED_MONITORING",
        cpi_score=28,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "BF": CountryRiskProfile(
        iso2="BF",
        iso3="BFA",
        country_name="Burkina Faso",
        region="Sub-Saharan Africa",
        basel_aml_index=7.25,
        fatf_status="INCREASED_MONITORING",
        cpi_score=41,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "HT": CountryRiskProfile(
        iso2="HT",
        iso3="HTI",
        country_name="Haiti",
        region="Caribbean",
        basel_aml_index=7.75,
        fatf_status="INCREASED_MONITORING",
        cpi_score=17,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "CD": CountryRiskProfile(
        iso2="CD",
        iso3="COD",
        country_name="Democratic Republic of the Congo",
        region="Sub-Saharan Africa",
        basel_aml_index=8.1,
        fatf_status="INCREASED_MONITORING",
        cpi_score=20,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "MZ": CountryRiskProfile(
        iso2="MZ",
        iso3="MOZ",
        country_name="Mozambique",
        region="Sub-Saharan Africa",
        basel_aml_index=7.3,
        fatf_status="INCREASED_MONITORING",
        cpi_score=25,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "NG": CountryRiskProfile(
        iso2="NG",
        iso3="NGA",
        country_name="Nigeria",
        region="Sub-Saharan Africa",
        basel_aml_index=6.95,
        fatf_status="INCREASED_MONITORING",
        cpi_score=25,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "ZA": CountryRiskProfile(
        iso2="ZA",
        iso3="ZAF",
        country_name="South Africa",
        region="Sub-Saharan Africa",
        basel_aml_index=6.2,
        fatf_status="INCREASED_MONITORING",
        cpi_score=41,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "PH": CountryRiskProfile(
        iso2="PH",
        iso3="PHL",
        country_name="Philippines",
        region="Southeast Asia",
        basel_aml_index=5.9,
        fatf_status="INCREASED_MONITORING",
        cpi_score=34,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "VN": CountryRiskProfile(
        iso2="VN",
        iso3="VNM",
        country_name="Vietnam",
        region="Southeast Asia",
        basel_aml_index=6.8,
        fatf_status="INCREASED_MONITORING",
        cpi_score=41,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "PA": CountryRiskProfile(
        iso2="PA",
        iso3="PAN",
        country_name="Panama",
        region="Central America",
        basel_aml_index=6.45,
        fatf_status="COMPLIANT",
        cpi_score=35,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "BS": CountryRiskProfile(
        iso2="BS",
        iso3="BHS",
        country_name="Bahamas",
        region="Caribbean",
        basel_aml_index=5.15,
        fatf_status="COMPLIANT",
        cpi_score=64,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "BB": CountryRiskProfile(
        iso2="BB",
        iso3="BRB",
        country_name="Barbados",
        region="Caribbean",
        basel_aml_index=5.05,
        fatf_status="COMPLIANT",
        cpi_score=69,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "IN": CountryRiskProfile(
        iso2="IN",
        iso3="IND",
        country_name="India",
        region="South Asia",
        basel_aml_index=5.1,
        fatf_status="COMPLIANT",
        cpi_score=39,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "BR": CountryRiskProfile(
        iso2="BR",
        iso3="BRA",
        country_name="Brazil",
        region="South America",
        basel_aml_index=5.45,
        fatf_status="COMPLIANT",
        cpi_score=36,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "CN": CountryRiskProfile(
        iso2="CN",
        iso3="CHN",
        country_name="People's Republic of China",
        region="East Asia",
        basel_aml_index=5.75,
        fatf_status="COMPLIANT",
        cpi_score=42,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "MX": CountryRiskProfile(
        iso2="MX",
        iso3="MEX",
        country_name="Mexico",
        region="North America",
        basel_aml_index=5.65,
        fatf_status="COMPLIANT",
        cpi_score=31,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "ID": CountryRiskProfile(
        iso2="ID",
        iso3="IDN",
        country_name="Indonesia",
        region="Southeast Asia",
        basel_aml_index=5.2,
        fatf_status="COMPLIANT",
        cpi_score=37,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "TR": CountryRiskProfile(
        iso2="TR",
        iso3="TUR",
        country_name="Turkey",
        region="Europe/Middle East",
        basel_aml_index=6.1,
        fatf_status="COMPLIANT",
        cpi_score=34,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "PL": CountryRiskProfile(
        iso2="PL",
        iso3="POL",
        country_name="Poland",
        region="Europe",
        basel_aml_index=4.35,
        fatf_status="COMPLIANT",
        cpi_score=54,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "SE": CountryRiskProfile(
        iso2="SE",
        iso3="SWE",
        country_name="Sweden",
        region="Europe",
        basel_aml_index=3.8,
        fatf_status="COMPLIANT",
        cpi_score=82,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "NO": CountryRiskProfile(
        iso2="NO",
        iso3="NOR",
        country_name="Norway",
        region="Europe",
        basel_aml_index=3.75,
        fatf_status="COMPLIANT",
        cpi_score=84,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "DK": CountryRiskProfile(
        iso2="DK",
        iso3="DNK",
        country_name="Denmark",
        region="Europe",
        basel_aml_index=3.65,
        fatf_status="COMPLIANT",
        cpi_score=90,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "FI": CountryRiskProfile(
        iso2="FI",
        iso3="FIN",
        country_name="Finland",
        region="Europe",
        basel_aml_index=3.7,
        fatf_status="COMPLIANT",
        cpi_score=87,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "NZ": CountryRiskProfile(
        iso2="NZ",
        iso3="NZL",
        country_name="New Zealand",
        region="Asia-Pacific",
        basel_aml_index=3.7,
        fatf_status="COMPLIANT",
        cpi_score=85,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "AT": CountryRiskProfile(
        iso2="AT",
        iso3="AUT",
        country_name="Austria",
        region="Europe",
        basel_aml_index=4.2,
        fatf_status="COMPLIANT",
        cpi_score=71,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "BE": CountryRiskProfile(
        iso2="BE",
        iso3="BEL",
        country_name="Belgium",
        region="Europe",
        basel_aml_index=4.3,
        fatf_status="COMPLIANT",
        cpi_score=73,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "ES": CountryRiskProfile(
        iso2="ES",
        iso3="ESP",
        country_name="Spain",
        region="Europe",
        basel_aml_index=4.28,
        fatf_status="COMPLIANT",
        cpi_score=60,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "IT": CountryRiskProfile(
        iso2="IT",
        iso3="ITA",
        country_name="Italy",
        region="Europe",
        basel_aml_index=4.75,
        fatf_status="COMPLIANT",
        cpi_score=56,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "PT": CountryRiskProfile(
        iso2="PT",
        iso3="PRT",
        country_name="Portugal",
        region="Europe",
        basel_aml_index=4.32,
        fatf_status="COMPLIANT",
        cpi_score=61,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "GR": CountryRiskProfile(
        iso2="GR",
        iso3="GRC",
        country_name="Greece",
        region="Europe",
        basel_aml_index=4.88,
        fatf_status="COMPLIANT",
        cpi_score=49,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "CY": CountryRiskProfile(
        iso2="CY",
        iso3="CYP",
        country_name="Cyprus",
        region="Europe",
        basel_aml_index=5.35,
        fatf_status="COMPLIANT",
        cpi_score=53,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "MT": CountryRiskProfile(
        iso2="MT",
        iso3="MLT",
        country_name="Malta",
        region="Europe",
        basel_aml_index=5.1,
        fatf_status="COMPLIANT",
        cpi_score=51,
        is_offshore_tax_haven=True,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "KR": CountryRiskProfile(
        iso2="KR",
        iso3="KOR",
        country_name="Republic of Korea",
        region="East Asia",
        basel_aml_index=4.15,
        fatf_status="COMPLIANT",
        cpi_score=63,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "TW": CountryRiskProfile(
        iso2="TW",
        iso3="TWN",
        country_name="Taiwan",
        region="East Asia",
        basel_aml_index=4.12,
        fatf_status="COMPLIANT",
        cpi_score=67,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "IL": CountryRiskProfile(
        iso2="IL",
        iso3="ISR",
        country_name="Israel",
        region="Middle East",
        basel_aml_index=4.6,
        fatf_status="COMPLIANT",
        cpi_score=62,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "CL": CountryRiskProfile(
        iso2="CL",
        iso3="CHL",
        country_name="Chile",
        region="South America",
        basel_aml_index=4.55,
        fatf_status="COMPLIANT",
        cpi_score=66,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "CO": CountryRiskProfile(
        iso2="CO",
        iso3="COL",
        country_name="Colombia",
        region="South America",
        basel_aml_index=5.5,
        fatf_status="COMPLIANT",
        cpi_score=40,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "PE": CountryRiskProfile(
        iso2="PE",
        iso3="PER",
        country_name="Peru",
        region="South America",
        basel_aml_index=5.6,
        fatf_status="COMPLIANT",
        cpi_score=33,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "EG": CountryRiskProfile(
        iso2="EG",
        iso3="EGY",
        country_name="Egypt",
        region="North Africa",
        basel_aml_index=6.25,
        fatf_status="COMPLIANT",
        cpi_score=35,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "MA": CountryRiskProfile(
        iso2="MA",
        iso3="MAR",
        country_name="Morocco",
        region="North Africa",
        basel_aml_index=5.4,
        fatf_status="COMPLIANT",
        cpi_score=38,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "KE": CountryRiskProfile(
        iso2="KE",
        iso3="KEN",
        country_name="Kenya",
        region="Sub-Saharan Africa",
        basel_aml_index=6.75,
        fatf_status="INCREASED_MONITORING",
        cpi_score=31,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "GH": CountryRiskProfile(
        iso2="GH",
        iso3="GHA",
        country_name="Ghana",
        region="Sub-Saharan Africa",
        basel_aml_index=5.8,
        fatf_status="COMPLIANT",
        cpi_score=43,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "TH": CountryRiskProfile(
        iso2="TH",
        iso3="THA",
        country_name="Thailand",
        region="Southeast Asia",
        basel_aml_index=5.6,
        fatf_status="COMPLIANT",
        cpi_score=35,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "MY": CountryRiskProfile(
        iso2="MY",
        iso3="MYS",
        country_name="Malaysia",
        region="Southeast Asia",
        basel_aml_index=4.9,
        fatf_status="COMPLIANT",
        cpi_score=50,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="LOW",
        risk_multiplier=1.0,
        edd_mandatory=False
    ),
    "UA": CountryRiskProfile(
        iso2="UA",
        iso3="UKR",
        country_name="Ukraine",
        region="Eastern Europe",
        basel_aml_index=6.55,
        fatf_status="COMPLIANT",
        cpi_score=36,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="HIGH",
        risk_multiplier=2.5,
        edd_mandatory=True
    ),
    "KZ": CountryRiskProfile(
        iso2="KZ",
        iso3="KAZ",
        country_name="Kazakhstan",
        region="Central Asia",
        basel_aml_index=5.95,
        fatf_status="COMPLIANT",
        cpi_score=39,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
    "UZ": CountryRiskProfile(
        iso2="UZ",
        iso3="UZB",
        country_name="Uzbekistan",
        region="Central Asia",
        basel_aml_index=6.4,
        fatf_status="COMPLIANT",
        cpi_score=33,
        is_offshore_tax_haven=False,
        is_comprehensively_sanctioned=False,
        risk_tier="MEDIUM",
        risk_multiplier=1.5,
        edd_mandatory=False
    ),
}


def get_country_risk(code: str) -> Optional[CountryRiskProfile]:
    upper = code.strip().upper()
    if len(upper) == 2:
        return JURISDICTION_PROFILES.get(upper)
    for p in JURISDICTION_PROFILES.values():
        if p.iso3 == upper:
            return p
    return None

def is_jurisdiction_prohibited(code: str) -> bool:
    profile = get_country_risk(code)
    if not profile:
        return False
    return profile.risk_tier == "PROHIBITED" or profile.is_comprehensively_sanctioned

def calculate_jurisdiction_risk_score(country_codes: List[str]) -> Tuple[float, str, bool]:
    if not country_codes:
        return 2.5, "LOW", False

    max_multiplier = 1.0
    highest_tier = "LOW"
    edd_required = False
    scores = []

    for c in country_codes:
        p = get_country_risk(c)
        if not p:
            scores.append(5.0)
            continue
        scores.append(p.basel_aml_index)
        if p.risk_multiplier > max_multiplier:
            max_multiplier = p.risk_multiplier
            highest_tier = p.risk_tier
        if p.edd_mandatory:
            edd_required = True

    avg_score = sum(scores) / len(scores) if scores else 3.0
    composite_score = round(avg_score * max_multiplier, 2)
    return min(10.0, composite_score), highest_tier, edd_required
