"""
FATCA (Foreign Account Tax Compliance Act) & CRS (Common Reporting Standard) Tax Engine.
Manages chapter 4 statuses, GIIN validations, reportable jurisdiction matrices, and tax withholding.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple
import re

@dataclass
class FATCAClassification:
    code: str
    title: str
    description: str
    requires_giin: bool
    requires_controlling_person_disclosure: bool
    withholding_rate_pct: float

FATCA_CHAPTER_4_STATUSES: Dict[str, FATCAClassification] = {
    "PFFI": FATCAClassification(
        code="PFFI",
        title="Participating Foreign Financial Institution",
        description="FFI entering agreement directly with IRS",
        requires_giin=True,
        requires_controlling_person_disclosure=False,
        withholding_rate_pct=0.0
    ),
    "RDCFFI": FATCAClassification(
        code="RDCFFI",
        title="Registered Deemed-Compliant Foreign Financial Institution",
        description="Model 1 IGA reporting FFI",
        requires_giin=True,
        requires_controlling_person_disclosure=False,
        withholding_rate_pct=0.0
    ),
    "ACTIVE_NFFE": FATCAClassification(
        code="ACTIVE_NFFE",
        title="Active Non-Financial Foreign Entity",
        description="Commercial operating company with < 50% passive income and assets",
        requires_giin=False,
        requires_controlling_person_disclosure=False,
        withholding_rate_pct=0.0
    ),
    "PASSIVE_NFFE": FATCAClassification(
        code="PASSIVE_NFFE",
        title="Passive Non-Financial Foreign Entity",
        description="Investment entity or company with >= 50% passive income requiring UBO look-through",
        requires_giin=False,
        requires_controlling_person_disclosure=True,
        withholding_rate_pct=30.0
    ),
    "EXEMPT_BENEFICIAL_OWNER": FATCAClassification(
        code="EXEMPT_BENEFICIAL_OWNER",
        title="Exempt Beneficial Owner",
        description="Foreign government, sovereign wealth fund, central bank, international organization",
        requires_giin=False,
        requires_controlling_person_disclosure=False,
        withholding_rate_pct=0.0
    ),
    "NONPARTICIPATING_FFI": FATCAClassification(
        code="NONPARTICIPATING_FFI",
        title="Nonparticipating Foreign Financial Institution",
        description="FFI not complying with FATCA rules subject to 30% gross withholding",
        requires_giin=False,
        requires_controlling_person_disclosure=False,
        withholding_rate_pct=30.0
    ),
    "US_SPECIFIED_PERSON": FATCAClassification(
        code="US_SPECIFIED_PERSON",
        title="Specified US Person",
        description="US citizen, green card holder, or domestic corporation",
        requires_giin=False,
        requires_controlling_person_disclosure=False,
        withholding_rate_pct=0.0
    ),
    "DIRECT_REPORTING_NFFE": FATCAClassification(
        code="DIRECT_REPORTING_NFFE",
        title="Direct Reporting NFFE",
        description="NFFE that elects to report substantial US owners directly to the IRS",
        requires_giin=True,
        requires_controlling_person_disclosure=False,
        withholding_rate_pct=0.0
    ),
}

WITHHOLDING_TAX_TREATIES: Dict[Tuple[str, str], Dict[str, float]] = {
    ("US", "US"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("US", "GB"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("US", "DE"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("US", "FR"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("US", "CH"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("US", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("US", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("US", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("US", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("US", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("US", "NL"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("US", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("US", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("US", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("GB", "US"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("GB", "GB"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("GB", "DE"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("GB", "FR"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("GB", "CH"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("GB", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("GB", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("GB", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("GB", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("GB", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("GB", "NL"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("GB", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("GB", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("GB", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("DE", "US"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("DE", "GB"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("DE", "DE"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("DE", "FR"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("DE", "CH"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("DE", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("DE", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("DE", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("DE", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("DE", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("DE", "NL"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("DE", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("DE", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("DE", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("FR", "US"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("FR", "GB"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("FR", "DE"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("FR", "FR"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("FR", "CH"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("FR", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("FR", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("FR", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("FR", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("FR", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("FR", "NL"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("FR", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("FR", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("FR", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CH", "US"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CH", "GB"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CH", "DE"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CH", "FR"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CH", "CH"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CH", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CH", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CH", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CH", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CH", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CH", "NL"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CH", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CH", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CH", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("SG", "US"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("SG", "GB"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("SG", "DE"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("SG", "FR"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("SG", "CH"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("SG", "SG"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("SG", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("SG", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("SG", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("SG", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("SG", "NL"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("SG", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("SG", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("SG", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("HK", "US"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("HK", "GB"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("HK", "DE"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("HK", "FR"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("HK", "CH"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("HK", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("HK", "HK"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("HK", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("HK", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("HK", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("HK", "NL"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("HK", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("HK", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("HK", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("KY", "US"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "GB"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "DE"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "FR"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "CH"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "SG"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "HK"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "KY"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("KY", "LU"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "IE"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "NL"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "JP"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "CA"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("KY", "AU"): {"dividend_pct": 30.0, "interest_pct": 30.0, "royalty_pct": 30.0},
    ("LU", "US"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("LU", "GB"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("LU", "DE"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("LU", "FR"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("LU", "CH"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("LU", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("LU", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("LU", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("LU", "LU"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("LU", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("LU", "NL"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("LU", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("LU", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("LU", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("IE", "US"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("IE", "GB"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("IE", "DE"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("IE", "FR"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("IE", "CH"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("IE", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("IE", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("IE", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("IE", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("IE", "IE"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("IE", "NL"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("IE", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("IE", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("IE", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("NL", "US"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("NL", "GB"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("NL", "DE"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("NL", "FR"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("NL", "CH"): {"dividend_pct": 5.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("NL", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("NL", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("NL", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("NL", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("NL", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("NL", "NL"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("NL", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("NL", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("NL", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("JP", "US"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("JP", "GB"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("JP", "DE"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("JP", "FR"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("JP", "CH"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("JP", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("JP", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("JP", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("JP", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("JP", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("JP", "NL"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("JP", "JP"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("JP", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("JP", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CA", "US"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CA", "GB"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CA", "DE"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CA", "FR"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CA", "CH"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CA", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CA", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CA", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CA", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CA", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CA", "NL"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CA", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("CA", "CA"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("CA", "AU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("AU", "US"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("AU", "GB"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("AU", "DE"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("AU", "FR"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("AU", "CH"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("AU", "SG"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("AU", "HK"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("AU", "KY"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("AU", "LU"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("AU", "IE"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("AU", "NL"): {"dividend_pct": 15.0, "interest_pct": 0.0, "royalty_pct": 0.0},
    ("AU", "JP"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("AU", "CA"): {"dividend_pct": 15.0, "interest_pct": 10.0, "royalty_pct": 10.0},
    ("AU", "AU"): {"dividend_pct": 0.0, "interest_pct": 0.0, "royalty_pct": 0.0},
}


def validate_giin(giin: str) -> bool:
    if not giin:
        return False
    pattern = r'^[A-Z0-9]{6}\.[A-Z0-9]{5}\.[A-Z0-9]{2}\.[A-Z0-9]{3}$'
    return bool(re.match(pattern, giin.strip().upper()))

def calculate_withholding_rate(beneficiary_country: str, payer_country: str, income_type: str = "dividend_pct") -> float:
    key = (beneficiary_country.upper(), payer_country.upper())
    rates = WITHHOLDING_TAX_TREATIES.get(key)
    if not rates:
        return 30.0
    return rates.get(income_type, 30.0)
